---
title: "Tutorial Exercises Week 4 - Solutions"
format:
  html:
    theme: cosmos
    mainfont: "Fira Sans"
    monofont: "Fira Mono"
    html-math-method: katex
    toc: true
    code-copy: true
    code-fold: false
    code-link: false
    code-tools: false
    css: style.css
---
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fira+Mono&family=Fira+Sans&display=swap" rel="stylesheet">

#### Question 1 {-}

The dot product of two equal-length vectors $\boldsymbol{x}=\left(x_1,\dots, x_n\right)$ and $\boldsymbol{y}=\left(y_1,\dots,y_n\right)$ is given by:

$$
\boldsymbol{x}\cdot \boldsymbol{y} = \sum_{i=1}^n x_i y_i
$$
Calculate the dot product of the two lists of numbers below in two ways:

1. Using only Python's built-in functions (such as with a `for` loop or list comprehensions).
2. Using `numpy` with the `np.dot()` function.

```{python}
x = [2, 6, 4, 9, 10]
y = [11, 5, 3, 9, 2]
```

```{python}
# For loop approach:
z = 0
for i in range(len(x)):
  z += x[i] * y[i]
z  
```

```{python}
# List comprehension approach:
sum([i * j for i, j in zip(x, y)])
```

```{python}
import numpy as np
np.dot(x, y)
```


#### Question 2 {-}

For each question, the input list has $n$ elements, which we write as $x=[x_1, x_2, \dots, x_n]$. Note that although the first element of $x$ is $x_1$, it is accessed by `x[0]` in Python.

**NOTE:** You must answer this question **without using any modules**. Using `numpy`, `math`, and other modules is not permitted in this question.

Denote by $y$ the sorted version of the list $x$, where the first element $y_1$ is the smallest and the last element $y_n$ is the largest.

Create a function called $quantile(x, q)$ which returns the number in $x$ in the $q\times 100$th percentile. It is defined as follows:

$$
quantile(x, q)= q y_{\lfloor q\left(n+1\right) \rfloor} +(1-q)y_{\lceil q\left(n+1\right) \rceil}
$$
where:

- $y$ is $x$ sorted ascending.
- $\lfloor z \rfloor$ is the floor function which returns the number $z$ rounded *down* to the nearest integer
- $\lceil z \rceil$ is the ceiling function which returns the number $z$ rounded *up* to the nearest integer.

For example, consider obtaining the median (the case when $q=0.5$) of a list of either 4 or 5 numbers:

- If $q=0.5$ and $n=4$, then $q\left(n+1\right)=2.5$, so $\lfloor 2.5\rfloor = 2$ and $\lceil 2.5 \rceil = 3$. We get $quantile(x,q)=0.5 y_2 + 0.5 y_3$, the average of the two numbers in the middle of $[y_1,y_2,y_3,y_4]$.
- If $q=0.5$ and $n=5$, then $q\left(n+1\right)=3$. Both the floor and ceiling of 3 is 3, so $quantile(x, q)=0.5 y_3 + 0.5 y_3 = y_3$, the number in the middle of $[y_1,y_2,y_3,y_4,y_5]$.

Towards answering this, first create two functions $floor(z)$ and $ceil(z)$ which returns $\lfloor z \rfloor$ and $\lceil z \rceil$, respectively, for a single number $z$. To help you do this, we provide code for the `floor` function to you:
```
def floor(z):
    if z < 0 and z != int(z):
        return int(z) - 1
    else:
        return int(z)
```
This function makes use of the fact that the `int` function rounds a number towards zero. If $z$ is positive, it rounds down, but if $z$ is negative, it rounds up.

Define an analogous $ceil(z)$ function, and use both to create the function $quantile(x, q)$.

**Answer:**
```{python}
def floor(z):
    if z < 0 and z != int(z):
        return int(z) - 1
    else:
        return int(z)

def ceil(z):
    if z > 0 and z != int(z):
        return int(z) + 1
    else:
        return int(z)

def quantile(x, q):
    y = sorted(x)
    n = len(x)
    return q * y[floor(q * (n + 1)) - 1] + (1 - q) * y[ceil(q * (n + 1)) - 1]

# Test it out:
quantile([3, 2, 5, 4, 1], 0.5)
```

```{python}
quantile([3, 2, 5, 4], 0.5)
```

#### Question 3 {-}

The transpose of a matrix $\boldsymbol{A}$, denoted $\boldsymbol{A}^\prime$, is obtained by replacing each element $a_{ij}$ with $a_{ji}$. It flips the matrix over its diagonal. Define your own Python function that transposes a matrix.

The function should take as input a matrix given in the form of list of lists, where each element of the outer list denotes a row, and each inner list gives the elements of that row. This way, element $a_{ij}$ can be accessed with `A[i][j]`. Your function should not use any functions from the `numpy` module.

Test your function using the following matrix:
$$
\boldsymbol{A} = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ \end{pmatrix}
$$

**Answer:**
```{python}

def my_transpose(M):

    num_rows = len(M)
    num_cols = len(M[0])

    out = []  # initialize output

    # Columns of the input are the rows of the output, so outer loop runs
    # over columns:
    for j in range(num_cols):
        out_j = []  # initial row of output
        for i in range(num_rows):
            out_j.append(M[i][j])  # element (j,i) of output is (i,j) of input
        out.append(out_j)
    return out

A = [
    [1, 2, 3],
    [4, 5, 6]
]
A_prime = my_transpose(A)

for row in A_prime:
    print(row)

```

#### Question 4 {-}

Write a function that converts integers into roman numerals. You may find the following dictionary useful to do this:

```{python}
roman = {
  'I'  : 1,
  'IV' : 4,
  'V'  : 5,
  'IX' : 9,
  'X'  : 10,
  'XL' : 40,
  'L'  : 50,
  'XC' : 90,
  'C'  : 100,
  'CD' : 400,
  'D'  : 500,
  'CM' : 900,
  'M'  : 1000
}
```
*Hint*: A good way to do this is to repeatedly loop through the values in the dictionary above backwards combining all the Roman numerals. For each iteration:

- If the input number is bigger or equal to the value, take the corresponding roman numeral and subtract the value from the input number.
- Otherwise try the next value.

This continues until the input number goes to zero.

```{python}
def int2roman(x):
    out = ''   # output string that we will add to in the loop
    for numeral, value in reversed(roman.items()):
        while x >= value:
            out += numeral  # add numeral to output string
            x -= value      # reduce input value
    return out
```

Try out some values:
```{python}
[int2roman(i) for i in [1, 3, 4, 6, 49, 101, 1989, 2024]]
```

