<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Programming for the TiSEM Minor in Essential Digital Skills - 8&nbsp; Introduction to Pandas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<link href="./data-visualization.html" rel="next">
<link href="./numpy.html" rel="prev">
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./pandas.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introduction to Pandas</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Programming for the TiSEM Minor in Essential Digital Skills</a> 
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">About</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./python-as-a-calculator.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Python as a Calculator</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-types-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variables and Data Types for Single Values</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-types-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Types for Multiple Values</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./defining-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Defining Functions and Conditional Execution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numpy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to NumPy</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pandas.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introduction to Pandas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Univariate Unconstrained Optimization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Classes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./errors-and-debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Errors and debugging</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#tabular-data-and-csv-files" id="toc-tabular-data-and-csv-files" class="nav-link active" data-scroll-target="#tabular-data-and-csv-files"><span class="header-section-number">8.1</span> Tabular Data and CSV Files</a>
  <ul class="collapse">
  <li><a href="#tabular-data" id="toc-tabular-data" class="nav-link" data-scroll-target="#tabular-data"><span class="header-section-number">8.1.1</span> Tabular Data</a></li>
  <li><a href="#comma-separated-value-files" id="toc-comma-separated-value-files" class="nav-link" data-scroll-target="#comma-separated-value-files"><span class="header-section-number">8.1.2</span> Comma-Separated Value Files</a></li>
  </ul></li>
  <li><a href="#reading-csv-files-into-python" id="toc-reading-csv-files-into-python" class="nav-link" data-scroll-target="#reading-csv-files-into-python"><span class="header-section-number">8.2</span> Reading CSV Files into Python</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning"><span class="header-section-number">8.3</span> Data Cleaning</a>
  <ul class="collapse">
  <li><a href="#dropping-variables" id="toc-dropping-variables" class="nav-link" data-scroll-target="#dropping-variables"><span class="header-section-number">8.3.1</span> Dropping Variables</a></li>
  <li><a href="#dropping-rows-with-missing-vales" id="toc-dropping-rows-with-missing-vales" class="nav-link" data-scroll-target="#dropping-rows-with-missing-vales"><span class="header-section-number">8.3.2</span> Dropping Rows with Missing Vales</a></li>
  <li><a href="#creating-new-variables" id="toc-creating-new-variables" class="nav-link" data-scroll-target="#creating-new-variables"><span class="header-section-number">8.3.3</span> Creating New Variables</a></li>
  <li><a href="#renaming-variables" id="toc-renaming-variables" class="nav-link" data-scroll-target="#renaming-variables"><span class="header-section-number">8.3.4</span> Renaming Variables</a></li>
  </ul></li>
  <li><a href="#describing-data" id="toc-describing-data" class="nav-link" data-scroll-target="#describing-data"><span class="header-section-number">8.4</span> Describing Data</a></li>
  <li><a href="#subsetting" id="toc-subsetting" class="nav-link" data-scroll-target="#subsetting"><span class="header-section-number">8.5</span> Subsetting</a></li>
  <li><a href="#group-by-operations" id="toc-group-by-operations" class="nav-link" data-scroll-target="#group-by-operations"><span class="header-section-number">8.6</span> Group by operations</a></li>
  <li><a href="#applying-functions-in-pandas" id="toc-applying-functions-in-pandas" class="nav-link" data-scroll-target="#applying-functions-in-pandas"><span class="header-section-number">8.7</span> Applying functions in Pandas</a></li>
  <li><a href="#exporting-data" id="toc-exporting-data" class="nav-link" data-scroll-target="#exporting-data"><span class="header-section-number">8.8</span> Exporting Data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-pandas" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introduction to Pandas</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<p>Now that we have learned the basics, it’s time to learn how to work with real data in Python.</p>
<section id="tabular-data-and-csv-files" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="tabular-data-and-csv-files"><span class="header-section-number">8.1</span> Tabular Data and CSV Files</h2>
<section id="tabular-data" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="tabular-data"><span class="header-section-number">8.1.1</span> Tabular Data</h3>
<p>Very often data are in <em>tabular</em> format, where columns represent variables and rows indicate observations, or records. For example, consider the following data on firm sales from two regions for different dates:</p>
<table class="table">
<thead>
<tr class="header">
<th>date</th>
<th>region</th>
<th>sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024-06-01</td>
<td>north</td>
<td>342</td>
</tr>
<tr class="even">
<td>2024-06-01</td>
<td>south</td>
<td>251</td>
</tr>
<tr class="odd">
<td>2024-06-02</td>
<td>north</td>
<td>489</td>
</tr>
<tr class="even">
<td>2024-06-02</td>
<td>south</td>
<td>372</td>
</tr>
<tr class="odd">
<td>2024-06-03</td>
<td>north</td>
<td>589</td>
</tr>
<tr class="even">
<td>2024-06-03</td>
<td>south</td>
<td>492</td>
</tr>
</tbody>
</table>
<p>There are 3 columns representing the variables <code>date</code>, <code>region</code> and <code>sales</code>, and the 6 rows under the variable names contain the individual observations. For example, the first observation is the sales on June 1 in the Northern region.</p>
</section>
<section id="comma-separated-value-files" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="comma-separated-value-files"><span class="header-section-number">8.1.2</span> Comma-Separated Value Files</h3>
<p>Such data would often be stored in <em>comma-separated value</em> (CSV) format, which have the file extension <code>.csv</code>. The contents of a file containing these data would look like:</p>
<pre><code>date,region,sales
2024-06-01,north,342
2024-06-01,south,251
2024-06-02,north,489
2024-06-02,south,372
2024-06-03,north,589
2024-06-03,south,492</code></pre>
<p>The variable names are on the first line, separated by commans, and the values for each variable on each subsequent line, also separated by commas. The commas therefore serve to separate the variables.</p>
<p>Sometimes variables can contain values that include commas. For example, if comma decimal separators are used, or a variable contains text that has commas. Consider this alternative example:</p>
<table class="table">
<thead>
<tr class="header">
<th>date</th>
<th>regions</th>
<th>revenue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2025-07-01</td>
<td>north,west</td>
<td>3423,40</td>
</tr>
<tr class="even">
<td>2025-07-01</td>
<td>south,east</td>
<td>4352,45</td>
</tr>
<tr class="odd">
<td>2025-07-02</td>
<td>north,west</td>
<td>3635,30</td>
</tr>
<tr class="even">
<td>2025-07-02</td>
<td>south,east</td>
<td>4252,53</td>
</tr>
<tr class="odd">
<td>2025-07-03</td>
<td>north,west</td>
<td>3734,35</td>
</tr>
<tr class="even">
<td>2025-07-03</td>
<td>south,east</td>
<td>4742,67</td>
</tr>
</tbody>
</table>
<p>Here there are two sets of regions: a “North, West” and “South, East”. The revenue variable also uses commas to separate the euros and the cents. Naturally this can cause some problems if commas are used to separate the variables.</p>
<p>Suppose we stored these data in a CSV file like this:</p>
<pre><code>date,regions,revenue
2025-07-01,north,west,3423,40
2025-07-01,south,east,4352,45
2025-07-02,north,west,3635,30
2025-07-02,south,east,4252,53
2025-07-03,north,west,3734,35
2025-07-03,south,east,4742,67</code></pre>
<p>Then the program reading the data would see from line 1 that there are 3 variables. However, it would think that there are 5 values on line 2: (i) 2025-07-01, (ii) north, (iii) west, (iv) 3423 and (v) 40. This is clearly not what we want.</p>
<p>To prevent the program reading the data to interpret these commas as separating the values, we can use quotation marks around the values:</p>
<pre><code>"date","regions","revenue"
"2025-07-01","north,west","3423,40"
"2025-07-01","south,east","4352,45"
"2025-07-02","north,west","3635,30"
"2025-07-02","south,east","4252,53"
"2025-07-03","north,west","3734,35"
"2025-07-03","south,east","4742,67"</code></pre>
</section>
</section>
<section id="reading-csv-files-into-python" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="reading-csv-files-into-python"><span class="header-section-number">8.2</span> Reading CSV Files into Python</h2>
<p>Although it is possible to read in data from a CSV into Python using the standard Python library (i.e.&nbsp;no modules), it is much easier and more common to use the <a href="https://pandas.pydata.org/">Pandas</a> module. This module also contains a large library of functions which are very useful for working with datasets.</p>
<p>We will learn how to use Pandas together with a dataset on Amsterdam House Prices from <a href="https://www.kaggle.com/datasets/thomasnibb/amsterdam-house-price-prediction">Kaggle</a>, which is a website that contains many datasets you can explore. You can download the extracted data directly <a href="https://walshc.github.io/eds-prog-data/HousingPrices-Amsterdam-August-2021.csv">here</a>.</p>
<p>If using Spyder, you should move the data file from your downloads folder to the folder where you are writing your Python script to analyze it. This way don’t need to provide the full file path to the file in our code. <em>Note:</em> Although you can open this CSV file with MS Excel or another spreadsheet software to look at it, do <strong>not</strong> use “Save” or “Save As” to change the file’s location. MS Excel may change the structure of the file, which can cause problems. Use your file browser to move the file instead.</p>
<p>If the data is now in the same folder as your Python script, you can use the following code to read in the data:</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"HousingPrices-Amsterdam-August-2021.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similar to how <code>numpy</code> is typically imported with the alias <code>np</code>, <code>pandas</code> is typically imported as <code>pd</code>. To read in a CSV dataset, we use the <code>read_csv()</code> function in Pandas. We provide the file name as the single argument to this function. In this code I have assigned the output of the <code>read_csv()</code> function to the name <code>df</code>, which is short for <code>DataFrame</code>, the data type that <code>pandas</code> reads the file in as. You don’t need to call it <code>df</code>, but this name is commonly used.</p>
<p>Let’s take a look what what happens when we print <code>df</code>:</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Unnamed: 0                                 Address      Zip     Price  \
0             1            Blasiusstraat 8 2, Amsterdam  1091 CR  685000.0   
1             2  Kromme Leimuidenstraat 13 H, Amsterdam  1059 EL  475000.0   
2             3              Zaaiersweg 11 A, Amsterdam  1097 SM  850000.0   
3             4            Tenerifestraat 40, Amsterdam  1060 TH  580000.0   
4             5              Winterjanpad 21, Amsterdam  1036 KN  720000.0   
..          ...                                     ...      ...       ...   
919         920                     Ringdijk, Amsterdam  1097 AE  750000.0   
920         921         Kleine Beerstraat 31, Amsterdam  1033 CP  350000.0   
921         922       Stuyvesantstraat 33 II, Amsterdam  1058 AK  350000.0   
922         923   John Blankensteinstraat 51, Amsterdam  1095 MB  599000.0   
923         924      S. F. van Ossstraat 334, Amsterdam  1068 JS  300000.0   

     Area  Room       Lon        Lat  
0      64     3  4.907736  52.356157  
1      60     3  4.850476  52.348586  
2     109     4  4.944774  52.343782  
3     128     6  4.789928  52.343712  
4     138     5  4.902503  52.410538  
..    ...   ...       ...        ...  
919   117     1  4.927757  52.354173  
920    72     3  4.890612  52.414587  
921    51     3  4.856935  52.363256  
922   113     4  4.965731  52.375268  
923    79     4  4.810678  52.355493  

[924 rows x 8 columns]</code></pre>
</div>
</div>
<p>We see that the data frame has 924 rows and 8 columns. We see the variable names and first and last 5 rows of data. It contains the street address, postcode, selling price, area (in square meters), number of rooms, and the GPS coordinates (latitude and longitude).</p>
</section>
<section id="data-cleaning" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="data-cleaning"><span class="header-section-number">8.3</span> Data Cleaning</h2>
<p>Very often when we read in data we need to make some adjustments before it is ready to be analyzed. We might want to drop some variables or some rows, create new variables from existing ones, or change variable names. Let’s take a look at some examples of these with these data.</p>
<section id="dropping-variables" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="dropping-variables"><span class="header-section-number">8.3.1</span> Dropping Variables</h3>
<p>The first variable, <code>Unnamed: 0</code> is just a row index from 1 to 924. This variable is useless so we can drop it from the data using the <code>drop</code> method:</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df.drop(<span class="st">'Unnamed: 0'</span>, axis<span class="op">=</span><span class="dv">1</span>, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, the <code>axis=1</code> option means I want to drop a column (it would be 0 for a row), and <code>inplace=True</code> means it modifies <code>df</code> in place. Without this second option we would have to assign the output of the command back to <code>df</code> with the command like this:</p>
<pre><code>df = df.drop('Unnamed: 0', axis=1)</code></pre>
</section>
<section id="dropping-rows-with-missing-vales" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="dropping-rows-with-missing-vales"><span class="header-section-number">8.3.2</span> Dropping Rows with Missing Vales</h3>
<p>The method <code>.isna()</code> returns for each value <code>True</code> if the value is missing and <code>False</code> otherwise. If we try it with our data we get:</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df.isna()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Address</th>
<th data-quarto-table-cell-role="th">Zip</th>
<th data-quarto-table-cell-role="th">Price</th>
<th data-quarto-table-cell-role="th">Area</th>
<th data-quarto-table-cell-role="th">Room</th>
<th data-quarto-table-cell-role="th">Lon</th>
<th data-quarto-table-cell-role="th">Lat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">919</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">920</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">921</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">922</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">923</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>924 rows × 7 columns</p>
</div>
</div>
</div>
<p>This isn’t very helpful because we only see the first and last 5 rows, none of which are missing. A better approach is to count the total number of missings per column using the <code>.sum()</code> method on this previous command:</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df.isna().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>Address    0
Zip        0
Price      4
Area       0
Room       0
Lon        0
Lat        0
dtype: int64</code></pre>
</div>
</div>
<p>Here we see that the variable <code>Price</code> has 4 missing values, whereas all the other variables have no missing values. Because we are mostly interested in the price of houses, we will want to drop these 4 values. But before we do, let’s take a look at the rows with the missing values. To do this, first let’s see how to extract the price variable from the DataFrame. We do that using the variable name in quotes, inside square brackets:</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Price'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>0      685000.0
1      475000.0
2      850000.0
3      580000.0
4      720000.0
         ...   
919    750000.0
920    350000.0
921    350000.0
922    599000.0
923    300000.0
Name: Price, Length: 924, dtype: float64</code></pre>
</div>
</div>
<p>To see which of these are missing we add <code>.isna()</code>:</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Price'</span>].isna()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>0      False
1      False
2      False
3      False
4      False
       ...  
919    False
920    False
921    False
922    False
923    False
Name: Price, Length: 924, dtype: bool</code></pre>
</div>
</div>
<p>This gives a <span class="math inline">924\times1</span> vector of <code>True</code> and <code>False</code>. To see the rows of <code>df</code> when this vector is <code>True</code>, we use the vector to index the DataFrame as follows:</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df[df[<span class="st">'Price'</span>].isna()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Address</th>
<th data-quarto-table-cell-role="th">Zip</th>
<th data-quarto-table-cell-role="th">Price</th>
<th data-quarto-table-cell-role="th">Area</th>
<th data-quarto-table-cell-role="th">Room</th>
<th data-quarto-table-cell-role="th">Lon</th>
<th data-quarto-table-cell-role="th">Lat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">73</td>
<td>Falckstraat 47 A, Amsterdam</td>
<td>1017 VV</td>
<td>NaN</td>
<td>147</td>
<td>3</td>
<td>4.897454</td>
<td>52.360707</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">321</td>
<td>Haarlemmerweg 705, Amsterdam</td>
<td>1067 HP</td>
<td>NaN</td>
<td>366</td>
<td>12</td>
<td>4.787874</td>
<td>52.383877</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">610</td>
<td>Zeeburgerkade 760, Amsterdam</td>
<td>1019 HT</td>
<td>NaN</td>
<td>107</td>
<td>3</td>
<td>4.945022</td>
<td>52.369244</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">727</td>
<td>Suikerplein 16, Amsterdam</td>
<td>1013 CK</td>
<td>NaN</td>
<td>81</td>
<td>3</td>
<td>4.880976</td>
<td>52.389623</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Now we can see which rows have a missing price. Now that we have identified these we might be happy to drop these from our data.</p>
<p>One way to do this would be to keep all rows where price is <em>not</em> missing. To get a vector that is <code>True</code> when price is not missing and <code>False</code> otherwise we just need to flip the result of <code>df['Price'].isna()</code>. We can do that with the <code>~</code> symbol:</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="op">~</span>df[<span class="st">'Price'</span>].isna()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>0      True
1      True
2      True
3      True
4      True
       ... 
919    True
920    True
921    True
922    True
923    True
Name: Price, Length: 924, dtype: bool</code></pre>
</div>
</div>
<p>Using this vector to index the data keeps only the rows with complete values:</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[<span class="op">~</span>df[<span class="st">'Price'</span>].isna()]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Address</th>
<th data-quarto-table-cell-role="th">Zip</th>
<th data-quarto-table-cell-role="th">Price</th>
<th data-quarto-table-cell-role="th">Area</th>
<th data-quarto-table-cell-role="th">Room</th>
<th data-quarto-table-cell-role="th">Lon</th>
<th data-quarto-table-cell-role="th">Lat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Blasiusstraat 8 2, Amsterdam</td>
<td>1091 CR</td>
<td>685000.0</td>
<td>64</td>
<td>3</td>
<td>4.907736</td>
<td>52.356157</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Kromme Leimuidenstraat 13 H, Amsterdam</td>
<td>1059 EL</td>
<td>475000.0</td>
<td>60</td>
<td>3</td>
<td>4.850476</td>
<td>52.348586</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Zaaiersweg 11 A, Amsterdam</td>
<td>1097 SM</td>
<td>850000.0</td>
<td>109</td>
<td>4</td>
<td>4.944774</td>
<td>52.343782</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Tenerifestraat 40, Amsterdam</td>
<td>1060 TH</td>
<td>580000.0</td>
<td>128</td>
<td>6</td>
<td>4.789928</td>
<td>52.343712</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Winterjanpad 21, Amsterdam</td>
<td>1036 KN</td>
<td>720000.0</td>
<td>138</td>
<td>5</td>
<td>4.902503</td>
<td>52.410538</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">919</td>
<td>Ringdijk, Amsterdam</td>
<td>1097 AE</td>
<td>750000.0</td>
<td>117</td>
<td>1</td>
<td>4.927757</td>
<td>52.354173</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">920</td>
<td>Kleine Beerstraat 31, Amsterdam</td>
<td>1033 CP</td>
<td>350000.0</td>
<td>72</td>
<td>3</td>
<td>4.890612</td>
<td>52.414587</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">921</td>
<td>Stuyvesantstraat 33 II, Amsterdam</td>
<td>1058 AK</td>
<td>350000.0</td>
<td>51</td>
<td>3</td>
<td>4.856935</td>
<td>52.363256</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">922</td>
<td>John Blankensteinstraat 51, Amsterdam</td>
<td>1095 MB</td>
<td>599000.0</td>
<td>113</td>
<td>4</td>
<td>4.965731</td>
<td>52.375268</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">923</td>
<td>S. F. van Ossstraat 334, Amsterdam</td>
<td>1068 JS</td>
<td>300000.0</td>
<td>79</td>
<td>4</td>
<td>4.810678</td>
<td>52.355493</td>
</tr>
</tbody>
</table>

<p>920 rows × 7 columns</p>
</div>
</div>
</div>
<p>We can see now that we have lost 4 rows, the rows with the missing values for price.</p>
<p>Another way to drop rows with missing values is the following command:</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df.dropna(inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This drops all rows with a missing value contained anywhere in it. This looks easier than what we did before, but an important part of data cleaning is to understand where the missings are, how many there are and why they might be there. Dropping rows blindly could lead to unexpected outcomes and should be avoided.</p>
</section>
<section id="creating-new-variables" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="creating-new-variables"><span class="header-section-number">8.3.3</span> Creating New Variables</h3>
<p>In real estate, a common variable is the price per square meter. We have the price and the number of square meters (variable <code>Area</code>), so we can calculate this variable from our existing data.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'price_per_sqm'</span>] <span class="op">=</span> df[<span class="st">'Price'</span>] <span class="op">/</span> df[<span class="st">'Area'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="renaming-variables" class="level3" data-number="8.3.4">
<h3 data-number="8.3.4" class="anchored" data-anchor-id="renaming-variables"><span class="header-section-number">8.3.4</span> Renaming Variables</h3>
<p>Sometimes we want to change variable names. We can see all the variable names using the command <code>df.columns</code>:</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>Index(['Address', 'Zip', 'Price', 'Area', 'Room', 'Lon', 'Lat',
       'price_per_sqm'],
      dtype='str')</code></pre>
</div>
</div>
<p>Calling the postcode <code>"Zip"</code> makes no sense for 2 reasons:</p>
<ol type="1">
<li>ZIP is an acronym for Zone Improvement Plan, and should be all upper case, and</li>
<li>ZIP codes are only used in the US, and so not in Amsterdam.</li>
</ol>
<p>So let’s rename this variable to postcode. We might also want to rename the variable <code>"Room"</code> to <code>"num_rooms"</code> to be more descriptive. To change the names of a subset of variables we can use the <code>rename</code> method and provide a dictionary to the <code>columns</code> argument, where the keys of the dictionary are the old names and the corresponding values are the new names. We do it all together with:</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df.rename(columns<span class="op">=</span>{<span class="st">"Zip"</span> : <span class="st">"postcode"</span>, <span class="st">"Room"</span> : <span class="st">"num_rooms"</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now our variable names have a mix of upper and lower case names, which is not so satisfying. Suppose I wanted to make all my variable names lower case. I can do that by replacing all column names with the lower case version of the names, which I can obtain using <code>df.columns.str.lower()</code>. To change the names to lower case I do:</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df.columns <span class="op">=</span> df.columns.<span class="bu">str</span>.lower()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="describing-data" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="describing-data"><span class="header-section-number">8.4</span> Describing Data</h2>
<p>Now that we have cleaned our data, it’s time to start analyzing it. We can get an overview of the main summary statistics for each numeric variable using the <code>.describe()</code> method:</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">area</th>
<th data-quarto-table-cell-role="th">num_rooms</th>
<th data-quarto-table-cell-role="th">lon</th>
<th data-quarto-table-cell-role="th">lat</th>
<th data-quarto-table-cell-role="th">price_per_sqm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>9.200000e+02</td>
<td>920.000000</td>
<td>920.00000</td>
<td>920.000000</td>
<td>920.000000</td>
<td>920.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>6.220654e+05</td>
<td>95.607609</td>
<td>3.56413</td>
<td>4.888652</td>
<td>52.363271</td>
<td>6479.852299</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>5.389942e+05</td>
<td>56.849699</td>
<td>1.57103</td>
<td>0.053118</td>
<td>0.024054</td>
<td>2219.265218</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1.750000e+05</td>
<td>21.000000</td>
<td>1.00000</td>
<td>4.644819</td>
<td>52.291519</td>
<td>2430.555556</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>3.500000e+05</td>
<td>60.000000</td>
<td>3.00000</td>
<td>4.855834</td>
<td>52.351925</td>
<td>4649.086379</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>4.670000e+05</td>
<td>83.000000</td>
<td>3.00000</td>
<td>4.886818</td>
<td>52.364499</td>
<td>6578.947368</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>7.000000e+05</td>
<td>113.000000</td>
<td>4.00000</td>
<td>4.922337</td>
<td>52.377545</td>
<td>7768.912530</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>5.950000e+06</td>
<td>623.000000</td>
<td>14.00000</td>
<td>5.029122</td>
<td>52.423805</td>
<td>25252.808989</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This gives the number of observations (920), the mean, standard deviation, minimum, 25th percentile, median, 75th percentile and maximum value for each numeric variable. Notice that address and postcode don’t appear here because they are strings (we can’t get the mean of a string variable). Because price is in euros, values are in the €175,000-€5.95m range. Therefore Python reports the numbers in scientific notation. <code>9.20e+02</code> is the same as <span class="math inline">9.2\times10^2=9.2\times 100=920</span>.</p>
<p>To get the mean of a single variable we can do:</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'price'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>np.float64(622065.4195652173)</code></pre>
</div>
</div>
<p>We can see above that the average house has 3.564 rooms. To see the distribution of the number of rooms we can use <code>value_counts()</code>:</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'num_rooms'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>num_rooms
3     330
4     201
2     191
5      97
6      42
7      19
1      17
8      11
9       6
13      2
10      2
14      2
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>This tells us that 330 observations had 3 rooms, 201 observations had 4 rooms, …, and 2 observations had 14 rooms. This shows 3 rooms first because it is the most common. To sort it by the number of rooms instead we can do:</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'num_rooms'</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>num_rooms
1      17
2     191
3     330
4     201
5      97
6      42
7      19
8      11
9       6
10      2
13      2
14      2
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>To get the proportion of observations with each number of rooms we can use the option <code>normalize=True</code>:</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'num_rooms'</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>num_rooms
3     0.358696
4     0.218478
2     0.207609
5     0.105435
6     0.045652
7     0.020652
1     0.018478
8     0.011957
9     0.006522
13    0.002174
10    0.002174
14    0.002174
Name: proportion, dtype: float64</code></pre>
</div>
</div>
<p>This tells us that 35.87% of houses sold had 3 rooms.</p>
</section>
<section id="subsetting" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="subsetting"><span class="header-section-number">8.5</span> Subsetting</h2>
<p>Suppose you want to see the average price of houses that satisfy certain criteria. Perhaps you want to know the average price of houses that have exactly 4 rooms. What we can do is first subset the data so that there are only observations with 4 rooms. Then using this subset we calculate the mean price. We can do this in steps as follows:</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df_four_rooms <span class="op">=</span> df[df[<span class="st">'num_rooms'</span>] <span class="op">==</span> <span class="dv">4</span>]</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>df_four_rooms[<span class="st">'price'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>np.float64(609845.0945273632)</code></pre>
</div>
</div>
<p>But it’s not necessary to create a whole new dataframe to do this operation. We can combine them into one command to avoid this:</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df[df[<span class="st">'num_rooms'</span>] <span class="op">==</span> <span class="dv">4</span>][<span class="st">'price'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>np.float64(609845.0945273632)</code></pre>
</div>
</div>
<p>Suppose I want to get the average price of houses that have exactly 4 rooms <em>and</em> have at least 100 square meters. I can combine logical vectors by putting them in parentheses and using the <code>&amp;</code> operator:</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df[(df[<span class="st">'num_rooms'</span>] <span class="op">==</span> <span class="dv">4</span>) <span class="op">&amp;</span> (df[<span class="st">'area'</span>] <span class="op">&gt;=</span> <span class="dv">100</span>)][<span class="st">'price'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>np.float64(859761.7764705883)</code></pre>
</div>
</div>
<p>We can also do <em>OR</em> operations. Suppose now I want to get the average price of houses that have at least 4 rooms <em>or</em> have at least 100 square meters. This is similar to before but we use <code>|</code> to represent <em>or</em>:</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>df[(df[<span class="st">'num_rooms'</span>] <span class="op">&gt;=</span> <span class="dv">4</span>) <span class="op">|</span> (df[<span class="st">'area'</span>] <span class="op">&gt;=</span> <span class="dv">100</span>)][<span class="st">'price'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>np.float64(847846.6853932585)</code></pre>
</div>
</div>
</section>
<section id="group-by-operations" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="group-by-operations"><span class="header-section-number">8.6</span> Group by operations</h2>
<p>Suppose now I want the average price of houses with exactly 1 room, exactly 2 rooms, exactly 3 rooms, and so on. I could use <code>df['num_rooms'].unique()</code> to get the unique values for the number of rooms and loop over these (sorting them first with <code>sorted()</code>):</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">sorted</span>(df[<span class="st">'num_rooms'</span>].unique()):</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"The average price of houses with"</span>, <span class="bu">str</span>(i),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>      <span class="st">"room"</span> <span class="cf">if</span> i <span class="op">==</span> <span class="dv">1</span> <span class="cf">else</span> <span class="st">"rooms"</span>, <span class="st">"is"</span>,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>        <span class="bu">str</span>(<span class="bu">round</span>(df[df[<span class="st">'num_rooms'</span>] <span class="op">==</span> i][<span class="st">'price'</span>].mean())))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average price of houses with 1 room is 394529
The average price of houses with 2 rooms is 383479
The average price of houses with 3 rooms is 512416
The average price of houses with 4 rooms is 609845
The average price of houses with 5 rooms is 845076
The average price of houses with 6 rooms is 919929
The average price of houses with 7 rooms is 1394737
The average price of houses with 8 rooms is 1751636
The average price of houses with 9 rooms is 1450000
The average price of houses with 10 rooms is 4300000
The average price of houses with 13 rooms is 4725000
The average price of houses with 14 rooms is 3772500</code></pre>
</div>
</div>
<p>But there is a much easier way to do this in Pandas using <code>groupby</code>. We simply do:</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df.groupby(<span class="st">'num_rooms'</span>)[<span class="st">'price'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>num_rooms
1     3.945294e+05
2     3.834791e+05
3     5.124164e+05
4     6.098451e+05
5     8.450764e+05
6     9.199286e+05
7     1.394737e+06
8     1.751636e+06
9     1.450000e+06
10    4.300000e+06
13    4.725000e+06
14    3.772500e+06
Name: price, dtype: float64</code></pre>
</div>
</div>
<p>For cleaner output we can add <code>round()</code> at the end:</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>df.groupby(<span class="st">'num_rooms'</span>)[<span class="st">'price'</span>].mean().<span class="bu">round</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>num_rooms
1      394529.0
2      383479.0
3      512416.0
4      609845.0
5      845076.0
6      919929.0
7     1394737.0
8     1751636.0
9     1450000.0
10    4300000.0
13    4725000.0
14    3772500.0
Name: price, dtype: float64</code></pre>
</div>
</div>
</section>
<section id="applying-functions-in-pandas" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="applying-functions-in-pandas"><span class="header-section-number">8.7</span> Applying functions in Pandas</h2>
<p>Suppose we want to create a new variable which is the 4-digit postcode (the first 4 digits in the address’s postcode).</p>
<p>For a single postcode, we could apply the following function to get it:</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_four_digits(x):</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x[:<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s try it on the first postcode in the data (<code>'1091 CR'</code>):</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>get_four_digits(df[<span class="st">'postcode'</span>][<span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>'1091'</code></pre>
</div>
</div>
<p>To apply this to all values in the data, we can use the <code>apply</code> method on the variable, and assign the output to a new variable:</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'four_digit_postcode'</span>] <span class="op">=</span> df[<span class="st">'postcode'</span>].<span class="bu">apply</span>(get_four_digits)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">address</th>
<th data-quarto-table-cell-role="th">postcode</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">area</th>
<th data-quarto-table-cell-role="th">num_rooms</th>
<th data-quarto-table-cell-role="th">lon</th>
<th data-quarto-table-cell-role="th">lat</th>
<th data-quarto-table-cell-role="th">price_per_sqm</th>
<th data-quarto-table-cell-role="th">four_digit_postcode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Blasiusstraat 8 2, Amsterdam</td>
<td>1091 CR</td>
<td>685000.0</td>
<td>64</td>
<td>3</td>
<td>4.907736</td>
<td>52.356157</td>
<td>10703.125000</td>
<td>1091</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Kromme Leimuidenstraat 13 H, Amsterdam</td>
<td>1059 EL</td>
<td>475000.0</td>
<td>60</td>
<td>3</td>
<td>4.850476</td>
<td>52.348586</td>
<td>7916.666667</td>
<td>1059</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Zaaiersweg 11 A, Amsterdam</td>
<td>1097 SM</td>
<td>850000.0</td>
<td>109</td>
<td>4</td>
<td>4.944774</td>
<td>52.343782</td>
<td>7798.165138</td>
<td>1097</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Tenerifestraat 40, Amsterdam</td>
<td>1060 TH</td>
<td>580000.0</td>
<td>128</td>
<td>6</td>
<td>4.789928</td>
<td>52.343712</td>
<td>4531.250000</td>
<td>1060</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Winterjanpad 21, Amsterdam</td>
<td>1036 KN</td>
<td>720000.0</td>
<td>138</td>
<td>5</td>
<td>4.902503</td>
<td>52.410538</td>
<td>5217.391304</td>
<td>1036</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">919</td>
<td>Ringdijk, Amsterdam</td>
<td>1097 AE</td>
<td>750000.0</td>
<td>117</td>
<td>1</td>
<td>4.927757</td>
<td>52.354173</td>
<td>6410.256410</td>
<td>1097</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">920</td>
<td>Kleine Beerstraat 31, Amsterdam</td>
<td>1033 CP</td>
<td>350000.0</td>
<td>72</td>
<td>3</td>
<td>4.890612</td>
<td>52.414587</td>
<td>4861.111111</td>
<td>1033</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">921</td>
<td>Stuyvesantstraat 33 II, Amsterdam</td>
<td>1058 AK</td>
<td>350000.0</td>
<td>51</td>
<td>3</td>
<td>4.856935</td>
<td>52.363256</td>
<td>6862.745098</td>
<td>1058</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">922</td>
<td>John Blankensteinstraat 51, Amsterdam</td>
<td>1095 MB</td>
<td>599000.0</td>
<td>113</td>
<td>4</td>
<td>4.965731</td>
<td>52.375268</td>
<td>5300.884956</td>
<td>1095</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">923</td>
<td>S. F. van Ossstraat 334, Amsterdam</td>
<td>1068 JS</td>
<td>300000.0</td>
<td>79</td>
<td>4</td>
<td>4.810678</td>
<td>52.355493</td>
<td>3797.468354</td>
<td>1068</td>
</tr>
</tbody>
</table>

<p>920 rows × 9 columns</p>
</div>
</div>
</div>
<p>You can also define and apply simple functions in one go using what are called <em>lambda</em> functions. These are small anonymous functions that are only used once. We can actually achieve what we did before with a single line using this approach:</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'four_digit_postcode'</span>] <span class="op">=</span> df[<span class="st">'postcode'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x[:<span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exporting-data" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="exporting-data"><span class="header-section-number">8.8</span> Exporting Data</h2>
<p>After doing some data cleaning and creating some new variables, we might want to export the data to a file. For example, perhaps we want to analyze the cleaned data in other software, or we want to share it with someone. We can export it using the <code>to_csv()</code> method, providing the filename we want to use. You should not use the same filename as the raw data, because then the your script will likely not work again and if you want to make any changes you will have to download the raw data again, which may not be easy to do. So let’s call it the same name but with <code>-cleaned</code> at the end so we know this is the cleaned version. We do it with:</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>df.to_csv(<span class="st">"HousingPrices-Amsterdam-August-2021-cleaned.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here <code>index=False</code> is to tell Python not to include an extra column with the row indices, which go from 0 to 923. In most cases this column is useless and just makes your files bigger.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./numpy.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to NumPy</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./data-visualization.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to Data Visualization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>