<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics 2 for IBA - 25&nbsp; Qualitative Variables with Multiple Levels</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<link href="./heteroskedasticity.html" rel="next">
<link href="./dummy-variables.html" rel="prev">
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./qualitative-variables.html"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Qualitative Variables with Multiple Levels</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics 2 for IBA</a> 
        <div class="sidebar-tools-main">
    <a href="./Statistics-2-for-IBA.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">About</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scatter-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Visualizing the Relationship between Two Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./covariance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Covariance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spurious-relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Spurious Relationships</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Simple Linear Regression Model (SLR)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">SLR Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">SLR Model Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr-confint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">SLR Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">SLR Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr-statistical-significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">SLR Statistical Significance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr-r-squared.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">SLR Quantifying Model Usefulness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr-prediction-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">SLR Prediction Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlr-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">The Multiple Linear Regression Model (MLR)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlr-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">MLR Model Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlr-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">MLR Inference on a Single Variable</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlr-r-squared.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">MLR Quantifying Model Usefulness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlr-prediction-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">MLR Prediction Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./f-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title"><span class="math inline">F</span>-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partial-f-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Partial <span class="math inline">F</span>-Test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./collinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Collinearity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./higher-order-terms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Higher-Order Terms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interaction-terms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Interaction Terms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dummy-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Dummy Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./qualitative-variables.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Qualitative Variables with Multiple Levels</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./heteroskedasticity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Testing and Correcting for Heteroskedasticity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./serial-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Testing and Correcting for Serial Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./zero-conditional-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">The Zero Conditional Mean Assumption</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">25.1</span> Introduction</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory"><span class="header-section-number">25.2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#the-incorrect-approach" id="toc-the-incorrect-approach" class="nav-link" data-scroll-target="#the-incorrect-approach"><span class="header-section-number">25.2.1</span> The Incorrect Approach</a></li>
  </ul></li>
  <li><a href="#the-correct-approach" id="toc-the-correct-approach" class="nav-link" data-scroll-target="#the-correct-approach"><span class="header-section-number">25.3</span> The Correct Approach</a></li>
  <li><a href="#qualitative-variables-in-r" id="toc-qualitative-variables-in-r" class="nav-link" data-scroll-target="#qualitative-variables-in-r"><span class="header-section-number">25.4</span> Qualitative Variables in R</a></li>
  <li><a href="#specifying-the-base-level" id="toc-specifying-the-base-level" class="nav-link" data-scroll-target="#specifying-the-base-level"><span class="header-section-number">25.5</span> Specifying the Base Level</a></li>
  <li><a href="#interaction-terms-with-dummy-variables" id="toc-interaction-terms-with-dummy-variables" class="nav-link" data-scroll-target="#interaction-terms-with-dummy-variables"><span class="header-section-number">25.6</span> Interaction Terms with Dummy Variables</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-qualitative-variables" class="quarto-section-identifier"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Qualitative Variables with Multiple Levels</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="introduction" class="level2" data-number="25.1">
<h2 data-number="25.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">25.1</span> Introduction</h2>
<p>In <a href="dummy-variables.html"><span>Chapter&nbsp;24</span></a> we learned how to use qualitative variables with two values - such as gender - in a regression model. By including a dummy variable for one of the gender values, we were able to cover all the possible values that the gender could take: <span class="math inline">=1</span> for females and <span class="math inline">=0</span> for males.</p>
<p>But often we have data with qualitative variables that can take on more than two values. For example we could have variables like:</p>
<ul>
<li>Educational attainment: High school, Bachelor, Master, PhD.</li>
<li>Industry: Primary sector (e.g.~agriculture), Manufacturing, Services.</li>
<li>Region: US States, Provinces of the Netherlands.</li>
</ul>
<p>What we will learn in this chapter is how to include this kind of information in a linear regression model.</p>
</section>
<section id="theory" class="level2" data-number="25.2">
<h2 data-number="25.2" class="anchored" data-anchor-id="theory"><span class="header-section-number">25.2</span> Theory</h2>
<p>Suppose we are interested in the impact of industry sector on wages. We have a sample of wages <span class="math inline">Y_i</span> for <span class="math inline">n</span> individuals and what sector they work in (<span class="math inline">sector_i</span>): primary, manufacturing or services.</p>
<section id="the-incorrect-approach" class="level3" data-number="25.2.1">
<h3 data-number="25.2.1" class="anchored" data-anchor-id="the-incorrect-approach"><span class="header-section-number">25.2.1</span> The Incorrect Approach</h3>
<p>Suppose for the moment we decided to follow the logic in <a href="dummy-variables.html"><span>Chapter&nbsp;24</span></a> and created a numeric variable <span class="math inline">x_{i1}</span> with the sector information as follows:</p>
<ul>
<li><span class="math inline">=0</span> if <span class="math inline">sector_i=\texttt{primary}</span>.</li>
<li><span class="math inline">=1</span> if <span class="math inline">sector_i=\texttt{manufacturing}</span>.</li>
<li><span class="math inline">=2</span> if <span class="math inline">sector_i=\texttt{services}</span>.</li>
</ul>
<p>Suppose also we used this variable to estimate the regression model: <span class="math display">
\mathbb{E}[Y_i | x_{i1}] = \beta_0 + \beta_1 x_{i1}
</span> We will see now that this approach is incorrect.</p>
<p>For individuals in the primary sector we have: <span class="math display">
\mathbb{E}[Y_i | x_{i1}=0] = \beta_0
</span> Therefore <span class="math inline">\beta_0</span> is the average wage of people in the primary sector.</p>
<p>For individuals in the manufacturing sector we have: <span class="math display">
\mathbb{E}[Y_i | x_{i1}=1] = \beta_0 + \beta_1
</span> This means that <span class="math inline">\beta_1</span> is the average difference in wages between people in the manufacturing sector and the primary sector.</p>
<p>But then for individuals in the services sector we have: <span class="math display">
\mathbb{E}[Y_i | x_{i1}=2] = \beta_0 + 2\beta_1
</span> This means that <span class="math inline">\beta_1</span> is also the average difference in wages between people in the services sector and the manufacturing sector! It also means that the difference in wages between services and the primary sector is <span class="math inline">2\beta_1</span>.</p>
<p>Using a variable like this means that going from one sector to the next leads to an increase in wage of <span class="math inline">\beta_1</span> on average for all sectors. But there is no reason to think that going from primary to manufacturing <em>and</em> manufacturing to services will lead to the <em>same</em> average increase in wage. This is a very restrictive way to use this variable. We want a more flexible way to use the information about the sector in the model.</p>
</section>
</section>
<section id="the-correct-approach" class="level2" data-number="25.3">
<h2 data-number="25.3" class="anchored" data-anchor-id="the-correct-approach"><span class="header-section-number">25.3</span> The Correct Approach</h2>
<p>Instead of creating <em>one</em> numeric variable with the information from the qualitative variable what we should do is create a dummy variable <em>for each value</em> of the categorical variable. For the sector example we create 3 variables:</p>
<ol type="1">
<li><span class="math inline">D_{i1}=1</span> if primary sector and <span class="math inline">x_{i1}=0</span> otherwise.</li>
<li><span class="math inline">D_{i2}=1</span> if manufacturing sector and <span class="math inline">x_{i2}=0</span> otherwise.</li>
<li><span class="math inline">D_{i3}=1</span> if services sector and <span class="math inline">x_{i3}=0</span> otherwise.</li>
</ol>
<p>We then estimate a regression model using these dummy variables. We cannot include all 3 dummy variables because otherwise we run into the dummy variable trap we encountered in <a href="dummy-variables.html"><span>Chapter&nbsp;24</span></a>. This is because <span class="math inline">D_{i1}=1-D_{i2}-D_{i3}</span> always:</p>
<ul>
<li>If <span class="math inline">D_{i1}=0</span> then one of <span class="math inline">D_{i2}</span> or <span class="math inline">D_{i3}</span> equals 1.</li>
<li>If <span class="math inline">D_{i1}=1</span> then <span class="math inline">D_{i2}=D_{i3}=0</span>.</li>
</ul>
<p>We need to choose one category to be the <em>base category</em>. Let’s let this be the primary sector. The model we would estimate is then:</p>
<p><span class="math display">
\mathbb{E}[Y_i|sector_i]=\beta_0+\beta_1 D_{i2} + \beta_2 D_{i3}
</span> For the primary sector we have: <span class="math display">
\mathbb{E}[Y_i|sector_i=\texttt{primary}]=\beta_0
</span> For the manufacturing sector we have: <span class="math display">
\mathbb{E}[Y_i|sector_i=\texttt{manufacturing}]=\beta_0+\beta_1
</span> For the services sector we have: <span class="math display">
\mathbb{E}[Y_i|sector_i=\texttt{services}]=\beta_0+\beta_2
</span> So:</p>
<ul>
<li><span class="math inline">\beta_1</span> is the average difference between the manufacturing and primary sectors.</li>
<li><span class="math inline">\beta_2</span> is the average difference between the services and primary sectors.</li>
<li><span class="math inline">\beta_2-\beta_1</span> is the average difference between the services and manufacturing sectors.</li>
</ul>
<p>Now the model is much more flexible.</p>
</section>
<section id="qualitative-variables-in-r" class="level2" data-number="25.4">
<h2 data-number="25.4" class="anchored" data-anchor-id="qualitative-variables-in-r"><span class="header-section-number">25.4</span> Qualitative Variables in R</h2>
<p>To show how to do this in R we will use a dataset on the average house prices <span class="math inline">Y_i</span> by municipality (<em>gemeente</em>) in the Netherlands in 2022 and the province each municipality is in, <span class="math inline">prov_i</span>. We will use this dataset to see how much location (province) impacts house prices.</p>
<p>To do this we create 12 dummy variables, one for each province:</p>
<ul>
<li><span class="math inline">D_{i1}=1</span> if <span class="math inline">prov_i=\texttt{Drenthe}</span> and zero otherwise.</li>
<li><span class="math inline">D_{i2}=1</span> if <span class="math inline">prov_i=\texttt{Flevoland}</span> and zero otherwise.</li>
<li><span class="math inline">\vdots</span></li>
<li><span class="math inline">D_{i12}=1</span> if <span class="math inline">prov_i=\texttt{Zuid-Holland}</span> and zero otherwise.</li>
</ul>
<p>Because <span class="math inline">D_{i1}=1-D_{i2}-D_{i3}-\dots-D_{i12}</span> for all <span class="math inline">i</span>, we need to exclude one province to avoid the dummy variable trap. Let’s choose Drenthe (<span class="math inline">D_{i1}</span>) to be the base level.</p>
<p>The model is then: <span class="math display">
        \mathbb{E}\left[ Y_i|prov_i \right]=
        \beta_0 + \beta_1 D_{i2} + \beta_2 D_{i3} +\dots+ \beta_{11} D_{i12}
</span> To get the data ready we merge the following two datasets by municipality:</p>
<ul>
<li><a href="https://walshc.github.io/stats2/cpb-house-prices.csv">cpb-house-prices.csv</a></li>
<li><a href="https://walshc.github.io/stats2/municipality-province.csv">municipality-province.csv</a></li>
</ul>
<p>We need to be careful that the house prices data uses <code>;</code> for separators and commas for decimal points:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"cpb-house-prices.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>, <span class="at">dec =</span> <span class="st">","</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"municipality"</span>, <span class="st">"house_price_2022"</span>, <span class="st">"house_price_2021"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"municipality-province.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df2) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"municipality"</span>, <span class="st">"province"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">merge</span>(df1, df2, <span class="at">by =</span> <span class="st">"municipality"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, what we could do is spend a lot of time creating 11 dummy variables, one for each province, and then typing all 11 into the formula in the <code>lm()</code> function. The good news is that there is no need to do this with R. If we provide a character vector into the <code>lm()</code> function, R will interpret it as a factor variable (a qualitative variable), and automatically create these dummies. R will also choose one level to be the base level automatically. Unless the variable is already a factor R will always choose the first value alphabetically (here Drenthe) to be the base level.</p>
<p>So estimating this model is as simple as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(house_price_2022 <span class="sc">~</span> province, <span class="at">data =</span> df)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = house_price_2022 ~ province, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-270.55  -51.18   -8.15   33.68  577.65 

Coefficients:
                      Estimate Std. Error t value    Pr(&gt;|t|)    
(Intercept)            381.308     27.768  13.732     &lt; 2e-16 ***
provinceFlevoland        7.242     48.095   0.151      0.8804    
provinceFryslân        -10.419     35.848  -0.291      0.7715    
provinceGelderland      53.907     30.862   1.747      0.0816 .  
provinceGroningen      -84.728     41.186  -2.057      0.0405 *  
provinceLimburg        -38.889     32.704  -1.189      0.2352    
provinceNoord-Brabant   61.476     30.599   2.009      0.0453 *  
provinceNoord-Holland  159.944     31.326   5.106 0.000000559 ***
provinceOverijssel      -4.944     33.781  -0.146      0.8837    
provinceUtrecht        137.172     33.570   4.086 0.000055142 ***
provinceZeeland        -43.208     38.507  -1.122      0.2626    
provinceZuid-Holland    62.294     30.982   2.011      0.0452 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 96.19 on 329 degrees of freedom
Multiple R-squared:  0.3251,    Adjusted R-squared:  0.3026 
F-statistic: 14.41 on 11 and 329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Let’s interpret these estimates. We first note that: <span class="math display">
      \begin{split}
        \mathbb{E}\left[ Y_i|prov_i=\texttt{Drenthe} \right]=&amp;
        \beta_0+\beta_1 \times 0 +\beta_2 \times 0+ \dots + \beta_{10}\times 0+\beta_{11} \times 0 = \beta_0\\
      \mathbb{E}\left[ Y_i|prov_i=\texttt{Flevoland} \right]=&amp;
        \beta_0+\beta_1 \times 1 + \beta_2 \times 0+\dots + \beta_{10}\times 0+\beta_{11} \times 0 = \beta_0+\beta_1\\
        &amp;\vdots \\
        \mathbb{E}\left[ Y_i|prov_i=\texttt{Zuid-Holland} \right]=&amp;
        \beta_0+\beta_1 \times 0 + \beta_2 \times 0+\dots + \beta_{10}\times 0+\beta_{11} \times 1 = \beta_0+\beta_{11} \\
      \end{split}
</span> So our estimate of <span class="math inline">\beta_0</span> is the average house price in Drenthe in our sample. Because house prices are in thousands of euros, the average house price in Drenthe in our sample is €381,308.33. Our estimate of <span class="math inline">\beta_0+\beta_1</span> is the average house price in Flevoland in our sample. This is €381,308.33+€7,241.67=€388,550.00. Our estimate of <span class="math inline">\beta_1</span> is therefore the difference in average house price between Flevoland and Drenthe in our sample.</p>
<p>We will now do some example questions with this output.</p>
<p>One example is: “are there any differences in average house prices across provinces (at the 5% level)?”</p>
<p>To do this, let <span class="math inline">\mu_j</span> be the population average house price in province <span class="math inline">j=1,2,\dots,12</span>. This question is essentially asking to test: <span class="math display">
\begin{split}
          H_0: &amp; \mu_1=\mu_2=\dots=\mu_{12}\\
          H_1: &amp; \text{ at least one } \mu_j\neq\mu_k \text{ for } j,k=1,\dots,12\\
        \end{split}
</span> Using our model with 11 dummy variables (with Drenthe as the base category), this is the same as: <span class="math display">
            \begin{split}
              H_0 &amp;: \beta_1=\beta_2=\dots=\beta_{11}=0 \\
              H_1&amp;: \text{ at least one } \beta_j\neq 0 \text{ for } j=1,2,\dots,11
            \end{split}
</span> This is just an <span class="math inline">F</span>-test for testing the model’s usefulness!</p>
<p>Let’s do the <span class="math inline">F</span>-test as a recap. Under <span class="math inline">H_0</span>, <span class="math inline">F\sim F_{k,n-k-1}</span>. We can get the value of the test statistic from the model summary:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)<span class="sc">$</span>fstat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    value     numdf     dendf 
 14.40891  11.00000 329.00000 </code></pre>
</div>
</div>
<p>The critical value can be found with (using <code>numdf</code> and <code>dendf</code> from above to get the numerator and denominator degrees of freedom):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">11</span>, <span class="dv">329</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.817809</code></pre>
</div>
</div>
<p>Because the test statistic (14.409) is larger than the critical value (1.818) we reject the null hypothesis. There is sufficient evidence to suggest that the average house prices are different across provinces.</p>
<p>We can also use the <span class="math inline">p</span>-value approach. The <span class="math inline">p</span>-value for the <span class="math inline">F</span>-test is already shown in the summary output, but we could also obtain it manually using:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>f_stat <span class="ot">&lt;-</span> <span class="fu">summary</span>(m)<span class="sc">$</span>fstat[<span class="dv">1</span>]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>(p_val <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(f_stat, <span class="dv">11</span>, <span class="dv">329</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>value 
    0 </code></pre>
</div>
</div>
<p>The <span class="math inline">p</span>-value (0) is smaller than the significance level (0.05), so we also reject <span class="math inline">H_0</span> with this approach.</p>
</section>
<section id="specifying-the-base-level" class="level2" data-number="25.5">
<h2 data-number="25.5" class="anchored" data-anchor-id="specifying-the-base-level"><span class="header-section-number">25.5</span> Specifying the Base Level</h2>
<p>The coefficient estimates <span class="math inline">b_1</span>, , <span class="math inline">b_{11}</span> are always interpreted as the differences with respect to the base level. Because of this, we may want to specify the base level to help us interpret the results. By default, R chooses Drenthe as the base level. But we may want to use Noord-Brabant or another province as the base level. How can we do this?</p>
<p>To do this we first convert the variable to a <code>factor</code> and then “relevel” the factor variable using the <code>relevel()</code> function specifying the base level. Let’s do this making Noord-Brabant the base level:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>province <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>province)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>province <span class="ot">&lt;-</span> <span class="fu">relevel</span>(df<span class="sc">$</span>province, <span class="at">ref =</span> <span class="st">"Noord-Brabant"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(house_price_2022 <span class="sc">~</span> province, <span class="at">data =</span> df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = house_price_2022 ~ province, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-270.55  -51.18   -8.15   33.68  577.65 

Coefficients:
                       Estimate Std. Error t value    Pr(&gt;|t|)    
(Intercept)            442.7839    12.8540  34.447     &lt; 2e-16 ***
provinceDrenthe        -61.4756    30.5986  -2.009    0.045343 *  
provinceFlevoland      -54.2339    41.3198  -1.313    0.190252    
provinceFryslân        -71.8950    26.0626  -2.759    0.006130 ** 
provinceGelderland      -7.5682    18.6185  -0.406    0.684647    
provinceGroningen     -146.2039    33.0225  -4.427 0.000012994 ***
provinceLimburg       -100.3646    21.5336  -4.661 0.000004582 ***
provinceNoord-Holland   98.4683    19.3781   5.081 0.000000629 ***
provinceOverijssel     -66.4199    23.1372  -2.871    0.004361 ** 
provinceUtrecht         75.6968    22.8275   3.316    0.001015 ** 
provinceZeeland       -104.6839    29.6136  -3.535    0.000466 ***
provinceZuid-Holland     0.8181    18.8163   0.043    0.965346    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 96.19 on 329 degrees of freedom
Multiple R-squared:  0.3251,    Adjusted R-squared:  0.3026 
F-statistic: 14.41 on 11 and 329 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Now the intercept is the average house price in Noord-Brabant and all the coefficient estimates are differences between Noord-Brabant. For example, houses in Drenthe are on average €61,475.6 cheaper than Noord-Brabant while houses in Noord-Holland are on average €98,468.3 more expensive.</p>
</section>
<section id="interaction-terms-with-dummy-variables" class="level2" data-number="25.6">
<h2 data-number="25.6" class="anchored" data-anchor-id="interaction-terms-with-dummy-variables"><span class="header-section-number">25.6</span> Interaction Terms with Dummy Variables</h2>
<p>We can also combine dummy variables with interaction terms. Consider the following model with the <a href="https://walshc.github.io/stats2/wages2.csv">wages2.csv</a> data, where <span class="math inline">Y_i</span> is the hourly wage: <span class="math display">
\mathbb{E}\left[ Y_i|educ_i,female_i,married_i \right]=
        \beta_0+
        \beta_1 educ_i+
        \beta_2 female_i+
        \beta_3 married_i+
        \beta_4 female_i\times married_i
</span> Holding <span class="math inline">educ_i</span> fixed, there are 4 possible combinations for the female and married dummies: <span class="math display">
      \begin{split}
        \text{Unmarried men:\qquad}
        \mathbb{E}\left[ Y_i|educ_i,female_i=0,married_i=0 \right]&amp;=
        \beta_0+
        \beta_1 educ_i \\
        \text{Unmarried women:\qquad}
        \mathbb{E}\left[ Y_i|educ_i,female_i=1,married_i=0 \right]&amp;=
        \beta_0+
        \beta_1 educ_i+\beta_2\\
        \text{Married men:\qquad}
        \mathbb{E}\left[ Y_i|educ_i,female_i=0,married_i=1 \right]&amp;=
        \beta_0+
        \beta_1 educ_i+\beta_3\\
        \text{Married women:\qquad}
        \mathbb{E}\left[ Y_i|educ_i,female_i=1,married_i=1 \right]&amp;=
        \beta_0+
        \beta_1 educ_i+\beta_2+\beta_3+\beta_4\\
      \end{split}
</span> Holding education fixed:</p>
<ul>
<li><span class="math inline">\beta_2</span> is the average difference in wage between unmarried women and unmarried men.</li>
<li><span class="math inline">\beta_3</span> is the average difference in wage between married men and unmarried men.</li>
<li><span class="math inline">\beta_2+\beta_4</span> is the average difference in wage between married women and married men.</li>
<li><span class="math inline">\beta_3+\beta_4</span> is the average difference in wage between married women and unmarried women.</li>
</ul>
<p>So:</p>
<ul>
<li><span class="math inline">\beta_2</span> is the wage gap for unmarried women.</li>
<li><span class="math inline">\beta_2+\beta_4</span> is the wage gap for married women.</li>
<li><span class="math inline">\beta_4</span> can therefore be interpreted as the difference in wage gap between married and unmarried women.</li>
</ul>
<p>Let’s estimate it in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"wages2.csv"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> educ <span class="sc">+</span> female <span class="sc">*</span> married, <span class="at">data =</span> df)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ educ + female * married, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.5907 -1.6293 -0.7337  1.1014 14.6606 

Coefficients:
               Estimate Std. Error t value        Pr(&gt;|t|)    
(Intercept)    -1.02442    0.69311  -1.478           0.140    
educ            0.49356    0.04856  10.164         &lt; 2e-16 ***
female         -0.36896    0.43341  -0.851           0.395    
married         2.64107    0.39936   6.613 0.0000000000933 ***
female:married -2.82883    0.55556  -5.092 0.0000004962244 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.065 on 521 degrees of freedom
Multiple R-squared:  0.3165,    Adjusted R-squared:  0.3113 
F-statistic: 60.32 on 4 and 521 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We now interpret the estimates:</p>
<p>According to the model, <span class="math inline">b_0=-1.02442</span> means the expected wage for an unmarried man with zero years of education is <span class="math inline">-</span>$1.02.</p>
<p>Let’s see how many observations have <span class="math inline">educ_i=female_i=married_i=0</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df[df<span class="sc">$</span>educ <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> df<span class="sc">$</span>female <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> df<span class="sc">$</span>married <span class="sc">==</span> <span class="dv">0</span>, ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>No observations satisfy this. Therefore we should not trust this estimate.</p>
<p>Interpreting <span class="math inline">b_1</span> is done as normal. Holding gender and marital status fixed, increasing education by one year on average increases the wage by 49 cents.</p>
<p>To interpret <span class="math inline">b_2</span> we need to be careful because <code>female</code> also appears in the interaction. When the variable married equals zero, then this term drops out and we can interpret the variable as normal. So <span class="math inline">b_2</span> is the average difference in wage between unmarried women and unmarried men, holding education fixed. So holding education fixed, unmarried women on average earn 37 cents less than unmarried men. The wage gap is therefore 37 cents for married women.</p>
<p>To interpret <span class="math inline">b_3</span> we need to be careful because <code>married</code> also appears in the interaction. When the female dummy equals zero, then this term drops out and we can interpret the variable as normal. So <span class="math inline">b_3</span> is the average difference in wage between married men and unmarried men, holding education fixed. Holding education fixed, married men on average earn $2.64 more than unmarried men.</p>
<p>Finally, for <span class="math inline">b_4</span> we recall that above we showed that <span class="math inline">\beta_4</span> can be interpreted as the difference in wage gap between married and unmarried women. So holding education fixed, the gender wage gap is $2.83 larger for married women compared to unmarried women.</p>
<p>Let’s consider an example question from this output.</p>
<p>Holding education fixed, do unmarried women earn less than unmarried men (at the 5% level)? Use a <span class="math inline">p</span>-value approach.</p>
<p>This question is asking if <span class="math inline">\beta_2&lt; 0</span>, so the null and alternative hypotheses are <span class="math inline">H_0: \beta_2\geq 0</span> and <span class="math inline">H_1:\beta_2&lt;0</span>. Under <span class="math inline">H_0</span>, the test statistic <span class="math inline">T=B_2/S_{B_2}\sim t_{n-k-1}</span>. Because the hinge is zero, we can read the test statistic directly from the table: <span class="math inline">t=-0.8513</span>. However, the <span class="math inline">p</span>-value in the table is for a two-sided test. We can get the <span class="math inline">p</span>-value with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(t <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m))[<span class="st">"female"</span>, <span class="st">"t value"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.8513</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(t, m<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1974969</code></pre>
</div>
</div>
<p>The <span class="math inline">p</span>-value (0.1975) is greater than the significance level (0.05), so we do not reject the null hypothesis. There is not enough evidence to show that unmarried women earn less than unmarried men of equal education levels.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./dummy-variables.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Dummy Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./heteroskedasticity.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Testing and Correcting for Heteroskedasticity</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>