<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Instruction Exercise Week 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="instruction-exercise5_files/libs/clipboard/clipboard.min.js"></script>
<script src="instruction-exercise5_files/libs/quarto-html/quarto.js"></script>
<script src="instruction-exercise5_files/libs/quarto-html/popper.min.js"></script>
<script src="instruction-exercise5_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="instruction-exercise5_files/libs/quarto-html/anchor.min.js"></script>
<link href="instruction-exercise5_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="instruction-exercise5_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="instruction-exercise5_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="instruction-exercise5_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="instruction-exercise5_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<link rel="stylesheet" href="style.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Instruction Exercise Week 5</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>The file <a href="https://walshc.github.io/stats2/rottentomatoes.csv">rottentomatoes.csv</a> contains the Rotten Tomatoes rating of a random sample of movies with their length, year of release, and dummy variables for their genres.</p>
<ul>
<li><code>rating</code>: The movie’s <em>freshness</em> (rating) in percentage terms (between 0 and 100). A higher number is a higher rating.</li>
<li><code>length</code>: The runtime/length of the movie in minutes.</li>
<li><code>year</code>: The year of the movie’s release.</li>
<li><code>comedy</code>: A dummy variable for if the movie is regarded as a comedy or not (<span class="math inline">=1</span> if a comedy, <span class="math inline">=0</span> if not).</li>
<li><code>action</code>, <code>drama</code>, <code>documentary</code>, <code>romance</code>, <code>horror</code>, <code>thriller</code>. These are defined similarly to comedy.</li>
</ul>
<p><em>Note:</em> A movie can have several genres at once. For example, a romantic comedy would have <code>romancer</code><span class="math inline">=1</span> and <code>comedy</code><span class="math inline">=1</span> and would have a zero for all other genres. A movie can also have zero genres, or even 5 genres.</p>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<p>Use a 5% significance level for all questions.</p>
<ol type="1">
<li>Regress <code>rating</code> on <code>length</code> and the square of <code>length</code>.</li>
</ol>
<ul>
<li>Write down the sample regression equation.</li>
<li>Describe the relationship between <code>rating</code> and <code>length</code> using this model.</li>
<li>According to this model, at what length is rating maximized on average?</li>
</ul>
<ol start="2" type="1">
<li>Regress <code>rating</code> on <code>action</code>.</li>
</ol>
<ul>
<li>Based on this regression, what is the average rating of action movies in the sample?</li>
<li>Test using a <span class="math inline">p</span>-value approach if action movies on average have a more than 3 percentage-point higher rating than non-action movies.</li>
</ul>
<ol start="3" type="1">
<li>Do action movies on average have a higher rating than non-action movies of the same length? Use a critical value approach.</li>
<li>Regress <code>rating</code> on <code>comedy</code>, <code>length</code> and their interaction. For comedy movies, how much on average does the rating change when the movie is ten minutes longer?</li>
<li>Regress <code>rating</code> on <code>length</code>, <code>year</code> and all the genre dummies. Are the <code>romance</code> and <code>thriller</code> dummies jointly useful? Use a <span class="math inline">p</span>-value approach.</li>
</ol>
</section>
<section id="solutions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="solutions">Solutions</h2>
<section id="question-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-1">Question 1</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"rottentomatoes.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> length <span class="sc">+</span> <span class="fu">I</span>(length<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> df)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ length + I(length^2), data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-45.563  -9.008  -1.081   8.459  39.064 

Coefficients:
             Estimate Std. Error t value    Pr(&gt;|t|)    
(Intercept) 17.994322   5.999148   2.999     0.00277 ** 
length       0.520754   0.099740   5.221 0.000000216 ***
I(length^2) -0.001586   0.000401  -3.954 0.000082274 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.7 on 997 degrees of freedom
Multiple R-squared:  0.061, Adjusted R-squared:  0.05912 
F-statistic: 32.39 on 2 and 997 DF,  p-value: 0.00000000000002361</code></pre>
</div>
</div>
<p>The sample regression equation is:</p>
<p><span class="math display">
\widehat{rating}_i=17.994322 + 0.520754 length_i - 0.001586 length_i^2
</span></p>
<p>Because <span class="math inline">b_1&gt;0</span> and <span class="math inline">b_2&lt;0</span> and both estimates are individually significant, the relationship between <code>rating</code> and <code>length</code> is <em>mountain-shaped</em> according to this model. The average rating initially increases with length but eventually decreases.</p>
<p>We can find the point at which the rating is maximized on average by differentiating the sample regression equation with respect to length, setting it equal to zero, and finding the length that solves this equation:</p>
<p><span class="math display">
\frac{\partial \widehat{rating}_i}{\partial length_i} = 0.520754 - 2\times 0.001586\times length_i =0
</span> Solving: <span class="math display">
length_i = \frac{0.520754}{2 \times 0.001586}=164.2
</span> We could also calculat this directly in R with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(m1)[<span class="dv">2</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>b_2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(m1)[<span class="dv">3</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span> b_1 <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> b_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  length 
164.2283 </code></pre>
</div>
</div>
</section>
<section id="question-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-2">Question 2</h3>
<p>The model is: <span class="math display">
\mathbb{E}[rating_i|action_i]= \beta_0 + \beta_1 action_i
</span> For action movies, the average rating is: <span class="math display">
\mathbb{E}[rating_i|action_i=1]= \beta_0 + \beta_1
</span> For non-action movies, the average rating is: <span class="math display">
\mathbb{E}[rating_i|action_i=0]= \beta_0
</span> So:</p>
<ul>
<li><span class="math inline">\beta_0+\beta_1</span> is the average rating of action movies</li>
<li><span class="math inline">\beta_0</span> is the average rating of non-action movies</li>
<li><span class="math inline">\beta_1</span> is the difference in rating between action and non-action movies.</li>
</ul>
<p>We then estimate the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> action, <span class="at">data =</span> df)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ action, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-43.359  -9.359  -1.359   8.641  39.641 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  53.3592     0.4526  117.90  &lt; 2e-16 ***
action        4.3794     1.0788    4.06 0.000053 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.99 on 998 degrees of freedom
Multiple R-squared:  0.01625,   Adjusted R-squared:  0.01526 
F-statistic: 16.48 on 1 and 998 DF,  p-value: 0.00005298</code></pre>
</div>
</div>
<p>To get the average rating of action movies, we need to sum <span class="math inline">b_0+b_1</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">coef</span>(m2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 57.73864</code></pre>
</div>
</div>
<p>To confirm this, we can get the average rating of action movies directly as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>rating[df<span class="sc">$</span>action <span class="sc">==</span> <span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 57.73864</code></pre>
</div>
</div>
<p>We now test if action movies on average have a more than 3 percentage-point higher rating than non-action movies. Because <span class="math inline">b_1=4.3794</span> we can see that action movies are estimated to have a 4.3794 percentage-point higher rating. The question is whether this estimate is precise enough to say that it is larger than 3 percentage points in the population (at the 5% level). The claim is thus whether <span class="math inline">\beta_1&gt;3</span> in the population. This refers to the alternative hypothesis, so the null hypothesis is the opposite of this (<span class="math inline">\beta_1\leq 3</span>). We are thus ready to perform our test.</p>
<ul>
<li>The null and alternative hypotheses are: <span class="math inline">H_0</span>: <span class="math inline">\beta_1\leq 3</span>, <span class="math inline">H_1</span>: <span class="math inline">\beta&gt;3</span>.</li>
<li>Under <span class="math inline">H_0</span>, the test statistic <span class="math inline">T=\frac{B_1-3}{S_{B_1}}\sim t_{n-k-1}</span>.</li>
<li>The value of the test statistic in our sample can be calculated with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m2))[<span class="dv">2</span>, <span class="dv">1</span>]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>s_b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m2))[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> (b_1 <span class="sc">-</span> <span class="dv">3</span>) <span class="sc">/</span> s_b_1</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.278705</code></pre>
</div>
</div>
<ul>
<li>The <span class="math inline">p</span>-value for this upper-tail test can be calculated with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pval <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(t, m2<span class="sc">$</span>df.residual)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>pval</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1006492</code></pre>
</div>
</div>
<ul>
<li>The <span class="math inline">p</span>-value of 0.1006492 is greater than the significance level, so we fail to reject the null hypothesis. There is insufficient evidence for the claim.</li>
</ul>
</section>
<section id="question-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-3">Question 3</h3>
<p>To answer this question we need to estimate a model that explains <code>ratin</code> using <code>action</code> and <code>length</code>. To see why, this model is:</p>
<p><span class="math display">
\mathbb{E}[rating_i|action_i,length_i]=\beta_0 + \beta_1 action_i + \beta_2 length_i
</span> For action movies of a particular length: <span class="math display">
\mathbb{E}[rating_i|action_i=1,length_i]=\beta_0 + \beta_1 + \beta_2 length_i
</span> For non-action movies of the same length: <span class="math display">
\mathbb{E}[rating_i|action_i=0,length_i]=\beta_0 + \beta_2 length_i
</span> Taking differences: <span class="math display">
\mathbb{E}[rating_i|action_i=1,length_i]-\mathbb{E}[rating_i|action_i=0,length_i]=\beta_1
</span> So <span class="math inline">\beta_1</span> in this model measures the difference in average rating between action movies and non-action movies of the same length. If <span class="math inline">\beta_1&gt;0</span>, then action movies on average have a higher rating than non-action movies of the same length. So the alternative hypothesis is <span class="math inline">\beta_1&gt;0</span> and the null hypothesis (the opposite of this) is <span class="math inline">\beta_1\leq 0</span>. We estimate model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> action <span class="sc">+</span> length, <span class="at">data =</span> df)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ action + length, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-44.049  -9.047  -0.926   8.445  39.558 

Coefficients:
            Estimate Std. Error t value     Pr(&gt;|t|)    
(Intercept) 40.82180    2.01964  20.212      &lt; 2e-16 ***
action       3.19059    1.07440   2.970      0.00305 ** 
length       0.12362    0.01943   6.363 0.0000000003 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.74 on 997 degrees of freedom
Multiple R-squared:  0.05464,   Adjusted R-squared:  0.05274 
F-statistic: 28.81 on 2 and 997 DF,  p-value: 0.0000000000006841</code></pre>
</div>
</div>
<p>Now we have everything to perform our test.</p>
<ul>
<li>The null and alternative hypotheses are: <span class="math inline">H_0</span>: <span class="math inline">\beta_1\leq 0</span>, <span class="math inline">H_1</span>: <span class="math inline">\beta&gt;0</span>.</li>
<li>Under <span class="math inline">H_0</span>, the test statistic <span class="math inline">T=\frac{B_1}{S_{B_1}}\sim t_{n-k-1}</span>.</li>
<li>The value of the test statistic in our sample can be seen from the summary output (<span class="math inline">t=2.970</span>). We could also extract it with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(m3))[<span class="st">"action"</span>, <span class="st">"t value"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.96966</code></pre>
</div>
</div>
<ul>
<li>The critical value is:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>, m3<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.646383</code></pre>
</div>
</div>
<ul>
<li>Because the test statistic is larger than the critical value, we reject the null hypothesis. There is sufficient evidence for the claim.</li>
</ul>
</section>
<section id="question-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-4">Question 4</h3>
<p>With an interaction, this model is:</p>
<p><span class="math display">
\mathbb{E}[rating_i | comedy_i,length_i]=
\beta_0 + \beta_1 comedy_i+ \beta_2 length_i + \beta_3 comedy_i length_i
</span> For comedy movies, the model becomes: <span class="math display">
\mathbb{E}[rating_i | comedy_i=1,length_i]=
\beta_0 + \beta_1 + (\beta_2 +\beta_3) length_i
</span> Increasing the length by 10 minutes: <span class="math display">
\mathbb{E}[rating_i | comedy_i=1,length_i+10]=
\beta_0 + \beta_1 + (\beta_2 +\beta_3) \left(length_i+ 10\right)
</span> Taking differences: <span class="math display">
\mathbb{E}[rating_i | comedy_i=1,length_i+10]-
\mathbb{E}[rating_i | comedy_i=1,length_i]= (\beta_2 + \beta_3)\times 10
</span> So to answer this we need to find <span class="math inline">10\times(b_2 + b_3)</span> using the estimated <span class="math inline">b_2</span> and <span class="math inline">b_3</span>. We estimate the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> comedy <span class="sc">*</span> length, <span class="at">data =</span> df)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ comedy * length, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-44.882  -9.392  -1.071   8.460  39.796 

Coefficients:
              Estimate Std. Error t value          Pr(&gt;|t|)    
(Intercept)   35.89728    2.46084  14.587           &lt; 2e-16 ***
comedy        13.38080    4.28494   3.123           0.00184 ** 
length         0.17347    0.02327   7.456 0.000000000000194 ***
comedy:length -0.12110    0.04091  -2.960           0.00315 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.74 on 996 degrees of freedom
Multiple R-squared:  0.05577,   Adjusted R-squared:  0.05293 
F-statistic: 19.61 on 3 and 996 DF,  p-value: 0.000000000002346</code></pre>
</div>
</div>
<p>We calculate <span class="math inline">10\times(b_2 + b_3)</span> with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span> <span class="sc">*</span> (<span class="fu">coef</span>(m4)[<span class="dv">3</span>] <span class="sc">+</span> <span class="fu">coef</span>(m4)[<span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   length 
0.5237664 </code></pre>
</div>
</div>
<p>The rating of comedy movies on average goes up by 0.5238 when they are 10 minutes longer.</p>
</section>
<section id="question-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-5">Question 5</h3>
<p>This model involves regressing <code>rating</code> on <em>every other variable</em> in the dataset. Because we did not create any new variables, we can do the following trick to estimate the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> ., <span class="at">data =</span> df)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ ., data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-42.626  -8.462  -0.780   8.116  39.638 

Coefficients:
             Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept) 336.36156  148.03220   2.272      0.023287 *  
length        0.11581    0.01994   5.809 0.00000000848 ***
year         -0.14856    0.07342  -2.023      0.043294 *  
comedy        3.19065    0.98482   3.240      0.001236 ** 
action        4.17174    1.13514   3.675      0.000251 ***
drama         3.48755    0.92936   3.753      0.000185 ***
documentary   4.76121    1.51256   3.148      0.001694 ** 
romance       1.24938    1.10940   1.126      0.260363    
horror        3.71544    1.50504   2.469      0.013730 *  
thriller      1.97002    1.10667   1.780      0.075362 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.6 on 990 degrees of freedom
Multiple R-squared:  0.08259,   Adjusted R-squared:  0.07425 
F-statistic: 9.903 on 9 and 990 DF,  p-value: 0.00000000000001214</code></pre>
</div>
</div>
<p>The <code>.</code> here means <em>every other variable</em>. Alternatively you could have done: <code>lm(rating ~ length + year + comedy + action + drama + documentary + romance + horror + thriller, data = df)</code> but that involves much more typing.</p>
<p>To check if the <code>romance</code> and <code>thriller</code> dummies are jointly useful we do a partial <span class="math inline">F</span> test.</p>
<ul>
<li><span class="math inline">H_0:</span> <span class="math inline">\beta_7=\beta_9=0</span> and <span class="math inline">H_1</span>: at least one of <span class="math inline">\beta_7\neq 0</span> or <span class="math inline">\beta_9\neq 0</span>.</li>
<li>Under <span class="math inline">H_0</span>, the test statistic: <span class="math display">
F = \frac{(SSE_r-SSE_c)/(k-g)}{SSE_c/(n-k-1)}
</span> follows an <span class="math inline">F</span> distribution with <span class="math inline">k-g</span> numerator and <span class="math inline">n-k-1</span> denominator degrees of freedom.</li>
<li>We can calculate the value of the test statistic as follows. We would normally estimate a reduced model that excludes <code>romance</code> and <code>thriller</code>. We could do this with: <code>lm(rating ~ length + year + comedy + action + drama + documentary + horror, data = df)</code> But this involves a lot of typing. So we will show a trick that also uses the <code>.</code> we used above. If we write <code>rating ~ . - romance - thriller</code> in the formula, it will regress <code>rating</code> on <em>all other variables except</em> <code>romance</code> and <code>thriller</code>. Let’s try it out:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>m5_r <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> . <span class="sc">-</span> romance <span class="sc">-</span> thriller, <span class="at">data =</span> df)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5_r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ . - romance - thriller, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-42.837  -8.724  -0.854   8.019  39.595 

Coefficients:
             Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept) 340.15408  147.97533   2.299      0.021728 *  
length        0.11928    0.01984   6.011 0.00000000258 ***
year         -0.15022    0.07339  -2.047      0.040930 *  
comedy        2.75911    0.92926   2.969      0.003058 ** 
action        4.37997    1.11551   3.926 0.00009216922 ***
drama         3.50266    0.92277   3.796      0.000156 ***
documentary   4.02754    1.46825   2.743      0.006196 ** 
horror        4.31040    1.45061   2.971      0.003036 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.61 on 992 degrees of freedom
Multiple R-squared:  0.07888,   Adjusted R-squared:  0.07238 
F-statistic: 12.14 on 7 and 992 DF,  p-value: 6.163e-15</code></pre>
</div>
</div>
<ul>
<li>We can then use the <code>anova()</code> function to get the partial <span class="math inline">F</span> test statistic and <span class="math inline">p</span>-value as normal:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m5_r, m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: rating ~ (length + year + comedy + action + drama + documentary + 
    romance + horror + thriller) - romance - thriller
Model 2: rating ~ length + year + comedy + action + drama + documentary + 
    romance + horror + thriller
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    992 157706                           
2    990 157070  2    635.87 2.0039 0.1354</code></pre>
</div>
</div>
<p>The value of the test statistic is 2.0039 and the <span class="math inline">p</span>-value is 0.1354.</p>
<ul>
<li>Because the <span class="math inline">p</span>-value is greater than the significance level of 0.05, we fail to reject the null hypothesis. The variables <code>romance</code> and <code>thriller</code> are not jointly useful at the 5% level.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>