<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial Exercises Week 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="tutorial5_files/libs/clipboard/clipboard.min.js"></script>
<script src="tutorial5_files/libs/quarto-html/quarto.js"></script>
<script src="tutorial5_files/libs/quarto-html/popper.min.js"></script>
<script src="tutorial5_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="tutorial5_files/libs/quarto-html/anchor.min.js"></script>
<link href="tutorial5_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="tutorial5_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="tutorial5_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="tutorial5_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="tutorial5_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<link rel="stylesheet" href="style.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="tutorial5.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tutorial Exercises Week 5</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="question-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-1">Question 1</h2>
<p>The S&amp;P 500 is a stock market index that tracks the stock market performance of the 500 biggest publicly-listed companies in the US. The file <a href="https://walshc.github.io/pqs-tutorials/SP500.csv">SP500.csv</a> contains the value of this index for each day from 2015 until 2023.</p>
<p>With <code>ggplot</code>, if you want to plot a variable <code>x</code> over time <code>t</code> from the dataframe <code>df</code>, you can use the command: <code>ggplot(df, aes(t, x)) + geom_line()</code>.</p>
<p>Use this approach to plot the closing price (variable <code>close</code>) over time.</p>
<p>Based on your plot, during which of the following periods did the index experience the largest crash?</p>
<ul>
<li>At the beginning of 2016.</li>
<li>At the end of 2018.</li>
<li>Near the beginning of 2020.</li>
<li>In the second half of 2023.</li>
</ul>
<section id="solution" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="solution">Solution</h4>
<p>We begin by reading in the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"SP500.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        date    open    high     low   close adj_close     volume
1 2023-11-08 4384.37 4391.20 4359.76 4382.78   4382.78 3729510000
2 2023-11-07 4366.21 4386.26 4355.41 4378.38   4378.38 3791230000
3 2023-11-06 4364.27 4372.21 4347.53 4365.98   4365.98 3656340000
4 2023-11-03 4334.23 4373.62 4334.23 4358.34   4358.34 4570960000
5 2023-11-02 4268.26 4319.72 4268.26 4317.78   4317.78 4669780000
6 2023-11-01 4201.27 4245.64 4197.74 4237.86   4237.86 4224900000</code></pre>
</div>
</div>
<p>The date appears to be in yyyy-mm-dd format. We can format it as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(df<span class="sc">$</span>date, <span class="at">format =</span> <span class="st">"%Y-%m-%d"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
"2015-01-02" "2017-03-21" "2019-06-07" "2019-06-06" "2021-08-23" "2023-11-08" </code></pre>
</div>
</div>
<p>We then make the line plot with <code>ggplot</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(date, close)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"S&amp;P 500 Index"</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial5_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that the largest crash happened at the start of 2020 when the corona outbreak happened. There was also a big crash at the start of 2022, but this was not one of the possible MCQ options.</p>
<p>Just so you can see it, it’s also possible to make a line plot with base R. We just use the <code>plot()</code> function with both variables and add the <code>type = "l"</code> option, where <code>"l"</code> stands for line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>date, df<span class="sc">$</span>close, <span class="at">type =</span> <span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial5_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="question-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-2">Question 2</h2>
<p>Using the S&amp;P 500 data, create a variable in your dataset which is the percentage change in the closing price from one day to the next. Call this the daily return.</p>
<p>If <span class="math inline">x_t</span> is the closing price on date <span class="math inline">t</span>, then the percentage change in the closing price from the previous day is given by the following equation:</p>
<p><span class="math display">
100\times \frac{x_t -x_{t-1}}{x_{t-1}}
</span></p>
<p>Plot the daily returns over time using <code>ggplot</code> with the <code>geom_line()</code> function.</p>
<p>Which of the following is true in the plot?</p>
<ul>
<li>Early 2020 had both the biggest positive and negative daily returns.</li>
<li>Early 2020 had the biggest positive daily returns, but not the biggest negative daily returns.</li>
<li>Early 2020 had the biggest negative daily returns, but not the biggest positive daily returns.</li>
<li>Early 2020 had neither the biggest positive daily returns, nor the biggest negative daily returns.</li>
</ul>
<section id="solution-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="solution-1">Solution</h4>
<p>To create this return variable, we first need to sort the data by date:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df[<span class="fu">order</span>(df<span class="sc">$</span>date), ]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           date    open    high     low   close adj_close     volume
2229 2015-01-02 2058.90 2072.36 2046.04 2058.20   2058.20 2708700000
2228 2015-01-05 2054.44 2054.44 2017.34 2020.58   2020.58 3799120000
2227 2015-01-06 2022.15 2030.25 1992.44 2002.61   2002.61 4460110000
2226 2015-01-07 2005.55 2029.61 2005.55 2025.90   2025.90 3805480000
2225 2015-01-08 2030.61 2064.08 2030.61 2062.14   2062.14 3934010000
2224 2015-01-09 2063.45 2064.43 2038.33 2044.81   2044.81 3364140000</code></pre>
</div>
</div>
<p>We then need to create the lagged closing price variable, <span class="math inline">x_{t-1}</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>lag_close <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, df<span class="sc">$</span>close[<span class="dv">1</span><span class="sc">:</span>(<span class="fu">nrow</span>(df)<span class="sc">-</span><span class="dv">1</span>)])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df[, <span class="fu">c</span>(<span class="st">"date"</span>, <span class="st">"close"</span>, <span class="st">"lag_close"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           date   close lag_close
2229 2015-01-02 2058.20        NA
2228 2015-01-05 2020.58   2058.20
2227 2015-01-06 2002.61   2020.58
2226 2015-01-07 2025.90   2002.61
2225 2015-01-08 2062.14   2025.90
2224 2015-01-09 2044.81   2062.14</code></pre>
</div>
</div>
<p>Because we don’t have an observation before the 2nd of January 2015 we need to use <code>NA</code> for that value. For all subsequent values we use the value from the previous period. We index the vector from 1 to <code>nrow(df) - 1</code> because for the very last row with index <code>nrow(df)</code>, we use the value with index <code>nrow(df) - 1</code> for the lag.</p>
<p>We then use this variable to create the percentage return variable according to the formula:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>return <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> (df<span class="sc">$</span>close <span class="sc">-</span> df<span class="sc">$</span>lag_close) <span class="sc">/</span> df<span class="sc">$</span>lag_close</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df[, <span class="fu">c</span>(<span class="st">"date"</span>, <span class="st">"close"</span>, <span class="st">"lag_close"</span>, <span class="st">"return"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           date   close lag_close     return
2229 2015-01-02 2058.20        NA         NA
2228 2015-01-05 2020.58   2058.20 -1.8278107
2227 2015-01-06 2002.61   2020.58 -0.8893486
2226 2015-01-07 2025.90   2002.61  1.1629823
2225 2015-01-08 2062.14   2025.90  1.7888346
2224 2015-01-09 2044.81   2062.14 -0.8403891</code></pre>
</div>
</div>
<p>The percentage return on January 5 20215 was -1.83%.</p>
<p>We then make a plot of the returns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(date, return)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"S&amp;P 500 Index Daily Return"</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values (`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="tutorial5_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that early 2020 had the largest swings in returns, where it had both the largest positive and negative daily returns.</p>
</section>
</section>
<section id="question-3" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-3">Question 3</h2>
<p>Download the dataset <a href="https://walshc.github.io/pqs-tutorials/toyota-camry-ads.csv">toyota-camry-ads.csv</a>. This contains information on classified advertisements placed on <a href="https://www.craigslist.org/about/sites">Craigslist</a> for used Toyota Camry cars, one of the most common sedan cars in the US. The variables are:</p>
<ul>
<li><code>condition</code>: what kind of condition the car is in (good, like new, etc).</li>
<li><code>odometer</code>: how many miles the car has travelled in its lifetime (the car’s “mileage”).</li>
<li><code>paint_color</code>: the car’s color.</li>
<li><code>price</code>: the asking price of the car.</li>
<li><code>year</code>: the year the car was bought new.</li>
</ul>
<p>Create a histogram of the <code>year</code> variable. Based on this histogram, choose the answer below which contains a correct statement about the data.</p>
<ul>
<li>The majority of cars in the dataset were bought after 2000.</li>
<li>The majority of cars in the dataset were bought between 2007-2009.</li>
<li>The majority of cars in the dataset were bought after 2010.</li>
<li>All cars in the dataset were bought after 1990.</li>
</ul>
<section id="solution-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="solution-2">Solution</h4>
<p>We can read in and plot the data as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"toyota-camry-ads.csv"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(year)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="tutorial5_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that most cars were bought after the year 2000. We can confirm this by checking the proportion of cars bought after 2000:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>year <span class="sc">&gt;</span> <span class="dv">2000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8953975</code></pre>
</div>
</div>
<p>About 89.5% of the cars were bought after 2000, which is a clear majority.</p>
<p>The other options are wrong for the following reasons.</p>
<ul>
<li>Only 25.4% of cars were bought in 2007-2009:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>year <span class="sc">%in%</span> <span class="dv">2007</span><span class="sc">:</span><span class="dv">2009</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2538354</code></pre>
</div>
</div>
<ul>
<li>Only 35.1% of cars were bought after 2010:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>year <span class="sc">&gt;</span> <span class="dv">2010</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3514644</code></pre>
</div>
</div>
<ul>
<li>A very small percentage (0.2%) were bought in 1990 or earlier, so it’s not true that <em>all</em> cars were bought before 1990:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>year <span class="sc">&lt;=</span> <span class="dv">1990</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00209205</code></pre>
</div>
</div>
</section>
</section>
<section id="question-4" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-4">Question 4</h2>
<p>Create a bar plot of the <code>condition</code> variable. Based on this plot, what is the most common condition for Toyota Camry cars for sale on this site to be in?</p>
<p><em>Plotting tip:</em> <code>ggplot</code> will by default order the “conditions” alphabetically. But sometimes it makes more sense for categorical variables like this to be ordered differently. We might want to order the bars from worst condition to best condition. We can do this by converting the condition variable to a factor variable and specifying the order we want:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ordered_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"salvage"</span>, <span class="st">"fair"</span>, <span class="st">"good"</span>, <span class="st">"excellent"</span>, <span class="st">"like new"</span>, <span class="st">"new"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>condition <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>condition, <span class="at">levels =</span> ordered_levels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Variables like this are called “ordinal”.</p>
<section id="solution-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="solution-3">Solution</h4>
<p>If we create a bar plot of the condition variable without ordering the levels, we get:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(condition)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial5_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this we can see that the most common condition for the cars to be in is “excellent”. But this is not a very satisfactory way of making the plot because there is a natural ordering to the condition types that isn’t alphabetical:</p>
<p><span class="math display">
salvage &lt; fair &lt; good &lt; excellent &lt; like\;new &lt; new
</span> We can use the plotting tip to re-order the levels and re-make the bar plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ordered_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"salvage"</span>, <span class="st">"fair"</span>, <span class="st">"good"</span>, <span class="st">"excellent"</span>, <span class="st">"like new"</span>, <span class="st">"new"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>condition <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>condition, <span class="at">levels =</span> ordered_levels)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(condition)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial5_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now the bars are in the right order. We still get the same answer to the question, however, that excellent is the most common condition for the cars to be in.</p>
</section>
</section>
<section id="question-5" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-5">Question 5</h2>
<p>Create a scatter plot with:</p>
<ul>
<li><code>odometer</code> on the horizontal axis.</li>
<li><code>price</code> on the vertical axis.</li>
</ul>
<p>In addition, make the colors of the points represent the values of the <code>year</code> variable.</p>
<p>Choose the answer below which best interprets this scatter plot.</p>
<p><em>Hint:</em> To make a scatter plot with <code>x</code> and <code>y</code> with colors representing <code>z</code> we do <code>ggplot(df, aes(x, y, color = z)) + geom_point()</code></p>
<ul>
<li>Higher values of odometer are usually associated with lower prices. In addition, newer cars usually sell for a higher price.</li>
<li>Higher values of odometer are usually associated with lower prices. In addition, older cars usually sell for a higher price.</li>
<li>Higher values of odometer are usually associated with higher prices. In addition, newer cars usually sell for a higher price.</li>
<li>Higher values of odometer are usually associated with higher prices. In addition, older cars usually sell for a higher price.</li>
</ul>
<section id="solution-4" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="solution-4">Solution</h4>
<p>We create the plot as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(odometer, price, <span class="at">color =</span> year)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial5_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can make the following conclusions from this:</p>
<ul>
<li>Higher values of odometer means a lower price on average.</li>
<li>Lower values of odometer means a higher price on average.</li>
<li>Darker points usually have a lower price. Darker points are cars with a lower year, which are the older cars.</li>
<li>Brighter points usually have a higher price. Brighter points are cars with a higher year, which are the newer cars.</li>
</ul>
<p>Therefore the option “Higher values of odometer are usually associated with lower prices. In addition, newer cars usually sell for a higher price” best matches what we observe.</p>
<p>We can customize the plot a bit the following way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(viridis)) <span class="fu">install.packages</span>(<span class="st">"viridis"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: viridis</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: viridisLite</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(odometer<span class="sc">/</span><span class="dv">1000</span>, price<span class="sc">/</span><span class="dv">1000</span>, <span class="at">color =</span> year)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Mileage (in 1,000s)"</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Asking Price (in $1,000)"</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis</span>(<span class="at">name =</span> <span class="st">"Year"</span>, <span class="at">option =</span> <span class="st">"C"</span>) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial5_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The line <code>if (!require(viridis)) install.packages("viridis")</code> checks if the package <code>viridis</code> is installed, and if it isn’t, it installs it. The <code>viridis</code> package is used to change the colors of the points. <em>Note:</em> you won’t be asked to use this package in the exam, but I’m just showing you how to use this package here in case you want to make colorful plots after this course.</p>
<p>The reason I divided the variables by 1,000 is to make them easier to read. We then adjust the axis labels accordingly to make this clear.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>