<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics 2 2022/23 Exam Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="2022-exam-solutions_files/libs/clipboard/clipboard.min.js"></script>
<script src="2022-exam-solutions_files/libs/quarto-html/quarto.js"></script>
<script src="2022-exam-solutions_files/libs/quarto-html/popper.min.js"></script>
<script src="2022-exam-solutions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2022-exam-solutions_files/libs/quarto-html/anchor.min.js"></script>
<link href="2022-exam-solutions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2022-exam-solutions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2022-exam-solutions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2022-exam-solutions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2022-exam-solutions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistics 2 2022/23 Exam Solutions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>The year 2022 has seen enormous fluctuations in energy prices. The price of gasoline (petrol) is one of these that has changed price a lot over the last year. To reduce the financial burden on households, the German government reduced the excise duty on unleaded petrol by 29.55 cents starting on June 1, 2022. This excise duty is the tax the government places on a liter of petrol, which went from 65.45 cents down to 35.9 cents. This excise duty reduction had a large impact on the price of petrol, which can be seen by plotting the petrol price over time:</p>
<div class="cell">
<details>
<summary>Show code generating the plot below</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"petrol.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(df<span class="sc">$</span>date)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_TIME"</span>, <span class="st">"C"</span>))  <span class="co"># make months display in English</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(date, petrol)) <span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">as.Date</span>(<span class="st">"2022-06-01"</span>), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Petrol Price (in €)"</span>) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="2022-exam-solutions_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When the excise duty fell, petrol stations were not forced to reduce the price of petrol by the full amount. You have been tasked by the government to study how much the excise tax affects the price of petrol. You are given a data set which contains the average petrol price (averaged over all petrol stations in the country in a day), the excise duty, and Brent Crude oil price for each day between April 1 and July 31. The variable names and their descriptions are:</p>
<ul>
<li><code>date</code>: The date in format yyyy-mm-dd.</li>
<li><code>petrol</code>: The average daily petrol price for E5 petrol (€ per liter) on that date.</li>
<li><code>duty</code>: The excise duty on E5 petrol (€ per liter)</li>
<li><code>oil</code>: The daily Brent Crude oil price (€ per barrel)</li>
</ul>
<section id="question-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-1">Question 1</h4>
<p>What is the sample correlation coefficient between the price of petrol and the excise duty on petrol?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"petrol.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df<span class="sc">$</span>petrol, df<span class="sc">$</span>duty)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7831513</code></pre>
</div>
</div>
<p><strong>Answer:</strong> 0.7831513</p>
</section>
<section id="question-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-2">Question 2</h4>
<p>Choose the answer below which best represents the interpretation of the correlation in the previous question, where <span class="math inline">r</span> represents your answer to the previous question.</p>
<ul>
<li>A €1 increase in the excise duty on average leads to an increase in the price of petrol by <span class="math inline">r</span> euros.</li>
<li>The excise duty data explains <span class="math inline">r</span>% of the data on petrol prices.</li>
<li>There is a strong positive linear relationship between the price of petrol and the excise duty on it.</li>
<li>The correlation depends on the units of the variables used to calculate it and is therefore difficult to interpret.</li>
</ul>
<p><strong>Answer:</strong> There is a strong positive linear relationship between the price of petrol and the excise duty on it.</p>
</section>
</section>
<section id="model-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-1">Model 1</h2>
<p>Estimate a simple linear regression model explaining the price of petrol by the excise duty.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(petrol <span class="sc">~</span> duty, <span class="at">data =</span> df)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = petrol ~ duty, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.11576 -0.05084 -0.01239  0.06339  0.13595 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.66927    0.02091   79.84   &lt;2e-16 ***
duty         0.54644    0.03961   13.80   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.06464 on 120 degrees of freedom
Multiple R-squared:  0.6133,    Adjusted R-squared:  0.6101 
F-statistic: 190.3 on 1 and 120 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="question-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-3">Question 3</h4>
<p>Your boss asks you to interpret the regression intercept. Choose the answer below which best represents how you should interpret the regression intercept for this particular dataset.</p>
<ul>
<li>An increase in the excise duty of €1 per liter would on average lead to an increase in the petrol price of €1.67 per liter.</li>
<li>If the government would set the excise duty to zero, the price of petrol would become exactly €1.67 per liter. This prediction is reliable because the intercept is individually significant at the 1% level.</li>
<li>An increase in the petrol price of €1 per liter would on average lead to an increase in the excise duty of €1.67 per liter.</li>
<li>Because we don’t observe the excise duty at or near zero, we should be cautious when interpreting the intercept. In this case its prediction is unreliable.</li>
</ul>
<p><strong>Answer:</strong> Because we don’t observe the excise duty at or near zero, we should be cautious when interpreting the intercept. In this case its prediction is unreliable.</p>
<p><em>Explanation:</em> The 1st option is wrong because that’s how we would interpret the slope if it was equal to 1.67, not the intercept. The 2nd option is wrong because this isn’t what <em>would</em> happen, it’s only what the model would predict would happen. Moreover, it’s unreliable because we don’t observe the duty anywhere near zero. The 3rd option is wrong because it’s like a wrong interpetation of the slope term (mixing up the independent variable with the dependent variable) and not the intercept term. The last option is right because we don’t observe the duty at or near zero, as can be seen from the summary output of the variable (lowest value of 35.9 cents):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>duty)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.3590  0.3590  0.5068  0.5068  0.6545  0.6545 </code></pre>
</div>
</div>
</section>
<section id="question-4" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-4">Question 4</h4>
<p>Report the sample regression slope.</p>
<p><strong>Answer</strong>: 0.54644</p>
<p>We can read it from the summary output above, or else extract it from the model with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     duty 
0.5464433 </code></pre>
</div>
</div>
</section>
<section id="question-5" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-5">Question 5</h4>
<p>Test the following claim: if the excise duty fell by €1, then the price of petrol would fall by more than 50 cents on average. Use a significance level of 5%.</p>
<ul>
<li>What is the null hypothesis? <span class="math inline">\beta_1</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in a value in the blank).</li>
<li>What is the alternative hypothesis? <span class="math inline">\beta_1</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in a value in the blank).</li>
<li>The test statistic <span class="math inline">T=(B_1-b)/S_{B_1}</span> follows a <span class="math inline">t</span> distribution with <span class="math inline">n/k/n-1/n-2/n-k</span> (choose one) degrees of freedom under <span class="math inline">H_0</span>/<span class="math inline">H_1</span> (choose one).</li>
<li>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the critical value? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Therefore, (choose an option below):
<ul>
<li>We reject, there is sufficient evidence that it would fall by more than 50 cents on average.</li>
<li>We don’t reject, there is sufficient evidence that it would fall by more than 50 cents on average.</li>
<li>We reject, there is insufficient evidence that it would fall by more than 50 cents on average.</li>
<li>We don’t reject, there is insufficient evidence that it would fall by more than 50 cents on average.</li>
</ul></li>
</ul>
<p><strong>Answer:</strong></p>
<ul>
<li><span class="math inline">H_0</span>: <span class="math inline">\beta_1\leq 0.5</span>.</li>
<li><span class="math inline">H_1</span>: <span class="math inline">\beta_1&gt; 0.5</span>.</li>
<li><span class="math inline">T=\frac{B_1-b}{S_{B_1}}</span> follows a <span class="math inline">t</span> distribution with <span class="math inline">n-2</span> degrees of freedom under <span class="math inline">H_0</span>.</li>
<li>The value of the test statistic is can be found with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m1))[<span class="st">"duty"</span>, <span class="st">"Estimate"</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>s_b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m1))[<span class="st">"duty"</span>, <span class="st">"Std. Error"</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> (b_1 <span class="sc">-</span> <span class="fl">0.5</span>) <span class="sc">/</span> s_b_1</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.172577</code></pre>
</div>
</div>
<ul>
<li>The critical value can be found with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>, m1<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.657651</code></pre>
</div>
</div>
<ul>
<li>Therefore, <em>we don’t reject, there is insufficient evidence that it would fall by more than 50 cents on average.</em></li>
</ul>
<p><em>Explanation:</em> The interpretation of the estimated slope is that if the duty increases by €1, then the price of petrol will increase by 54.6 cents on average. This means that if the duty <em>decreases</em> by €1, then the price of petrol will <em>decrease</em> by 54.6 cents on average. The claim says that the price of petrol would fall <em>by more than 50 cents</em> on average from a €1 decrease in the duty. This would happen if <span class="math inline">\beta_1&gt;0.5</span>. So this is the alternative hypothesis. The null is then <span class="math inline">\beta_1\leq 0.5</span>. With a simple linear regression model, the test statistic follows a <span class="math inline">t</span> distribution with <span class="math inline">n-k-1=n-2</span> degrees of freedom under <span class="math inline">H_0</span> (because <span class="math inline">k=1</span>). This is an upper tail test so we get the critical value with <code>qt(0.95, n-k-1)</code>, and we can use <code>m1$df.residual</code> to obtain <code>n-k-1</code> directly, or else read it from the model output (120). Because the test statistic is greater than the critical value, we reject <span class="math inline">H_0</span>.</p>
</section>
</section>
<section id="model-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-2">Model 2</h2>
<p>Estimate a simple linear regression model explaining the price of petrol with the price of Brent crude oil.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(petrol <span class="sc">~</span> oil, <span class="at">data =</span> df)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = petrol ~ oil, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.19536 -0.08191  0.01147  0.06111  0.20955 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.879261   0.142817   13.16   &lt;2e-16 ***
oil         0.000590   0.001256    0.47     0.64    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1039 on 120 degrees of freedom
Multiple R-squared:  0.001834,  Adjusted R-squared:  -0.006484 
F-statistic: 0.2205 on 1 and 120 DF,  p-value: 0.6395</code></pre>
</div>
</div>
<section id="question-6" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-6">Question 6</h4>
<p>Use a <span class="math inline">t</span>-test to test the following null and alternative hypotheses:</p>
<p><span class="math display">
\begin{split}
H_0:\,&amp; \beta_1 = 0  \\
H_1:\,&amp; \beta_1 \neq 0
\end{split}
</span></p>
<p>Assume for this question that the model assumptions hold. Use a significance level of 5%.</p>
<ul>
<li>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the test’s <span class="math inline">p</span>-value? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the conclusion? Choose an option below:
<ul>
<li><span class="math inline">p\leq \alpha</span>; the model is useful.</li>
<li><span class="math inline">p&gt; \alpha</span>; the model is useful.</li>
<li><span class="math inline">p\leq \alpha</span>; the model is useless.</li>
<li><span class="math inline">p&gt; \alpha</span>; the model is useless.</li>
</ul></li>
</ul>
<p><strong>Answer:</strong></p>
<p>We can obtain the answers directly from the model output:</p>
<ul>
<li>Test statistic: 0.47</li>
<li><span class="math inline">p</span>-value: 0.64</li>
<li>Conclusion: <span class="math inline">p&gt; \alpha</span>; the model is useless.</li>
</ul>
</section>
<section id="question-7" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-7">Question 7</h4>
<p>Choose the correct options out of the options in <strong>bold</strong> below:</p>
<p>In a line plot of the residuals there is <strong>an increasing/a decreasing/no trend</strong> (choose one) in the first 60 time periods. This is an indication that <strong>linearity/homoskedasticity/normality/independence</strong> (choose one) <strong>holds/is violated</strong> (choose one).</p>
<p>In a scatter plot of the residuals against the Brent Crude oil price, all the residuals are <strong>positive/negative/zero</strong> (choose one) when the Brent Crude oil price is below €105 per barrel. This is an indication that <strong>linearity/homoskedasticity/normality/independence</strong> (choose one) <strong>holds/is violated</strong> (choose one).</p>
<p>In a histogram of the residuals, the bins of residuals <strong>deviate significantly from the fitted normal curve/line up very closely with the fitted normal curve</strong> (choose one). Therefore <strong>linearity/homoskedasticity/normality/independence</strong> (choose one) <strong>holds/is violated</strong> (choose one).</p>
<p><strong>Answer:</strong></p>
<p>We can create these plots with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>e <span class="ot">&lt;-</span> m2<span class="sc">$</span>residuals</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>t <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(t, e)) <span class="sc">+</span> <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="2022-exam-solutions_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(oil, e)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="2022-exam-solutions_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(e)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fu">sd</span>(df<span class="sc">$</span>e)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="2022-exam-solutions_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In a line plot of the residuals there is <em>an increasing trend</em> in the first 60 time periods. This is an indication that <em>independence</em> <em>is violated</em>.</p>
<p>In a scatter plot of the residuals against the Brent Crude oil price, all the residuals are <em>positive</em> when the Brent Crude oil price is below €105 per barrel. This is an indication that <em>linearity</em> <em>is violated</em>.</p>
<p>In a histogram of the residuals, the bins of residuals <em>deviate significantly from the fitted normal curve</em>. Therefore <em>normality</em> <em>is violated</em>.</p>
<p><em>Explanation:</em> For independence, there should be no discernable pattern in a plot of the residuals over time.</p>
<p>For the remaining two parts, these are no longer relevant starting in Fall 2024. Starting in Fall 2024 we no longer inspect the histogram of residuals for normality nor check for linearity. We only inspect scatter plots of the residuals against the independent variable for heteroskedasticity and the residuals over time for serial correlation. Therefore you don’t need to know how to make the histogram with the fitted normal curve.</p>
</section>
</section>
<section id="model-3" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-3">Model 3</h2>
<p>You think that the poor performance of the oil model is related to the fact that the excise duty changed so much half-way through the sample. You decide to make an improved model that combines the excise duty and the oil price to explain the petrol price.</p>
<p>Regress the variable <code>petrol</code> on the variables:</p>
<ol type="1">
<li><code>duty</code></li>
<li><code>oil</code></li>
</ol>
<p>If you did this correctly, your estimated intercept should be 0.594.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(petrol <span class="sc">~</span> duty <span class="sc">+</span> oil, <span class="at">data =</span> df)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = petrol ~ duty + oil, data = df)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.077436 -0.019884 -0.003459  0.022454  0.082818 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.5939982  0.0630736   9.418 4.49e-16 ***
duty        0.7696276  0.0248035  31.029  &lt; 2e-16 ***
oil         0.0084825  0.0004897  17.323  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.03459 on 119 degrees of freedom
Multiple R-squared:  0.8902,    Adjusted R-squared:  0.8884 
F-statistic: 482.4 on 2 and 119 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="question-8" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-8">Question 8</h4>
<p>In the multiple linear regression model of the petrol price regressed on the variables (i) duty and (ii) oil, which variables are individually significant at the 1% level?</p>
<p><strong>Answer:</strong> <code>duty</code> and <code>oil</code>.</p>
</section>
<section id="question-9" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-9">Question 9</h4>
<p>Choose the answer below that best represents the interpretation of the estimated coefficient on excise duty:</p>
<ul>
<li>If the excise duty increases by 1 cent, then the price of petrol will increase by 0.77 cents.</li>
<li>If the excise duty increases by 1 cent, then the price of petrol will increase by 0.77 cents on average.</li>
<li>If the excise duty increases by 1 cent, then holding the Brent Crude oil price fixed, the price of petrol will increase by 0.77 cents.</li>
<li>If the excise duty increases by 1 cent, then holding the Brent Crude oil price fixed, the price of petrol will increase by 0.77 cents on average.</li>
</ul>
<p><strong>Answer:</strong> If the excise duty increases by 1 cent, then holding the Brent Crude oil price fixed, the price of petrol will increase by 0.77 cents on average.</p>
</section>
<section id="question-10" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-10">Question 10</h4>
<p>If the price of a barrel of oil increased by €10 while the excise duty remained fixed, by how many cents would the price of petrol be expected to increase according to the model?</p>
<p><strong>Answer:</strong> 8.48 cents.</p>
<p><em>Explanation</em> The interpretation of <span class="math inline">b_3=0.0084825</span> is that a €1 increase in the price of a barrel of oil increases the price of petrol by €0.00848 on average, holding the duty fixed. So a €10 increase will increase this by €0.0848 (multiply by 10). To convert this to cents, we multiply further by 100, so 8.48 cents. We can also calculate this in R with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m3)[<span class="dv">3</span>] <span class="sc">*</span> <span class="dv">10</span> <span class="sc">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     oil 
8.482529 </code></pre>
</div>
</div>
</section>
<section id="question-11" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-11">Question 11</h4>
<p>Report a 95% confidence interval for <span class="math inline">\beta_1</span> (the coefficient on the excise duty).</p>
<ul>
<li>Lower bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Upper bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
</ul>
<p><strong>Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m3, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %      97.5 %
(Intercept) 0.469106294 0.718890156
duty        0.720514191 0.818740975
oil         0.007512913 0.009452144</code></pre>
</div>
</div>
<p>The lower bound is 0.7205. The upper bound is 0.8187.</p>
</section>
<section id="question-12" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-12">Question 12</h4>
<p>The 95% confidence interval for the coefficient on Brent Crude oil is [0.007513, 0.009452]. Choose the answer below which best explains the interpretation of this confidence interval.</p>
<ul>
<li>We are 95% confident that the population <span class="math inline">\beta_2</span> is between 0.007513 and 0.009452.</li>
<li>We are 95% confident that the estimator <span class="math inline">B_2</span> is between 0.007513 and 0.009452.</li>
<li>We are 95% confident that the sample estimate <span class="math inline">b_2</span> is between 0.007513 and 0.009452.</li>
<li>We are 95% confident that the hinge <span class="math inline">b</span> is between 0.007513 and 0.009452.</li>
</ul>
<p><strong>Answer:</strong> We are 95% confident that the population <span class="math inline">\beta_2</span> is between 0.007513 and 0.009452.</p>
</section>
<section id="question-13" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-13">Question 13</h4>
<p>What percentage of variation in the petrol data is explained by the variation in the excise duty and Brent Crude oil price?</p>
<p>Write your answer as a percentage (a number between 0 and 100) and not as a proportion (a number between 0 and 1).</p>
<p><strong>Answer:</strong> 89.01998. We multiply the <span class="math inline">R^2</span> by 100 to obtain this. We can read the <span class="math inline">R^2</span> from the summary output, or else we can calculate it directly with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)<span class="sc">$</span>r.squared <span class="sc">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 89.01998</code></pre>
</div>
</div>
</section>
<section id="question-14" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-14">Question 14</h4>
<p>Use an appropriate test to test if this model is useful.</p>
<p>What is the null hypothesis? <span class="math inline">\beta_1=\beta_2=</span> <span class="math inline">\underline{\hspace{20mm}}</span> What is the alternative hypothesis? <strong>at least one of/each of/one of/none of</strong> (choose one) <span class="math inline">\beta_j\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for <span class="math inline">j=1,2</span>. Under the null hypothesis, the test statistic follows a(n) <strong>F/student t/normal/binomial/chi squared</strong> (choose one) distribution with <span class="math inline">\underline{\hspace{20mm}}</span> numerator and <span class="math inline">\underline{\hspace{20mm}}</span> denominator degrees of freedom. The <span class="math inline">a</span> in the formula for the test statistic below in this sample equals <span class="math inline">\underline{\hspace{20mm}}</span></p>
<p><span class="math display">
\frac{a/k}{SSE/(n-k-1)}
</span> What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span> What is the critical value? <span class="math inline">\underline{\hspace{20mm}}</span> What is the conclusion? Choose one of the options below:</p>
<ul>
<li>Reject; the model is useful.</li>
<li>Reject; the model is useless.</li>
<li>Don’t reject; the model is useful.</li>
<li>Don’t reject; the model is useless.</li>
</ul>
<p><strong>Answer:</strong></p>
<ul>
<li><span class="math inline">H_0</span>: <span class="math inline">\beta_1=\beta_2=0</span>.</li>
<li><span class="math inline">H_1</span>: At least one of <span class="math inline">\beta_j\neq 0</span> for <span class="math inline">j=1,2</span>.</li>
<li>Under <span class="math inline">H_0</span>, the test statistic follows an <span class="math inline">F</span> distribution with 2 numerator and 119 denominator degrees of freedom (numbers <span class="math inline">k=2</span> and <span class="math inline">n-k-1=119</span> can be read from the last line of the summary output).</li>
<li>The <span class="math inline">a</span> in the formula is the <span class="math inline">SSR</span> and can be calculated with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(petrol <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> df), m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: petrol ~ 1
Model 2: petrol ~ duty + oil
  Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
1    121 1.29662                                  
2    119 0.14237  2    1.1542 482.39 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>the <span class="math inline">SSR</span> is 1.1542. - The value of the test statistic is 482.39. This can be calculated directly with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)<span class="sc">$</span>fstatistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value    numdf    dendf 
482.3934   2.0000 119.0000 </code></pre>
</div>
</div>
<ul>
<li>The critical value is:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">2</span>, <span class="dv">119</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.072429</code></pre>
</div>
</div>
<ul>
<li>The conclusion is <em>Reject; the model is useful</em>.</li>
</ul>
</section>
<section id="question-15" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-15">Question 15</h4>
<p>On August 1st, the Brent Crude oil price was 106.09 and the excise duty remained at 35.9 cents. What is the predicted price of petrol on August 1st according to the model?</p>
<p>Use your model to construct an interval that contains with 95% probability the actual realization of the price of petrol on August 1st.</p>
<p>Prediction: <span class="math inline">\underline{\hspace{20mm}}</span> Lower bound: <span class="math inline">\underline{\hspace{20mm}}</span> Upper bound: <span class="math inline">\underline{\hspace{20mm}}</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">oil =</span> <span class="fl">106.09</span>, <span class="at">duty =</span> <span class="fl">0.359</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m3, df_p, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 1.770206 1.700305 1.840107</code></pre>
</div>
</div>
<p>The prediction is €1.77. The lower bound of the interval is €1.70 and the upper bound is €1.84.</p>
</section>
<section id="question-16" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-16">Question 16</h4>
<p>If the government didn’t change the excise duty and kept it at 65.45 cents, what does the model predict the petrol price would have been on June 1st?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">oil =</span> <span class="fl">122.20</span>, <span class="at">duty =</span> <span class="fl">0.6545</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m3, df_p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
2.134285 </code></pre>
</div>
</div>
<p><em>Explanation:</em> We look in the data at what the price of oil was that day and use it in our prediction.</p>
</section>
</section>
<section id="model-4" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-4">Model 4</h2>
<p>If you plot the predicted values from the previous model (with the Excise duty and the Brent Crude oil price as independent variables) against the dependent variable over time, we can see that it fits the data reasonably well:</p>
<div class="cell">
<details>
<summary>Show code generating the plot below</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"petrol.csv"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(petrol <span class="sc">~</span> duty <span class="sc">+</span> oil, <span class="at">data =</span> tmp)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>tmp<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(tmp<span class="sc">$</span>date)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>tmp<span class="sc">$</span><span class="st">`</span><span class="at">Predicted values</span><span class="st">`</span> <span class="ot">&lt;-</span> m<span class="sc">$</span>fitted.values</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>tmp<span class="sc">$</span>Data <span class="ot">&lt;-</span> tmp<span class="sc">$</span>petrol</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_TIME"</span>, <span class="st">"C"</span>))  <span class="co"># make months display in English</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> tmp[, <span class="fu">c</span>(<span class="st">"date"</span>, <span class="st">"Predicted values"</span>, <span class="st">"Data"</span>)]</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">melt</span>(tmp, <span class="at">id.vars =</span> <span class="st">"date"</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(date, value, <span class="at">color =</span> variable)) <span class="sc">+</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Petrol Price (in €)"</span>) <span class="sc">+</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="2022-exam-solutions_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>However, your boss asks you to instead try a different approach to improve the fit. He asks you to model the petrol price as a function of the excise duty and period-specific time trends: one for April-May, and another for June-July.</p>
<p>Towards doing this, create two variables according to the following commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>t <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>t_post <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">as.Date</span>(df<span class="sc">$</span>date) <span class="sc">&gt;</span> <span class="fu">as.Date</span>(<span class="st">"2022-05-31"</span>), </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">as.Date</span>(df<span class="sc">$</span>date) <span class="sc">-</span> <span class="fu">as.Date</span>(<span class="st">"2022-05-31"</span>), <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you did this correctly, the first variable should be 1, 2, 3, …, 122 until the end of the data set. The second variable should contain zeros for each day until June 1st, after which it will be the sequence 1, 2, 3, …, 61 until the end of the data set.</p>
<p>Then use these two variables to estimate a regression model with petrol as the dependent variable and:</p>
<ul>
<li><code>duty</code></li>
<li><code>t</code></li>
<li><code>t_post</code></li>
</ul>
<p>as the three independent variables. If you estimated the model correctly, your estimated intercept should equal 1.641.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>t <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>t_post <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">as.Date</span>(df<span class="sc">$</span>date) <span class="sc">&gt;</span> <span class="fu">as.Date</span>(<span class="st">"2022-05-31"</span>), </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">as.Date</span>(df<span class="sc">$</span>date) <span class="sc">-</span> <span class="fu">as.Date</span>(<span class="st">"2022-05-31"</span>), <span class="dv">0</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(petrol <span class="sc">~</span> duty <span class="sc">+</span> t <span class="sc">+</span> t_post, <span class="at">data =</span> df)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = petrol ~ duty + t + t_post, data = df)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.094879 -0.014864 -0.000491  0.013687  0.075536 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.6407749  0.0225635   72.72   &lt;2e-16 ***
duty         0.4506160  0.0298921   15.07   &lt;2e-16 ***
t            0.0029424  0.0001773   16.59   &lt;2e-16 ***
t_post      -0.0067034  0.0002508  -26.73   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02439 on 118 degrees of freedom
Multiple R-squared:  0.9459,    Adjusted R-squared:  0.9445 
F-statistic: 687.4 on 3 and 118 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The predicted petrol price against the actual petrol price over time evolve according to the following graph:</p>
<div class="cell">
<details>
<summary>Show code generating the plot below</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>tmp<span class="sc">$</span><span class="st">`</span><span class="at">Predicted values</span><span class="st">`</span> <span class="ot">&lt;-</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(petrol <span class="sc">~</span> duty <span class="sc">+</span> t <span class="sc">+</span> t_post, <span class="at">data =</span> df)<span class="sc">$</span>fitted.values</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">melt</span>(tmp, <span class="at">id.vars =</span> <span class="st">"date"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(date, value, <span class="at">color =</span> variable)) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Petrol Price (in €)"</span>) <span class="sc">+</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="2022-exam-solutions_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>With this model, the predicted petrol price follows a linear time trend in the first two months, then has an abrupt drop on June 1, after which it follows a linear trend again with a different slope.</p>
<section id="question-17" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-17">Question 17</h4>
<p>In the April-May period, holding the excise duty fixed, the model predicts that each day the petrol price is expected to increase by how many cents?</p>
<p><strong>Answer:</strong> 0.29424 cents.</p>
<p><em>Explanation</em> A one-unit increase in <code>t</code> on average increases <code>petrol</code> by 0.0029424 units, holding <code>t_post</code> and <code>duty</code> fixed. A unit increse <code>t</code> holding <code>t_post</code> fixed corresponds to a one-day increase in May-July (when <code>t_post</code> is zero). Finally 0.0029424 units of <code>petrol</code> is 0.29424 cents (multiply by 100).</p>
</section>
<section id="question-18" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-18">Question 18</h4>
<p>In the June-July period, holding the excise duty fixed, the model predicts that each day the petrol price is expected to decrease by how many cents?</p>
<p><strong>Answer:</strong> 0.3761 cents.</p>
<p><em>Explanation</em> The model is:</p>
<p><span class="math display">
\mathbb{E}[petrol_t|duty_t,t_t,t\_post_t]=\beta_0+\beta_1duty_t + \beta_2 t_t + \beta_3 t\_post_t
</span> Holding the duty fixed, one day later in the post period is: <span class="math display">
\mathbb{E}[petrol_t|duty_t,t_t+1,t\_post_t+1]=\beta_0+\beta_1duty_t + \beta_2 \left(t_t+1\right) + \beta_3\left( t\_post_t+1\right)
</span> Taking differences: <span class="math display">
\beta_2+\beta_3
</span> Thus we need to add <span class="math inline">b_2+b_3</span> to get the average effect of a one-day increase in the post-period (holding duty fixed). This is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">coef</span>(m4)[<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.00376095</code></pre>
</div>
</div>
<p>Finally, the question is asking how big the decrease is in cents. So we multiply by 100 and take the absoute value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">coef</span>(m4)[<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>]) <span class="sc">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.376095</code></pre>
</div>
</div>
</section>
<section id="question-19" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-19">Question 19</h4>
<p>Report the coefficient of determination from the model.</p>
<p><strong>Answer:</strong> We can read the <span class="math inline">R^2</span> straight from the summary output. This is 0.9459. We can also get it directly with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9458794</code></pre>
</div>
</div>
</section>
<section id="question-20" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-20">Question 20</h4>
<p>Between the models 3 (excise duty and Brent Crude oil) and 4 (excise duty and period-specific time trends), which can explain a higher percentage of the variation in the petrol price data?</p>
<ul>
<li>The model with excise duty and the period-specific time trends (Model 4).</li>
<li>The model with excise duty and the Brent Crude oil price (Model 3).</li>
<li>The models contain different variables and cannot be compared.</li>
<li>Both models explain the petrol price data equally well because the total sum of squares is the same for both models.</li>
</ul>
<p><strong>Answer:</strong> The model with excise duty and the period-specific time trends (Model 4).</p>
<p><em>Explanation:</em> Model 4’s <span class="math inline">R^2</span> is higher (0.9459 versus 0.8902). Model 4 can explain a higher proportion of the variation in petrol prices.</p>
</section>
</section>
<section id="model-5" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-5">Model 5</h2>
<p>Your boss thinks the period-specific time trends are promising. He then asks you to estimate a complete model explaining the petrol price by the following 4 variables, combining the previous approaches:</p>
<ul>
<li><code>duty</code></li>
<li><code>oil</code></li>
<li><code>t</code></li>
<li><code>t_post</code></li>
</ul>
<p>If you estimated the model correctly, your estimated intercept should be 1.325.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(petrol <span class="sc">~</span> duty <span class="sc">+</span> oil <span class="sc">+</span> t <span class="sc">+</span> t_post, <span class="at">data =</span> df)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = petrol ~ duty + oil + t + t_post, data = df)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.082110 -0.014665 -0.000869  0.015710  0.063820 

Coefficients:
              Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept)  1.3251477  0.0728061  18.201   &lt; 2e-16 ***
duty         0.5370511  0.0336404  15.964   &lt; 2e-16 ***
oil          0.0025577  0.0005652   4.526 0.0000146 ***
t            0.0022609  0.0002229  10.145   &lt; 2e-16 ***
t_post      -0.0051800  0.0004090 -12.665   &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02259 on 117 degrees of freedom
Multiple R-squared:  0.9539,    Adjusted R-squared:  0.9524 
F-statistic: 605.8 on 4 and 117 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The model’s predictions over time now look like:</p>
<div class="cell">
<details>
<summary>Show code generating the plot below</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>tmp<span class="sc">$</span><span class="st">`</span><span class="at">Predicted values</span><span class="st">`</span> <span class="ot">&lt;-</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(petrol <span class="sc">~</span> duty <span class="sc">+</span> oil <span class="sc">+</span> t <span class="sc">+</span> t_post, <span class="at">data =</span> df)<span class="sc">$</span>fitted.values</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">melt</span>(tmp, <span class="at">id.vars =</span> <span class="st">"date"</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(date, value, <span class="at">color =</span> variable)) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Petrol Price (in €)"</span>) <span class="sc">+</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="2022-exam-solutions_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="question-21" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-21">Question 21</h4>
<p>Using an appropriate test, test the joint usefulness of the period-specific trend terms (coefficients 3 and 4 in the model).</p>
<p>Use a significance level of 5%.</p>
<p>Using an appropriate test, test the joint usefulness of the period-specific trend terms (coefficients 3 and 4 in the model).</p>
<p>Use a significance level of 5%.</p>
<ul>
<li>What is the null hypothesis? <span class="math inline">\beta_j</span> = <span class="math inline">\underline{\hspace{20mm}}</span> for <span class="math inline">j=</span><strong>1,2/3,4/1,2,3,4/0,1,2,3,4</strong> (choose one).</li>
<li>The alternative hypothesis is that the null hypothesis does not hold.</li>
<li>The formula for the test statistic has the following form: <span class="math display">
\frac{a/(k-g)}{b/(n-k-1)}
</span></li>
<li>What is the value of a and b in your sample? a: <span class="math inline">\underline{\hspace{20mm}}</span> b: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the critical value? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the conclusion? <strong>reject/don’t reject/accept/don’t accept</strong> (choose one) the null hypothesis. The period-specific trend terms are jointly <strong>useful/useless/colinear/different</strong> (choose one).</li>
</ul>
<p><strong>Answer:</strong></p>
<ul>
<li><span class="math inline">H_0</span>: <span class="math inline">\beta_j=0</span> for <span class="math inline">j=3,4</span>.</li>
<li><span class="math inline">H_1</span>: <span class="math inline">\beta_j\neq 0</span> for <span class="math inline">j=3,4</span>.</li>
<li>Under <span class="math inline">H_0</span>, the test statistic <span class="math inline">F=\frac{(SSE_r-SSE_c)/(k-g)}{SSE_c/(n-k-1)}</span> follows an <span class="math inline">F</span> distribution with <span class="math inline">k-g=2</span> and <span class="math inline">n-k-1=117</span> degrees of freedom. Thus <span class="math inline">a</span> represents <span class="math inline">SSE_r-SSE_c</span> and <span class="math inline">b</span> represents <span class="math inline">SSE_c</span>. We can calculate these with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m3, m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: petrol ~ duty + oil
Model 2: petrol ~ duty + oil + t + t_post
  Res.Df      RSS Df Sum of Sq      F    Pr(&gt;F)    
1    119 0.142369                                  
2    117 0.059719  2   0.08265 80.963 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>because <code>m3</code> above is actually the reduced model (<code>petrol ~ duty + oil</code>) and <code>m5</code> is the complete model. The value of <span class="math inline">SSE_r-SSE_c</span> is 0.08265 and the value of <span class="math inline">SSE_c</span> is 0.059719.</p>
<ul>
<li>The value of the test statistic is 80.963.</li>
<li>The critical value can be found with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">2</span>, <span class="dv">117</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.073763</code></pre>
</div>
</div>
<ul>
<li>Conclusion: <em>Reject</em> the null hypothesis. The period-specific trend terms are jointly <em>useful</em>.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>