<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics 2 2023/24 Exam Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="2023-exam-solutions_files/libs/clipboard/clipboard.min.js"></script>
<script src="2023-exam-solutions_files/libs/quarto-html/quarto.js"></script>
<script src="2023-exam-solutions_files/libs/quarto-html/popper.min.js"></script>
<script src="2023-exam-solutions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2023-exam-solutions_files/libs/quarto-html/anchor.min.js"></script>
<link href="2023-exam-solutions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2023-exam-solutions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2023-exam-solutions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2023-exam-solutions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2023-exam-solutions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistics 2 2023/24 Exam Solutions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>Chief Executive Officers (CEOs) of large companies often earn extremely large salaries, often hundreds of times the salaries of the company’s regular employees. These relative pay differences are often criticized. You are tasked with understanding which and how much different factors impact CEO compensation. You collect data on a random sample of <span class="math inline">n=132</span> CEOs from different companies in the year 1990. Your dataset contains the following variables:</p>
<ul>
<li><code>salary</code>: Annual CEO compensation in 1990, measured in thousands of dollars ($1000s).</li>
<li><code>age</code>: Age of CEO in years.</li>
<li><code>college</code>: Dummy variable which equals 1 if the CEO attended college and 0 otherwise.</li>
<li><code>grad</code>: Dummy variable which equals 1 if the CEO attended graduate school (post-graduate education, e.g.&nbsp;an MBA) and 0 otherwise.</li>
<li><code>comten</code>: Number of years the CEO has worked with the company.</li>
<li><code>ceoten</code>: Number of years the CEO has been the CEO in the company.</li>
<li><code>sales</code>: The total sales of the company in 1990, measured in millions of dollars ($1,000,000s).</li>
<li><code>profits</code>: The total profits of the company in 1990, measured in millions of dollars ($1,000,000s).</li>
<li><code>mktval</code>: The total market value of the company at the end of 1990, measured in millions of dollars ($1,000,000s).</li>
</ul>
<p>The dataset can be downloaded by clicking the following link: <a href="https://walshc.github.io/stats2/ceosal.csv">ceosal.csv</a></p>
<p>In the questions that follow, pay particular attention to the units of the variables. The salaries are measured thousands of dollars and sales, profits and market value are measured in millions of dollars.</p>
<section id="question-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-1">Question 1</h4>
<p>Report the sample correlation coefficient between <code>salary</code> and <code>sales</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"ceosal.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df<span class="sc">$</span>salary, df<span class="sc">$</span>sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4464905</code></pre>
</div>
</div>
<p><strong>Answer:</strong> 0.4464905</p>
</section>
<section id="question-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-2">Question 2</h4>
<p>The sample correlation coefficient between <code>salary</code> and <code>college</code> is -0.200. Choose the answer below which best represents the interpretation of this correlation coefficient.</p>
<ul>
<li>There is a weak negative linear relationship between CEO salary and having a college degree.</li>
<li>There is a weak positive linear relationship between CEO salary and having a college degree.</li>
<li>There is a very strong negative linear relationship between CEO salary and having a college degree.</li>
<li>There is a very strong positive linear relationship between CEO salary and having a college degree.</li>
<li>Obtaining a college degree on average decreases your salary by 200 dollars, holding everything else fixed.</li>
<li>Obtaining a college degree on average decreases your salary by 0.2 dollars, holding everything else fixed.</li>
</ul>
<p><strong>Answer:</strong> There is a weak negative linear relationship between CEO salary and having a college degree.</p>
</section>
<section id="question-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-3">Question 3</h4>
<p>Report the sample covariance between <code>salary</code> and <code>ceoten</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(df<span class="sc">$</span>salary, df<span class="sc">$</span>ceoten)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 387.2734</code></pre>
</div>
</div>
<p><strong>Answer:</strong> 387.2734</p>
</section>
<section id="block-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="block-2">Block 2</h3>
<p>Estimate a simple linear regression model explaining <code>salary</code> with <code>sales</code>. If you estimated the model correctly, your estimated constant term should be 542.063.</p>
<p>Use this model to answer the following questions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> sales, <span class="at">data =</span> df)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sales, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-528.80 -211.70  -64.71  151.51 1059.87 

Coefficients:
             Estimate Std. Error t value     Pr(&gt;|t|)    
(Intercept) 542.06347   39.27227  13.803      &lt; 2e-16 ***
sales         0.12364    0.02173   5.689 0.0000000805 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 303.4 on 130 degrees of freedom
Multiple R-squared:  0.1994,    Adjusted R-squared:  0.1932 
F-statistic: 32.37 on 1 and 130 DF,  p-value: 0.00000008047</code></pre>
</div>
</div>
<section id="question-4" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-4">Question 4</h4>
<p>Report the sample regression slope.</p>
<p><strong>Answer:</strong> 0.1236</p>
</section>
<section id="question-5" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-5">Question 5</h4>
<p>In a company with $1m more in sales, how much more do we expect CEOs in that company to earn (in dollars)?</p>
<p><strong>Note:</strong> Be careful with the units for both sales and CEO salary.</p>
<p><strong>Answer:</strong> 123.641</p>
<p><em>Explanation:</em> The question refers to a one-unit increase in the <span class="math inline">x</span> variable, so no adjustment is needed. The <span class="math inline">y</span> variable is measured in in thousands of dollars, so we need to multiply <span class="math inline">b_1</span> by 1,000 to convert to dollars.</p>
</section>
<section id="question-6" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-6">Question 6</h4>
<p>If we take the estimate of the regression intercept at face value, which of the options below best describes the interpretation of that estimate?</p>
<ul>
<li>In companies with zero sales, CEOs on average earn $542,063,000.00 per year.</li>
<li>In companies with zero sales, CEOs on average earn $542,063.00 per year.</li>
<li>In companies with zero sales, CEOs on average earn $542.06 per year.</li>
<li>Companies with CEOs with zero salaries on average have sales of $542,063,000.00 per year.</li>
<li>Companies with CEOs with zero salaries on average have sales of $542,063.00 per year.</li>
<li>Companies with CEOs with zero salaries on average have sales of $542.06 per year.</li>
</ul>
<p><strong>Answer:</strong> In companies with zero sales, CEOs on average earn $542,063.00 per year.</p>
<p><em>Explanation:</em> The estimate of <span class="math inline">\beta_0</span> is the estimate of <span class="math inline">\mathbb{E}[Y_i|x_i=0]</span>. The <span class="math inline">y</span>-data are measured in thousands of dollars, so we need to multiply <span class="math inline">b_0</span> by 1,000.</p>
</section>
<section id="question-7" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-7">Question 7</h4>
<p>The estimate from the previous question is unreliable. This is because:</p>
<ul>
<li>We do not observe any company with zero sales, or close to zero sales.</li>
<li>We do not observe any CEO with zero salary, or close to zero salary.</li>
<li>We do not observe any company where it has BOTH zero sales (or close to zero) AND a CEO with a zero salary (or close to zero).</li>
<li>The units of the y-data and the x-data differ. One is measured in millions, and the other is measured in thousands.</li>
</ul>
<p><strong>Answer:</strong> We do not observe any company with zero sales, or close to zero sales.</p>
<p><em>Explanation:</em> We can only get a reliable estimate of <span class="math inline">\mathbb{E}[Y_i|x_i=0]</span> when we observe <span class="math inline">x</span>-data at or near zero. We can check this with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   29.0   468.2   925.0  1337.7  1925.0  5300.0 </code></pre>
</div>
</div>
<p>The smallest value of sales is 29 million dollars, very far from zero.</p>
</section>
<section id="question-8" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-8">Question 8</h4>
<p><em>Note:</em> This question involves inspecting the normality of the residuals with a plot, which we no longer do in this course starting in 2024.</p>
<p>Create some plots to visually inspect the model assumptions. Of the 4 options below, 3 contain clearly incorrect statements. Use your plots to choose the correct statement out of the 4 options:</p>
<ul>
<li>In a scatter plot of the residuals against sales, the residuals are above and below zero for both small and large values of sales. Therefore, the homoskedasticity assumption is not violated.</li>
<li>In a scatter plot of the residuals against salary, we observe that the average residuals are negative for low values of salary, and positive for large values of salary. Therefore the linearity assumption is violated.</li>
<li>Comparing a histogram of the residuals against a fitted normal curve we observe a significant deviation, as the residuals are positively skewed. Therefore the normality assumption is violated.</li>
<li>In a line plot of the residuals against the case number, we do not observe any distinguishing patterns. Therefore the independence assumption is violated.</li>
</ul>
<p><strong>Answer:</strong> Comparing a histogram of the residuals against a fitted normal curve we observe a significant deviation, as the residuals are positively skewed. Therefore the normality assumption is violated.</p>
<p><em>Explanation:</em></p>
<ul>
<li>The first option is wrong because for homoskedasticity we should check if the dispersion of the residuals changes as the <span class="math inline">x</span> variable changes.</li>
<li>The second option is wrong because the residuals plotted against the <span class="math inline">y</span> variable would not be how you would check the linearity assumption. For checking non-linearities, you would plot the residuals against the <span class="math inline">x</span> variable.</li>
<li>The fourth option is wrong because we can only check for a violation of independence by plotting the residuals over time (or case number) when we have time series data. However, here we have cross-section data.</li>
<li>This leaves the third option. We can plot a histogram of the residuals to see if they are skewed:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>residuals <span class="ot">&lt;-</span> m1<span class="sc">$</span>residuals</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for distribution of residuals:</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="2023-exam-solutions_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Indeed there are considerably more large positive values than large negative values, indicating the residuals are skewed to the right.</p>
</section>
<section id="question-9" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-9">Question 9</h4>
<p>Run a regression of the squared residuals against sales to formally test the homoskedasticity assumption. Use a 5% level for the test.</p>
<p>What is the null hypothesis? Choose one of the following options:</p>
<ul>
<li>There is no heteroskedasticity.</li>
<li>There is heteroskedasticity.</li>
</ul>
<p>What is the <span class="math inline">p</span>-value of the test?</p>
<p>What is the conclusion of the test? Choose one of the following options:</p>
<ul>
<li>There is not sufficient evidence to conclude that there is heteroskedasticity.</li>
<li>There is sufficient evidence to conclude that there is heteroskedasticity.</li>
<li>There is not sufficient evidence to conclude that there is homoskedasticity.</li>
<li>There is sufficient evidence to conclude that there is homoskedasticity.</li>
</ul>
<p><strong>Answer:</strong></p>
<ul>
<li>There is no heteroskedasticity.</li>
<li>For the <span class="math inline">p</span>-value we run the test:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>e2 <span class="ot">&lt;-</span> m1<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(e2 <span class="sc">~</span> sales, <span class="at">data =</span> df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e2 ~ sales, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-102552  -80708  -52343   10080 1019585 

Coefficients:
             Estimate Std. Error t value   Pr(&gt;|t|)    
(Intercept) 106416.39   21226.14   5.013 0.00000171 ***
sales          -11.79      11.75  -1.004      0.317    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 164000 on 130 degrees of freedom
Multiple R-squared:  0.007695,  Adjusted R-squared:  6.238e-05 
F-statistic: 1.008 on 1 and 130 DF,  p-value: 0.3172</code></pre>
</div>
</div>
<p>The <span class="math inline">p</span>-value is 0.317206. - Conclusion: There is not sufficient evidence to conclude that there is heteroskedasticity.</p>
</section>
</section>
<section id="block-3-salary-and-profits" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="block-3-salary-and-profits">Block 3: Salary and Profits</h3>
<p>Estimate a simple linear regression model explaining <code>salary</code> with <code>profits</code>. If you estimated the model correctly, your estimated constant term should be 588.959</p>
<p>Use this model to answer the following questions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> profits, <span class="at">data =</span> df)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ profits, data = df)

Residuals:
   Min     1Q Median     3Q    Max 
-593.5 -236.0  -55.9  212.6  998.3 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 588.9594    41.0908  14.333  &lt; 2e-16 ***
profits       1.5841     0.4033   3.928 0.000138 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 320.6 on 130 degrees of freedom
Multiple R-squared:  0.1061,    Adjusted R-squared:  0.09922 
F-statistic: 15.43 on 1 and 130 DF,  p-value: 0.0001383</code></pre>
</div>
</div>
<section id="question-10" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-10">Question 10</h4>
<p>Use the model to test the following claim:</p>
<p>“If a CEO can increase a company’s profits by $1m, on average they get an increase in salary of more than $1,000.”</p>
<p>Use a 5% significance level for your test.</p>
<ul>
<li><p>What is the null hypothesis? <span class="math inline">\beta_1</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in a value in the blank).</p></li>
<li><p>What is the alternative hypothesis? <span class="math inline">\beta_1</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in a value in the blank).</p></li>
<li><p>Under the null hypothesis, the test statistic <span class="math inline">T</span> follows a <span class="math inline">t</span> distribution with how many degrees of freedom? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the associated <span class="math inline">p</span>-value? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is your conclusion? Choose an option below:</p>
<ul>
<li>Reject H0: There is sufficient evidence for the claim.</li>
<li>Reject H1: There is sufficient evidence for the claim.</li>
<li>Reject H0: There is not sufficient evidence for the claim.</li>
<li>Reject H1: There is not sufficient evidence for the claim.</li>
<li>Don’t reject H0: There is sufficient evidence for the claim.</li>
<li>Don’t reject H1: There is sufficient evidence for the claim.</li>
<li>Don’t reject H0: There is not sufficient evidence for the claim.</li>
<li>Don’t reject H1: There is not sufficient evidence for the claim.</li>
</ul></li>
</ul>
<p><strong>Answers:</strong></p>
<ul>
<li><span class="math inline">H_0</span>: <span class="math inline">\beta_1 \leq 1</span></li>
<li><span class="math inline">H_1</span>: <span class="math inline">\beta_1 &gt; 1</span></li>
<li>Degrees of freedom:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>m2<span class="sc">$</span>df.residual</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 130</code></pre>
</div>
</div>
<ul>
<li>Value of the test statistic:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m2))[<span class="st">"profits"</span>, <span class="st">"Estimate"</span>]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>s_b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m2))[<span class="st">"profits"</span>, <span class="st">"Std. Error"</span>]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> (b_1 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> s_b_1</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.448373</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">p</span>-value:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(t, m2<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0749602</code></pre>
</div>
</div>
<ul>
<li>Conclusion: Don’t reject H0: There is not sufficient evidence for the claim.</li>
</ul>
<p><em>Explanation:</em> The interpretation of <span class="math inline">b_1</span> is that a one million dollar increase in profits leads to a $1,584 increase in salary on average. The claim is asking if this is larger than $1,000 in the population, thus if <span class="math inline">\beta_1&gt;1</span>. This is the alternative hypothesis, and we use the opposite for the null. The <span class="math inline">p</span>-value is above the significance level so we fail to reject <span class="math inline">H_0</span>. There is not sufficient evidence for the claim.</p>
</section>
<section id="question-11" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-11">Question 11</h4>
<p>Construct a 95% confidence interval for the coefficient on profits. Report the lower bound and upper bound of this interval below:</p>
<ul>
<li>Lower bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Upper bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m2, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept) 507.6661567 670.252598
profits       0.7862601   2.381932</code></pre>
</div>
</div>
<p>The lower bound is 0.7862601 and the upper bound is 2.381932.</p>
</section>
<section id="question-12" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-12">Question 12</h4>
<p>The 95% confidence interval for the intercept is <span class="math inline">[507.666, 670.253]</span>.</p>
<p>Insert the blanks in the interpretation of this confidence interval below. Take note of the units of the variables when writing your answer.</p>
<p>We are <span class="math inline">\underline{\hspace{20mm}}</span>% confident that the population mean salary of CEOs in companies with profits of <span class="math inline">\underline{\hspace{20mm}}</span> is between <span class="math inline">\$\underline{\hspace{20mm}}</span> and <span class="math inline">\$\underline{\hspace{20mm}}</span></p>
<p>Write your answer in dollars, taking note that the salary variable is measured in thousands of dollars.</p>
<p><strong>Answer:</strong> We are 95% confident that the population mean salary of CEOs in companies with profits of $0 is between $507,666 and $670,253.</p>
</section>
<section id="block-4" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="block-4">Block 4</h4>
<p>Create an interaction term called <code>gradsales</code> which multiplies the variables <code>grad</code> and <code>sales</code> by each other. Then use this to estimate a regression model explaining salary with the following three variables:</p>
<ul>
<li><code>grad</code></li>
<li><code>sales</code></li>
<li><code>gradsales</code></li>
</ul>
<p>If you estimated the model correctly, your estimated model intercept should be 614.916.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> grad <span class="sc">*</span> sales, <span class="at">data =</span> df)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ grad * sales, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-488.09 -207.75  -69.06  150.45 1114.10 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  614.91624   56.20435  10.941   &lt;2e-16 ***
grad        -135.08388   78.38940  -1.723   0.0873 .  
sales          0.07594    0.03343   2.271   0.0248 *  
grad:sales     0.08296    0.04383   1.893   0.0606 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 301.3 on 128 degrees of freedom
Multiple R-squared:  0.2225,    Adjusted R-squared:  0.2043 
F-statistic: 12.21 on 3 and 128 DF,  p-value: 0.0000004449</code></pre>
</div>
</div>
</section>
<section id="question-13" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-13">Question 13</h4>
<p>For companies with $1m more in sales, on average CEOs without graduate school education earn how much more (in dollars)?</p>
<p><strong>Answer:</strong> $75.94.</p>
<p><em>Explanation:</em> The model is: <span class="math display">\mathbb{E}[Y_i|grad_i,sales_i]=\beta_0 + \beta_1 grad_i + \beta_2 sales_i + \beta_3 grad_i sales_i</span> When <span class="math inline">grad_i=0</span>, the model becomes: <span class="math display">\mathbb{E}[Y_i|grad_i=0,sales_i]=\beta_0 + \beta_1 \times 0 + \beta_2 sales_i + \beta_3 \times 0 \times sales_i= \beta_0 + \beta_2 sales_i</span> Increasing sales by one unit: <span class="math display">\mathbb{E}[Y_i|grad_i=0,sales_i+1]=\beta_0 + \beta_2 \left(sales_i+1\right)=\beta_0 + \beta_2 sales_i + \beta_2</span> Taking differences: <span class="math display">\mathbb{E}[Y_i|grad_i=0,sales_i+1]-
\mathbb{E}[Y_i|grad_i=0,sales_i]=\beta_2
</span> Thus <span class="math inline">\beta_2</span> is the expected change in salary (in thousands) when sales increases by one unit (one million) for CEOs that didn’t go to graduate school.</p>
<p>Because sales is in millions and salary is in thousands, a one-dollar increase in sales leads to a:</p>
<p><span class="math display">b_2 \times \frac{1000000}{1000}=0.07594\times 1000=75.94</span> dollar increase in salary.</p>
</section>
<section id="question-14" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-14">Question 14</h4>
<p>For companies with $1m more in sales, on average CEOs with graduate school education earn how much more (in dollars)?</p>
<p><strong>Answer:</strong> $158.89.</p>
<p><em>Explanation:</em> The model is: <span class="math display">\mathbb{E}[Y_i|grad_i,sales_i]=\beta_0 + \beta_1 grad_i + \beta_2 sales_i + \beta_3 grad_i sales_i</span> When <span class="math inline">grad_i=1</span>, the model becomes: <span class="math display">\mathbb{E}[Y_i|grad_i=1,sales_i]=\beta_0 + \beta_1 + \beta_2 sales_i + \beta_3 sales_i=\beta_0+\beta_1+\left(\beta_2+\beta_3\right)sales_i</span> Increasing sales by 1 unit: <span class="math display">\mathbb{E}[Y_i|grad_i=1,sales_i+1]=\beta_0 + \beta_1 + \beta_2 sales_i + \beta_3 sales_i=\beta_0+\beta_1+\left(\beta_2+\beta_3\right)\left(sales_i+1\right)</span> Taking differences: <span class="math display">\mathbb{E}[Y_i|grad_i=1,sales_i+1]-\mathbb{E}[Y_i|grad_i=1,sales_i]=\beta_2+\beta_3</span> Therefore <span class="math inline">\beta_2+\beta_3</span> represents the expected change in salary (in thousands) when sales increases by one unit for CEOs that did go to graduate school.</p>
<p>Because sales is in millions and salary is in thousands, a one-dollar increase in sales leads to a:</p>
<p><span class="math display">\left(b_2+b_3\right) \times \frac{1000000}{1000}=\left(0.07594+0.08296\right)\times 1000=158.89</span> dollar increase in salary.</p>
<p>We could also have done this calculation in R the following way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">coef</span>(m3)[<span class="dv">3</span>] <span class="sc">+</span> <span class="fu">coef</span>(m3)[<span class="dv">4</span>]) <span class="sc">*</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sales 
158.8949 </code></pre>
</div>
</div>
</section>
</section>
<section id="block-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="block-5">Block 5</h3>
<p>Estimate a simple linear regression model explaining salary with the following 4 variables:</p>
<ul>
<li><code>sales</code></li>
<li><code>mktval</code></li>
<li><code>comten</code></li>
<li><code>ceoten</code></li>
</ul>
<p>If you estimated the model correctly, your estimate of the intercept should be 490.217.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> sales <span class="sc">+</span> mktval <span class="sc">+</span> comten <span class="sc">+</span> ceoten, <span class="at">data =</span> df)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sales + mktval + comten + ceoten, data = df)

Residuals:
   Min     1Q Median     3Q    Max 
-552.9 -182.9  -52.3  133.6 1043.2 

Coefficients:
             Estimate Std. Error t value         Pr(&gt;|t|)    
(Intercept) 490.21676   61.89257   7.920 0.00000000000103 ***
sales         0.10979    0.02359   4.655 0.00000803914634 ***
mktval        0.04888    0.02234   2.188          0.03047 *  
comten       -4.31799    2.19947  -1.963          0.05181 .  
ceoten       11.89457    3.76740   3.157          0.00199 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 290 on 127 degrees of freedom
Multiple R-squared:  0.2852,    Adjusted R-squared:  0.2627 
F-statistic: 12.67 on 4 and 127 DF,  p-value: 0.00000001052</code></pre>
</div>
</div>
<section id="question-15" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-15">Question 15</h4>
<p>Which variables are individually significant at the 5% level?</p>
<p><strong>Answer:</strong> Significant: <code>sales</code>, <code>mktval</code>, <code>ceoten</code>. Insignificant: <code>comten</code>.</p>
<p><em>Explanation</em>: We look at the <span class="math inline">p</span>-values in the model summary table. If the <span class="math inline">p</span>-value for a variable is less than 0.05 it is significant, otherwise it is insignificant.</p>
</section>
<section id="question-16" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-16">Question 16</h4>
<p>What proportion of the variation in the data on salary is left unexplained by your model? Note that proportions are between 0 and 1, so your answer should be between 0 and 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">summary</span>(m4)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7147985</code></pre>
</div>
</div>
<p><strong>Answer:</strong> 0.714799.</p>
<p><em>Explanation:</em> The <span class="math inline">R^2</span> gives the proportion of the <span class="math inline">y</span>-data that is explained by the variation in the explanatory variables. From the summary table we see it is 0.2852. To get the proportion that is unexplained, we subtract this from 1.</p>
</section>
<section id="question-17" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-17">Question 17</h4>
<p>Perform an appropriate hypothesis test to test the usefulness of the model. Use a 5% significance level.</p>
<ul>
<li><p>The null hypothesis is that <em>at least one/all/none</em> (choose one) of <span class="math inline">\beta_j</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for <span class="math inline">j=</span> <span class="math inline">\underline{\hspace{20mm}}</span> to <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in values in the blank spaces).</p></li>
<li><p>The alternative hypothesis is that <em>at least one/all/none</em> (choose one) of <span class="math inline">\beta_j</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for the same <span class="math inline">j</span> (choose one comparison operator and fill in a value in in the blank space).</p></li>
<li><p>The formula for the test statistic is of the form: <span class="math display">
\frac{Z/k}{SSE/(n-k-1)}
</span> What is the value of Z in the estimated model? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the critical value? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the conclusion? Choose one of the options below.</p>
<ul>
<li>Reject H0. The model is useful.</li>
<li>Reject H0. The model is useless.</li>
<li>Don’t reject H0. The model is useful.</li>
<li>Don’t reject H0. The model is useless.</li>
</ul></li>
</ul>
<p><strong>Answer:</strong></p>
<ul>
<li><span class="math inline">H_0</span>: all <span class="math inline">\beta_j=0</span> for <span class="math inline">j=1</span> to <span class="math inline">4</span>.</li>
<li><span class="math inline">H_1</span>: at least one <span class="math inline">\beta_j\neq 0</span> for the same <span class="math inline">j</span>.</li>
<li><span class="math inline">Z</span> is the SSR. We can find it using:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> df)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0, m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: salary ~ 1
Model 2: salary ~ sales + mktval + comten + ceoten
  Res.Df      RSS Df Sum of Sq      F        Pr(&gt;F)    
1    131 14943567                                      
2    127 10681639  4   4261927 12.668 0.00000001052 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Its value is 4261927.</p>
<ul>
<li>The value of the test statistic can be read from the summary output (12.67), or the above <code>anova()</code> output (12.668). Alternatively we can get it with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)<span class="sc">$</span>fstatistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    value     numdf     dendf 
 12.66811   4.00000 127.00000 </code></pre>
</div>
</div>
<ul>
<li>The critical value is 2.443017. We can find that with (where we can read the <span class="math inline">k=4</span> numerator and <span class="math inline">n-k-1=127</span> denominator degrees of freedom from the last line of the summary output or from the command <code>summary(m4)$fstatistic</code>):</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">4</span>, <span class="dv">127</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.443017</code></pre>
</div>
</div>
<ul>
<li>The conclusion is <em>Reject H0. The model is useful.</em> This is because the value of the <span class="math inline">F</span> statistic exceeds the critical value.</li>
</ul>
</section>
<section id="question-18" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-18">Question 18</h4>
<p>Test the joint usefulness of <code>comten</code> and <code>ceoten</code>. Use a 5% significance level. Note that these variables are the 3rd and 4th variables in your model.</p>
<ul>
<li><p>The null hypothesis is that <em>at least one/all/none</em> (choose one) of <span class="math inline">\beta_j</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for <span class="math inline">j=</span> <span class="math inline">\underline{\hspace{20mm}}</span> to <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in values in the blank spaces).</p></li>
<li><p>The alternative hypothesis is that <em>at least one/all/none</em> (choose one) of <span class="math inline">\beta_j</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for the same <span class="math inline">j</span> (choose one comparison operator and fill in a value in in the blank space).</p></li>
<li><p>According to the null hypothesis, the test statistic follows an <span class="math inline">F</span> distribution with <span class="math inline">\underline{\hspace{20mm}}</span> numerator and <span class="math inline">\underline{\hspace{20mm}}</span> denominator degrees of freedom.</p></li>
<li><p>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the critical value? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the conclusion? Choose one of the options below.</p>
<ul>
<li>Reject H0. The variables are useful additions to the model.</li>
<li>Reject H0. The variables are useless additions to the model.</li>
<li>Don’t reject H0. The variables are useful additions to the model.</li>
<li>Don’t reject H0. The variables are useless additions to the model.</li>
</ul></li>
</ul>
<p><strong>Answer:</strong></p>
<ul>
<li><span class="math inline">H_0</span>: all <span class="math inline">\beta_j=0</span> for <span class="math inline">j=3,4</span>.</li>
<li><span class="math inline">H_1</span>: at least one <span class="math inline">\beta_j\neq 0</span> for the same <span class="math inline">j</span>.</li>
<li>We can run the partial <span class="math inline">F</span> test with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>m4r <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> sales <span class="sc">+</span> mktval, <span class="at">data =</span> df)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m4r, m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: salary ~ sales + mktval
Model 2: salary ~ sales + mktval + comten + ceoten
  Res.Df      RSS Df Sum of Sq      F   Pr(&gt;F)   
1    129 11590614                                
2    127 10681639  2    908975 5.4037 0.005594 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>From here we can see there are <span class="math inline">k-g=2</span> numerator and <span class="math inline">n-k-1=127</span> denominator degrees of freedom.</li>
<li>Value of the test statistic: 5.4037 (read from <code>anova()</code> output).</li>
<li><span class="math inline">p</span>-value: 0.005594 (read from <code>anova()</code> output).</li>
<li>Conclusion: Reject H0. The variables are useful additions to the model (<em>reason:</em> <span class="math inline">p</span>-value is less than 0.05).</li>
</ul>
</section>
<section id="question-19" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-19">Question 19</h4>
<p>Using the model, provide a 95% confidence interval for the mean salary of CEOs (in dollars) with the following characteristics:</p>
<ul>
<li><p>They have been working in their company for 20 years, and have been a CEO there for 8 of those years.</p></li>
<li><p>The companies they work for have annual sales of $1,000m and a market value of $1,500m.</p></li>
<li><p>Lower bound: <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>Upper bound: <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
</ul>
<p><strong>Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sales =</span> <span class="dv">1000</span>, <span class="at">mktval =</span> <span class="dv">1500</span>, <span class="at">comten =</span> <span class="dv">20</span>, <span class="at">ceoten =</span> <span class="dv">8</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m4, df_p, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 682.1336 628.8171 735.4501</code></pre>
</div>
</div>
<ul>
<li>The lower bound is $628,817.10.</li>
<li>The upper bound is $735,450.10.</li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>