<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics 2 2023/24 Resit Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="2023-resit-solutions_files/libs/clipboard/clipboard.min.js"></script>
<script src="2023-resit-solutions_files/libs/quarto-html/quarto.js"></script>
<script src="2023-resit-solutions_files/libs/quarto-html/popper.min.js"></script>
<script src="2023-resit-solutions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2023-resit-solutions_files/libs/quarto-html/anchor.min.js"></script>
<link href="2023-resit-solutions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2023-resit-solutions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2023-resit-solutions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2023-resit-solutions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2023-resit-solutions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistics 2 2023/24 Resit Solutions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>The dataset <a href="https://walshc.github.io/stats2/housing.csv"><code>housing.csv</code></a> contains data from a random sample of 250 <em>gemeenten</em> (municipalities) in the Netherlands. For each <em>gemeente</em> in the sample we observe:</p>
<ul>
<li>The average house price (measured in thousands of euros).</li>
<li>The population growth over the last 5 years.</li>
<li>The province the <em>gemeente</em> is located in.</li>
</ul>
<p>The twelve provinces of the Netherlands are Drenthe, Flevoland, Friesland, Gelderland, Groningen, Limburg, Noord-Brabant, Noord-Holland, Overijssel, Utrecht, Zeeland and Zuid-Holland.</p>
<p>For the purpose of this exam, the <em>Randstad</em> is defined as the provinces of Noord-Holland, Zuid-Holland and Utrecht.</p>
<section id="question-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-1">Question 1</h4>
<p>What is the sample correlation between <code>pop_growth</code> and <code>house_price</code>?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"housing.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df<span class="sc">$</span>pop_growth, df<span class="sc">$</span>house_price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3046134</code></pre>
</div>
</div>
<p><strong>Answer:</strong> 0.3046134</p>
</section>
<section id="question-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-2">Question 2</h4>
<p>Choose the answer below which best interprets the correlation from the previous question:</p>
<ul>
<li>The measured correlation tells us that there is a positive linear relationship between <code>pop_growth</code> and <code>house_price</code>.</li>
<li>The measured correlation tells us that <code>house_price</code> causes <code>pop_growth</code>.</li>
<li>The measured correlation tells us that <code>pop_growth</code> causes <code>house_price</code>.</li>
<li>The measured correlation tells us nothing about the relationship between <code>pop_growth</code> and <code>house_price</code>.</li>
</ul>
<p><strong>Answer:</strong> The measured correlation tells us that there is a positive linear relationship between <code>pop_growth</code> and <code>house_price</code>.</p>
</section>
</section>
<section id="model-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-1">Model 1</h2>
<p>Estimate a simple linear regression model with the gemeente’s average house price as the dependent variable and the gemeente’s population growth as the independent variable.</p>
<p>Your estimated sample regression intercept should be 393.049.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(house_price <span class="sc">~</span> pop_growth, <span class="at">data =</span> df)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = house_price ~ pop_growth, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-217.67  -71.15  -25.65   41.26  685.62 

Coefficients:
            Estimate Std. Error t value    Pr(&gt;|t|)    
(Intercept)  393.049     12.074  32.552     &lt; 2e-16 ***
pop_growth    12.979      2.577   5.036 0.000000914 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 118.3 on 248 degrees of freedom
Multiple R-squared:  0.09279,   Adjusted R-squared:  0.08913 
F-statistic: 25.37 on 1 and 248 DF,  p-value: 0.0000009136</code></pre>
</div>
</div>
<section id="question-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-3">Question 3</h4>
<p>Report the sample regression slope.</p>
<p><strong>Answer:</strong> 12.979</p>
</section>
<section id="question-4" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-4">Question 4</h4>
<p>A 1 percentage point increase in the gemeente’s population growth is associated with on average how much of an increase in the gemeente’s average house price?</p>
<p>Write your answer in euros. Note that the dependent variable is measured in thousands of euros.</p>
<p><strong>Answer:</strong> 12979.23</p>
<p><em>Explanation:</em> A 1 percentage point increase in the gemeente’s population growth is a one-unit increase in the <span class="math inline">x</span> variable, so no adjustment is needed. The dependent variable is measured in thousands of euros, so to convert to euros we multiply the estimtae slope coefficient by 1,000. We could do this manually or else in R with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">2</span>] <span class="sc">*</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pop_growth 
  12979.23 </code></pre>
</div>
</div>
</section>
<section id="question-5" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-5">Question 5</h4>
<p>Choose the answer below which best interprets the sample regression intercept.</p>
<ul>
<li>Houses in gemeentes with zero population on average sell for €393,049. However, there are no gemeentes with zero population in the data (or close to zero) so this prediction is unreliable.</li>
<li>Houses in gemeentes with zero population on average sell for €393.05. However, there are no gemeentes with zero population in the data (or close to zero) so this prediction is unreliable.</li>
<li>Houses in gemeentes with zero population growth on average sell for €393,049.</li>
<li>Houses in gemeentes with zero population growth on average sell for €393.05.</li>
</ul>
<p><strong>Answer:</strong> Houses in gemeentes with zero population growth on average sell for €393,049.</p>
<p><em>Explanation:</em> The intercept <span class="math inline">b_0</span> gives an estimate of <span class="math inline">\mathbb{E}[Y_i|x_i=0]</span>, the average value of <span class="math inline">Y</span> when <span class="math inline">x=0</span>. Because the <span class="math inline">Y</span> variable is measured in thousands, we need to multiply <span class="math inline">b_0</span> by 1,000 to get the answer. For this prediction to be reliable we need <span class="math inline">x=0</span> to be in the range of the data. We can check this with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>pop_growth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -2.300   1.800   3.400   3.677   5.100  18.200 </code></pre>
</div>
</div>
<p>We can see that zero is in the range, and there are actually values of <code>pop_growth</code> equal to zero in the data.</p>
</section>
<section id="question-6" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-6">Question 6</h4>
<p>What is the coefficient of determination?</p>
<p><strong>Answer:</strong> 0.09279</p>
<p><em>Explanation:</em> The coefficient of determination is the same as the <span class="math inline">R^2</span>, which we can see from the 2nd-last line in the model summary output (after <code>Multiple R-squared</code>). We could also obtain this directly with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0927893</code></pre>
</div>
</div>
</section>
<section id="question-7" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-7">Question 7</h4>
<p>What proportion of the variation in house prices is left unexplained by the model?</p>
<p><em>Note:</em> proportions are numbers between 0 and 1.</p>
<p><strong>Answer:</strong> 0.9072</p>
<p><em>Explanation:</em> The <span class="math inline">R^2</span> gives the proportion of the <span class="math inline">y</span>-data explained by the <span class="math inline">x</span>-data. The proportion unexplained is then <span class="math inline">1-R^2</span>. We can calculate this manually with 1-0.09279, but we can also get it directly from R with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">summary</span>(m1)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9072107</code></pre>
</div>
</div>
</section>
<section id="question-8" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-8">Question 8</h4>
<p>Provide a 95% confidence interval for the estimated coefficient on <code>pop_growth</code>.</p>
<ul>
<li>Lower bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Upper bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
</ul>
<p><strong>Answer:</strong> Lower bound: 7.903474, upper bound: 18.05499.</p>
<p><em>Explanation:</em> We obtain a 95% confidence interval for the parameter estimates using:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) 369.267353 416.83018
pop_growth    7.903474  18.05499</code></pre>
</div>
</div>
</section>
<section id="question-9" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-9">Question 9</h4>
<p>Test the following claim at the 5% level using a <span class="math inline">p</span>-value approach:</p>
<p><em>A 1 percentage point increase in the population growth over 5 years on average increases house prices by less than €15,000.</em></p>
<ul>
<li><p>What is the null hypothesis? <span class="math inline">\beta_1</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in a value in the blank).</p></li>
<li><p>What is the alternative hypothesis? <span class="math inline">\beta_1</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in a value in the blank).</p></li>
<li><p>Under the null hypothesis, the test statistic <span class="math inline">T</span> follows a <span class="math inline">t</span> distribution with <span class="math inline">n-\underline{\hspace{10mm}}</span> degrees of freedom.</p></li>
<li><p>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the associated <span class="math inline">p</span>-value? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is your conclusion? Choose an option below:</p>
<ul>
<li>Reject H0: There is sufficient evidence for the claim.</li>
<li>Reject H1: There is sufficient evidence for the claim.</li>
<li>Reject H0: There is not sufficient evidence for the claim.</li>
<li>Reject H1: There is not sufficient evidence for the claim.</li>
<li>Don’t reject H0: There is sufficient evidence for the claim.</li>
<li>Don’t reject H1: There is sufficient evidence for the claim.</li>
<li>Don’t reject H0: There is not sufficient evidence for the claim.</li>
<li>Don’t reject H1: There is not sufficient evidence for the claim.</li>
</ul></li>
</ul>
<p><strong>Answer:</strong></p>
<ul>
<li><span class="math inline">H_0</span>: <span class="math inline">\beta\geq 15</span>.</li>
<li><span class="math inline">H_1</span>: <span class="math inline">\beta &lt; 15</span>.</li>
<li>Under <span class="math inline">H_0</span>, <span class="math inline">T=(B_1-15)/S_{B_1}</span> follows a <span class="math inline">t</span> distribution with <span class="math inline">n-2</span> degrees of freedom.</li>
<li>Value of test statistic: -0.7841297.</li>
<li><span class="math inline">p</span>-value: 0.2168561.</li>
<li>Conclusion: Don’t reject H0: There is not sufficient evidence for the claim.</li>
</ul>
<p><em>Explanation:</em></p>
<ul>
<li>The claim is that a one-unit increase in <span class="math inline">x</span> on average leads to an increase in <span class="math inline">y</span> of less than 15 units. Thus the claim is that <span class="math inline">\beta_1&lt;15</span>. This is the alternative hypothesis, with the null hypothesis being the opposite of this.</li>
<li>With a simple linear regression with one variable, the test statistic follows a <span class="math inline">t</span>-distribution with <span class="math inline">n-2</span> degrees of freedom.</li>
<li>We can calculate the value of the test statistic in R with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(m1)<span class="sc">$</span>coefficients[<span class="st">"pop_growth"</span>, <span class="st">"Estimate"</span>]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>s_b_1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(m1)<span class="sc">$</span>coefficients[<span class="st">"pop_growth"</span>, <span class="st">"Std. Error"</span>]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>(t <span class="ot">&lt;-</span> (b_1 <span class="sc">-</span> <span class="dv">15</span>) <span class="sc">/</span> s_b_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.7841297</code></pre>
</div>
</div>
<ul>
<li>Because this is a lower-tail test, the <span class="math inline">p</span>-value is calculated with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(t, m1<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2168561</code></pre>
</div>
</div>
<ul>
<li>The <span class="math inline">p</span>-value is larger than the significance level of 5%, so we do not reject <span class="math inline">H_0</span>, and say there is not sufficient evidence for the claim.</li>
</ul>
</section>
<section id="question-10" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-10">Question 10</h4>
<p>Run a formal test for heteroskedasticity using a <span class="math inline">p</span>-value approach.</p>
<ul>
<li>Report the value of the test statistic: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Report the <span class="math inline">p</span>-value: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Is there evidence of heteroskedasticity at the 5% level (Yes/No)? Choose one.</li>
</ul>
<p><strong>Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>e2 <span class="ot">&lt;-</span> m1<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(e2 <span class="sc">~</span> pop_growth, <span class="at">data =</span> df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e2 ~ pop_growth, data = df)

Residuals:
   Min     1Q Median     3Q    Max 
-30585 -12830  -8483  -2052 457218 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)     7293       4540   1.607   0.1094  
pop_growth      1793        969   1.850   0.0655 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 44480 on 248 degrees of freedom
Multiple R-squared:  0.01361,   Adjusted R-squared:  0.009635 
F-statistic: 3.422 on 1 and 248 DF,  p-value: 0.06551</code></pre>
</div>
</div>
<ul>
<li>Value of the test statistic: 3.422 (F-statistic on last line).</li>
<li><span class="math inline">p</span>-value: 0.06551 (<span class="math inline">p</span>-value on last line).</li>
<li>Conclusion: No evidence of heteroskedasticity (<span class="math inline">p</span>-value larger than 0.05).</li>
</ul>
</section>
</section>
<section id="model-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-2">Model 2</h2>
<p>Create a variable called <code>pop_growth_sq</code>, which is the square of the variable <code>pop_growth</code>.</p>
<p>Estimate a linear regression model with the gemeente’s average house price as the dependent variable and <code>pop_growth</code> and <code>pop_growth_sq</code> as the two independent variables.</p>
<p>Your estimated sample regression intercept should be 385.516.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(house_price <span class="sc">~</span> pop_growth <span class="sc">+</span> <span class="fu">I</span>(pop_growth<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> df)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = house_price ~ pop_growth + I(pop_growth^2), data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-181.78  -72.52  -26.33   39.18  683.53 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     385.5164    14.9412  25.802  &lt; 2e-16 ***
pop_growth       17.2184     5.5794   3.086  0.00226 ** 
I(pop_growth^2)  -0.3670     0.4283  -0.857  0.39240    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 118.4 on 247 degrees of freedom
Multiple R-squared:  0.09548,   Adjusted R-squared:  0.08815 
F-statistic: 13.04 on 2 and 247 DF,  p-value: 0.000004148</code></pre>
</div>
</div>
<section id="question-11" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-11">Question 11</h4>
<p>Choose the answer below which best describes the interpretation of the estimates. Use a 5% significance level.</p>
<ul>
<li>Because <code>pop_growth</code> is significantly positive and <code>pop_growth_sq</code> is significantly negative, there is no evidence of <em>a mountain-shaped</em> relationship between house prices and population growth.</li>
<li>Because <code>pop_growth</code> is significantly positive and <code>pop_growth_sq</code> is significantly negative, there is no evidence of <em>any</em> relationship between house prices and population growth.</li>
<li>Because <code>pop_growth</code> is significantly positive and <code>pop_growth_sq</code> is <em>not</em> significantly negative, there is no evidence of <em>a mountain-shaped</em> relationship between house prices and population growth.</li>
<li>Because <code>pop_growth</code> is significantly positive and <code>pop_growth_sq</code> is <em>not</em> significantly negative, there is no evidence of <em>any</em> relationship between house prices and population growth.</li>
</ul>
<p><strong>Answer:</strong> Because <code>pop_growth</code> is significantly positive and <code>pop_growth_sq</code> is <em>not</em> significantly negative, there is no evidence of <em>a mountain-shaped</em> relationship between house prices and population growth.</p>
<p><em>Explanation:</em> In a model <span class="math inline">\mathbb{E}[Y_i|x_i]=\beta_0+\beta_1 x_i + \beta_2 x_i^2</span>, a <span class="math inline">\beta_1&gt;0</span> with <span class="math inline">\beta_2&lt;0</span> indicates a mountain-shaped relationship. Here we find <span class="math inline">b_1&gt;0</span> and <span class="math inline">b_2&lt;0</span> which would indicate a mountain shape. However, the estimated <span class="math inline">b_2</span> is not significantly negative (<span class="math inline">t</span>-stat of only -0.857), so there is no statistical evidence of a mountain shape.</p>
</section>
<section id="question-12" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-12">Question 12</h4>
<p>Perform an appropriate hypothesis test to test the usefulness of the model. Use a 5% significance level.</p>
<ul>
<li>The null hypothesis is that <em>at least one/all/none</em> (choose one) of <span class="math inline">\beta_j</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for <span class="math inline">j=</span> <span class="math inline">\underline{\hspace{20mm}}</span> to <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in values in the blank spaces).</li>
<li>The alternative hypothesis is that <em>at least one/all/none</em> (choose one) of <span class="math inline">\beta_j</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for the same <span class="math inline">j</span> (choose one comparison operator and fill in a value in in the blank space).</li>
<li>The formula for the test statistic is of the form: <span class="math display">
\frac{\frac{SST - a}{k}}{\frac{a}{n-k-1}}
</span> What is the value of <span class="math inline">a</span> in the estimated model? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the critical value? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is your conclusion? <em>Reject/don’t reject</em> (choose one) <span class="math inline">H_0</span>. The model is <em>useful/useless</em> (choose one) .</li>
</ul>
<p><strong>Answer:</strong> - <span class="math inline">H_0</span>: All <span class="math inline">\beta_j=0</span> for <span class="math inline">j=1,2</span>. - <span class="math inline">H_1</span>: At least one <span class="math inline">\beta_j\neq 0</span> for the same <span class="math inline">j</span>. - <span class="math inline">a=3460951</span>. - Value of test statistic is 13.04. - Critical value: 3.032361. - Conclusion: Reject <span class="math inline">H_0</span>; the model is useful.</p>
<p><em>Explanation:</em></p>
<ul>
<li>The <span class="math inline">a</span> is the <span class="math inline">SSE</span> in the formula for the test statistic. Normally the numerator would have <span class="math inline">SSR</span>, but because <span class="math inline">SSR=SST-SSE</span>, we can also write the test statistic this way. To find the <span class="math inline">SSE</span> we can get the ANOVA table by first estimating a model with just a constant term:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(house_price <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> df)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0, m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: house_price ~ 1
Model 2: house_price ~ pop_growth + I(pop_growth^2)
  Res.Df     RSS Df Sum of Sq      F      Pr(&gt;F)    
1    249 3826273                                    
2    247 3460951  2    365323 13.036 0.000004148 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We can read the value under <code>RSS</code> for Model 2. Alternatively we can just use the <code>deviance()</code> function for our model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3460951</code></pre>
</div>
</div>
<ul>
<li>The value of the test statistic can be read from the last line of the summary output. We can also get it directly with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)<span class="sc">$</span>fstatistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    value     numdf     dendf 
 13.03612   2.00000 247.00000 </code></pre>
</div>
</div>
<ul>
<li>The critical value can be found with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">2</span>, <span class="dv">247</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.032361</code></pre>
</div>
</div>
<p>We can get the numerator degrees of freedom (<span class="math inline">k=2</span>) and denominator degrees of freedom (<span class="math inline">n-k-1=247</span>) from the output of <code>summary(m2)$fstatistic</code> above, or else from the last line of the summary output. - Because the test statistic is greater than the critical value we reject <span class="math inline">H_0</span> and conclude that the model is useful.</p>
</section>
<section id="question-13" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-13">Question 13</h4>
<p>Compare the adjusted R-squared between this model and the model in the previous block of questions (with only <code>pop_growth</code> as an independent variable). Choose the answer below which best describes how we should use this information to build our model:</p>
<ul>
<li>The adjusted R-squared for the model including <code>pop_growth_sq</code> is larger. Therefore the model excluding <code>pop_growth_sq</code> is preferred.</li>
<li>The adjusted R-squared for the model including <code>pop_growth_sq</code> is larger. Therefore the model including <code>pop_growth_sq</code> is preferred.</li>
<li>The adjusted R-squared for the model including <code>pop_growth_sq</code> is smaller. Therefore the model excluding <code>pop_growth_sq</code> is preferred.</li>
<li>The adjusted R-squared for the model including <code>pop_growth_sq</code> is smaller. Therefore the model including <code>pop_growth_sq</code> is preferred.</li>
</ul>
<p><strong>Answer:</strong> - The adjusted R-squared for the model including <code>pop_growth_sq</code> is smaller. Therefore the model excluding <code>pop_growth_sq</code> is preferred.</p>
<p><em>Explanation:</em> The adjusted <span class="math inline">R^2</span>s can be seen from the default <code>summary()</code> outputs to the right of the ordinary <span class="math inline">R^2</span>. We can see that it is smaller in the model with <code>pop_growth_sq</code> (0.0881 vs 0.0891), despite it having an extra variable. Although not necessary to do this question, we could extract both adjusted <span class="math inline">R^2</span>s to see them next to each other with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)<span class="sc">$</span>adj.r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08913119</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)<span class="sc">$</span>adj.r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08815336</code></pre>
</div>
</div>
<p>Because of the decrease in adjusted <span class="math inline">R^2</span> we prefer the simpler model with only <code>pop_growth</code> as it has a higher adjusted <span class="math inline">R^2</span>.</p>
</section>
</section>
<section id="model-3" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-3">Model 3</h2>
<p>Create a variable called <code>randstad</code> that is <code>TRUE</code> if the province is either Noord-Holland, Zuid-Holland or Utrecht and is <code>FALSE</code> otherwise.</p>
<p>The mean of this variable should equal 0.392.</p>
<p>We can create this variable two different ways. One is with the logical OR operator:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>randstad <span class="ot">&lt;-</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>province <span class="sc">==</span> <span class="st">"Noord-Holland"</span> <span class="sc">|</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>province <span class="sc">==</span> <span class="st">"Zuid-Holland"</span> <span class="sc">|</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>province <span class="sc">==</span> <span class="st">"Utrecht"</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>randstad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.392</code></pre>
</div>
</div>
<p>We can see that the mean matches the question. An alternative way is to use the <code>%in%</code> operator:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>randstad_provs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Noord-Holland"</span>, <span class="st">"Zuid-Holland"</span>, <span class="st">"Utrecht"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>randstad <span class="ot">&lt;-</span> df<span class="sc">$</span>province <span class="sc">%in%</span> randstad_provs</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>randstad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.392</code></pre>
</div>
</div>
<p>The mean also matches the question.</p>
<section id="question-14" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-14">Question 14</h4>
<p>What is difference between:</p>
<ol type="1">
<li>The mean gemeente average house price <em>inside</em> the Randstad, and</li>
<li>The mean gemeente average house price <em>outside</em> the Randstad?</li>
</ol>
<p>Write your answer in euros.</p>
<p><strong>Answer:</strong> 105,475 euros.</p>
<p><em>Explanation:</em></p>
<p>We can estimate a model with the dummy variable <code>randstad</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(house_price <span class="sc">~</span> randstad, <span class="at">data =</span> df)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = house_price ~ randstad, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-234.21  -70.72  -18.63   44.02  613.99 

Coefficients:
             Estimate Std. Error t value         Pr(&gt;|t|)    
(Intercept)   399.430      9.161  43.602          &lt; 2e-16 ***
randstadTRUE  105.475     14.631   7.209 0.00000000000679 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 112.9 on 248 degrees of freedom
Multiple R-squared:  0.1732,    Adjusted R-squared:  0.1699 
F-statistic: 51.97 on 1 and 248 DF,  p-value: 0.00000000000679</code></pre>
</div>
</div>
<p>The model is: <span class="math display">\mathbb{E}[Y_i|x_i]=\beta_0+\beta_1 x_i</span> The mean house price inside the Randstad is: <span class="math display">\mathbb{E}[Y_i|x_i=1]=\beta_0+\beta_1</span></p>
<p>The mean house price outside the Randstad is: <span class="math display">\mathbb{E}[Y_i|x_i=0]=\beta_0</span> The difference is <span class="math inline">\beta_1</span>. Thus <span class="math inline">b_1</span> from this model estimates this difference in means. We multiply by 1,000 then to convert to euros.</p>
</section>
</section>
<section id="model-4" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-4">Model 4</h2>
<p>Estimate a model explaining <code>house_price</code> with the following 3 variables:</p>
<ol type="1">
<li><code>pop_growth</code></li>
<li><code>randstad</code></li>
<li>The interaction between <code>pop_growth</code> and <code>randstad</code></li>
</ol>
<p>Your estimated regression intercept should be 346.65.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(house_price <span class="sc">~</span> pop_growth <span class="sc">*</span> randstad, <span class="at">data =</span> df)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = house_price ~ pop_growth * randstad, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-220.08  -64.27  -16.90   44.11  620.16 

Coefficients:
                        Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept)              346.652     14.727  23.538       &lt; 2e-16 ***
pop_growth                16.496      3.689   4.472 0.00001184014 ***
randstadTRUE             137.578     23.178   5.936 0.00000000989 ***
pop_growth:randstadTRUE  -11.817      4.883  -2.420        0.0163 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 108.6 on 246 degrees of freedom
Multiple R-squared:  0.2415,    Adjusted R-squared:  0.2322 
F-statistic: 26.11 on 3 and 246 DF,  p-value: 0.00000000000001072</code></pre>
</div>
</div>
<section id="question-15" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-15">Question 15</h4>
<p>For gemeentes with zero population growth, the gemeente average house price in the Randstad is how much more larger?</p>
<p>Write your answer in euros.</p>
<p><strong>Answer:</strong> 137,578.20</p>
<p><em>Explanation:</em> The model is: <span class="math display">\mathbb{E}[Y_i|x_{i1},x_{i2}]=\beta_0+\beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i1} x_{i2}</span> When population growth is zero, the model becomes: <span class="math display">\mathbb{E}[Y_i|x_{i1}=0,x_{i2}]=\beta_0+\beta_1 \times 0 + \beta_2 x_{i2} + \beta_3 \times 0\times x_{i2}=\beta_0+\beta_2 x_{i2}</span> Inside the Randstad, the average house price is (when population growth is zero): <span class="math display">\mathbb{E}[Y_i|x_{i1}=0,x_{i2}=1]=\beta_0+\beta_2 </span> Outside the Randstad, the average house price is (when population growth is zero): <span class="math display">\mathbb{E}[Y_i|x_{i1}=0,x_{i2}=0]=\beta_2 </span> Thus the difference <span class="math inline">\beta_2</span> is the difference in average house prices between the Randstad and outside the Randstad when population growth is zero. The dependent variable is measured in thousands of euros so we multiply <span class="math inline">b_2</span> by 1,000 to convert it to euros. We can do this manually, or else using R with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m4)[<span class="dv">3</span>] <span class="sc">*</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>randstadTRUE 
    137578.2 </code></pre>
</div>
</div>
</section>
<section id="question-16" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-16">Question 16</h4>
<p>In the Randstad, a 1 percentage point higher population growth rate on average leads to how much more expensive a house?</p>
<p>Write your answer in euros.</p>
<p><strong>Answer:</strong> 4,679.24</p>
<p><em>Explanation:</em> The model is: <span class="math display">\mathbb{E}[Y_i|x_{i1},x_{i2}]=\beta_0+\beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i1} x_{i2}</span> Inside the Randstad, the model is: <span class="math display">\mathbb{E}[Y_i|x_{i1},x_{i2}=1]=\beta_0+\beta_1 x_{i1} + \beta_2 \times 1 + \beta_3 x_{i1}\times 1=\beta_0+\beta_2 +\left(\beta_1 + \beta_3\right)x_{i1}</span> Increasing population growth by 1 percentage point: <span class="math display">
\mathbb{E}[Y_i|x_{i1}+1,x_{i2}=1]=
\beta_0+\beta_2 +\left(\beta_1 + \beta_3\right)\left(x_{i1}+1\right)=
\beta_0+\beta_2 +\left(\beta_1 + \beta_3\right)x_{i1} + \beta_1+\beta_3=
</span> Taking differences: <span class="math display">
\mathbb{E}[Y_i|x_{i1}+1,x_{i2}=1]-
\mathbb{E}[Y_i|x_{i1},x_{i2}=1]=\beta_1+\beta_3
</span> Thus <span class="math inline">\beta_1+\beta_3</span> measures the impact of a one percentage point increase in the population growth on the house price in the Randstad. Because house prices are measured in thousands, we multiply <span class="math inline">b_1+b_3</span> by 1,000 to convert to euros. We can do this manually or else in R with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">coef</span>(m4)[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">coef</span>(m4)[<span class="dv">4</span>]) <span class="sc">*</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pop_growth 
  4679.241 </code></pre>
</div>
</div>
</section>
<section id="question-17" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-17">Question 17</h4>
<p>Use your model to predict the average house price in a single gemeente in the Randstad with a population growth of 4%.</p>
<p>Also calculate an interval which contains the actual average house price with 90% probability.</p>
<p>Write your answers in euros.</p>
<ul>
<li>Prediction: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Interval lower bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Interval upper bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
</ul>
<p><strong>Answer:</strong></p>
<p>We obtain the prediction and prediction interval with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pop_growth =</span> <span class="dv">4</span>, <span class="at">randstad =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m4, df_p, <span class="at">interval =</span> <span class="st">"predict"</span>, <span class="at">level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 502.9475 322.6866 683.2083</code></pre>
</div>
</div>
<p>We then multiply each by 1,000 to convert to euros:</p>
<ul>
<li>Prediction: 502,947.50</li>
<li>Interval lower bound: 322,686.60</li>
<li>Interval upper bound: 683,208.30</li>
</ul>
</section>
</section>
<section id="model-5" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-5">Model 5</h2>
<p>Create a variable called <code>gelderland</code> which is <code>TRUE</code> if the gemeente is in Gelderland and is <code>FALSE</code> otherwise. Similarly, create a variable called <code>limburg</code> which is <code>TRUE</code> if the gemeente is in Limburg and is <code>FALSE</code> otherwise.</p>
<p>Use these to estimate a model explaining <code>house_price</code> with the following 4 variables:</p>
<ol type="1">
<li><code>pop_growth</code></li>
<li><code>randstad</code></li>
<li><code>gelderland</code>.</li>
<li><code>limburg</code>.</li>
</ol>
<p>Your estimated regression intercept should be 371.767.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>gelderland <span class="ot">&lt;-</span> df<span class="sc">$</span>province <span class="sc">==</span> <span class="st">"Gelderland"</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>limburg <span class="ot">&lt;-</span> df<span class="sc">$</span>province <span class="sc">==</span> <span class="st">"Limburg"</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(house_price <span class="sc">~</span> pop_growth <span class="sc">+</span> randstad <span class="sc">+</span> gelderland <span class="sc">+</span> limburg, <span class="at">data =</span> df)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = house_price ~ pop_growth + randstad + gelderland + 
    limburg, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-210.87  -63.74  -14.83   41.07  625.24 

Coefficients:
               Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept)     371.767     14.086  26.394       &lt; 2e-16 ***
pop_growth        8.530      2.488   3.429      0.000711 ***
randstadTRUE     95.449     15.859   6.019 0.00000000638 ***
gelderlandTRUE   28.884     21.541   1.341      0.181208    
limburgTRUE     -43.383     26.352  -1.646      0.100986    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 108.9 on 245 degrees of freedom
Multiple R-squared:  0.2411,    Adjusted R-squared:  0.2287 
F-statistic: 19.46 on 4 and 245 DF,  p-value: 0.00000000000006416</code></pre>
</div>
</div>
<section id="question-18" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-18">Question 18</h4>
<p>Choose the answer below which best describes the interpretation of the estimated coefficient on <code>gelderland</code>:</p>
<ul>
<li>Holding the population growth fixed, the average house price in Gelderland is €28,884 more than the average house price in <em>Drenthe, Flevoland, Friesland, Groningen, Noord-Brabant, Overijssel, and Zeeland.</em></li>
<li>Holding the population growth fixed, the average house price in Gelderland is €28,884 more than the average house price in the <em>Randstad and Limburg.</em></li>
<li>If the population growth is 8.53%, the average house price in Gelderland is €28,884 more than the average house price in <em>Drenthe, Flevoland, Friesland, Groningen, Noord-Brabant, Overijssel, and Zeeland.</em></li>
<li>If the population growth is 8.53%, the average house price in Gelderland is €28,884 more than the average house price in the <em>Randstad and Limburg.</em></li>
</ul>
<p><strong>Answer:</strong></p>
<p>Holding the population growth fixed, the average house price in Gelderland is €28,884 more than the average house price in Drenthe, Flevoland, Friesland, Groningen, Noord-Brabant, Overijssel, and Zeeland.</p>
<p><em>Explanation:</em> The Randstad (Noord-Holland, Zuid-Holland and Utrecht), Gelderland and Limburg are included provinces in the model. This means that the remaining provinces (Drenthe, Flevoland, Friesland, Groningen, Noord-Brabant, Overijssel, and Zeeland) form a collective <em>base category</em>. Each of the estimated province coefficients are therefore compared to these. Thus the coefficient in front of <code>gelderland</code> estimates the difference in average house prices between <code>gelderland</code> and these base provinces holding the population growth fixed.</p>
<p>To see this more clearly, we can write down the model:</p>
<p><span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2},x_{i3},x_{i4}]=
\beta_0+ \beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i3} + \beta_4 x_{i4}
</span> For gemeentes in Gelderland, we know that <span class="math inline">x_{i2}=x_{i4}=0</span> (you can’t be in Gelderland and another province). The model for Gelderland is then: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}=0,x_{i3}=1,x_{i4}=0]=
\beta_0+ \beta_1 x_{i1} + \beta_3
</span> For gemeentes in the base category (Drenthe, Flevoland, Friesland, Groningen, Noord-Brabant, Overijssel, and Zeeland), we have <span class="math inline">x_{i2}=x_{i3}=x_{i4}=0</span> because they cana’t be in the Randstad, Gelderland or Limburg as well. The model for these provinces is:</p>
<p><span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}=0,x_{i3}=0,x_{i4}=0]=
\beta_0+ \beta_1 x_{i1}
</span> Taking differences:</p>
<p><span class="math display">
    \mathbb{E}[Y_i|x_{i1},x_{i2}=0,x_{i3}=1,x_{i4}=0]=
\mathbb{E}[Y_i|x_{i1},x_{i2}=0,x_{i3}=0,x_{i4}=0]=\beta_3
</span> Thus <span class="math inline">\beta_3</span> is the difference in average house prices between Gelderland and these base provinces for a given population growth.</p>
</section>
<section id="question-19" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-19">Question 19</h4>
<p>We want to test for the joint usefulness of the variables <code>gelderland</code> and <code>limburg</code>, which are variables 3 and 4 in the model. Use a 5% significance level.</p>
<p>Choose one of the options in <em>italics</em> and fill in the blanks.</p>
<ul>
<li>The null hypothesis is that <em>all/at least one/none</em> of <span class="math inline">\beta_j</span> <span class="math inline">\rule{1cm}{0.15mm}</span> <span class="math inline">\rule{1cm}{0.15mm}</span> for <span class="math inline">j=\rule{1cm}{0.15mm}</span>.</li>
<li>The alternative hypothesis is that <em>all/at least one/none</em> of <span class="math inline">\beta_j</span> <span class="math inline">\rule{1cm}{0.15mm}</span> <span class="math inline">\rule{1cm}{0.15mm}</span> for the same <span class="math inline">j</span>.</li>
</ul>
<p>The test statistic is of the form: <span class="math display">
\frac{\frac{a - SSE_c}{k-g}}{\frac{SSE_c}{n-k-1}}
</span></p>
<p>What is the value of <span class="math inline">a</span> in the test? <span class="math inline">\rule{1cm}{0.15mm}</span></p>
<p>What is the value of the test statistic? <span class="math inline">\rule{1cm}{0.15mm}</span></p>
<p>What is the critical value? <span class="math inline">\rule{1cm}{0.15mm}</span></p>
<p>Which of the 4 options below is the correct conclusion from the test?</p>
<ul>
<li>Reject H0. The variables are useful additions to the model.</li>
<li>Reject H0. The variables are not useful additions to the model.</li>
<li>Don’t reject H0. The variables are useful additions to the model.</li>
<li>Don’t reject H0. The variables are not useful additions to the model.</li>
</ul>
<p><strong>Answer:</strong></p>
<p>We can perform the partial <span class="math inline">F</span> test by first estimating the reduced model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>m5r <span class="ot">&lt;-</span> <span class="fu">lm</span>(house_price <span class="sc">~</span> pop_growth <span class="sc">+</span> randstad, <span class="at">data =</span> df)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m5r, m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: house_price ~ pop_growth + randstad
Model 2: house_price ~ pop_growth + randstad + gelderland + limburg
  Res.Df     RSS Df Sum of Sq      F  Pr(&gt;F)  
1    247 2971312                              
2    245 2903751  2     67561 2.8502 0.05975 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This also provides us with the numerator and denominator degrees of freedom required to compute the critical value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">2</span>, <span class="dv">245</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.032663</code></pre>
</div>
</div>
<p>We now have everything to answer the questions:</p>
<ul>
<li><span class="math inline">H_0</span>: All <span class="math inline">\beta_j=0</span> for <span class="math inline">j=3,4</span>.</li>
<li><span class="math inline">H_1</span>: At least one <span class="math inline">\beta_j\neq 0</span> for the same <span class="math inline">j</span>.</li>
<li><span class="math inline">a</span> is the <span class="math inline">SSE_r</span>, the sum of squared errors for the reduced model. We can find the value of this from the <code>anova()</code> output: 2971312.</li>
<li>Value of the test statistic: 2.8502.</li>
<li>Critical value: 3.026153.</li>
<li>Conclusion: Don’t reject H0. The variables are not useful additions to the model (<em>reason:</em> test statistic smaller than critical value).</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>