<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics 2 2025/26 Resit Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="2025-resit-solutions_files/libs/clipboard/clipboard.min.js"></script>
<script src="2025-resit-solutions_files/libs/quarto-html/quarto.js"></script>
<script src="2025-resit-solutions_files/libs/quarto-html/popper.min.js"></script>
<script src="2025-resit-solutions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2025-resit-solutions_files/libs/quarto-html/anchor.min.js"></script>
<link href="2025-resit-solutions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2025-resit-solutions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2025-resit-solutions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2025-resit-solutions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2025-resit-solutions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="2025-resit-solutions.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistics 2 2025/26 Resit Solutions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>The human resources (HR) department in your large firm has collected data on employee satisfaction from a random sample of <span class="math inline">n=14999</span> employees. They are interested in the factors driving this. They are asking for your help to perform the statistical analysis.</p>
<p>Here is a link to download the dataset: <a href="https://walshc.github.io/stats2/employee-satisfaction.csv"><code>employee-satisfaction.csv</code></a>.</p>
<p>The definitions of all the variables are as follows:</p>
<ul>
<li><code>y</code>: Employee satisfaction score (between 0 and 1) where a higher number means more satisfied.</li>
<li><code>num_projects</code>: The number of projects the employee has worked on in the last year.</li>
<li><code>salary</code>: A categorical variable indicating the employee’s salary (<code>"high"</code>, <code>"medium"</code> or <code>"low"</code>).</li>
<li><code>promotion</code>: A dummy variable that equals 1 if the employee received a promotion in the last 5 years and 0 otherwise.</li>
</ul>
<section id="question-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-1">Question 1</h4>
<p>What is the sample covariance between <code>y</code> and <code>num_projects</code>?</p>
<p><strong>Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"employee-satisfaction.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(df<span class="sc">$</span>y, df<span class="sc">$</span>num_projects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.04381449</code></pre>
</div>
</div>
</section>
</section>
<section id="model-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-1">Model 1</h2>
<p>The HR department want to know how promotions affect employee satisfaction. Estimate a linear regression model with <code>y</code> as the dependent variable and <code>promotion</code> as the independent variable.</p>
<p>If you estimated the model correctly, you should have an estimated intercept of 0.611895.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> promotion, <span class="at">data =</span> df)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ promotion, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.5460 -0.1719  0.0281  0.2081  0.3881 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.611895   0.002051 298.273  &lt; 2e-16 ***
promotion   0.044124   0.014067   3.137  0.00171 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2486 on 14997 degrees of freedom
Multiple R-squared:  0.0006556, Adjusted R-squared:  0.000589 
F-statistic: 9.839 on 1 and 14997 DF,  p-value: 0.001712</code></pre>
</div>
</div>
<section id="question-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-2">Question 2</h4>
<p>What is the sample regression slope?</p>
<p><strong>Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> promotion 
0.04412371 </code></pre>
</div>
</div>
</section>
<section id="question-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-3">Question 3</h4>
<p>Provide a 99% confidence interval for the sample regression slope.</p>
<ul>
<li>Lower bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Upper bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
</ul>
<p><strong>Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1, <span class="at">parm =</span> <span class="st">"promotion"</span>, <span class="at">level =</span> <span class="fl">0.99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                0.5 %     99.5 %
promotion 0.007885075 0.08036235</code></pre>
</div>
</div>
</section>
<section id="question-4" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-4">Question 4</h4>
<p>According to the estimated model, what is the average employee satisfaction of employees that received a promotion in the last 5 years.</p>
<p><strong>Answer:</strong></p>
<p>The model is: <span class="math display">
\mathbb{E}[Y_i|promotion_i]=\beta_0+\beta_1 x_i
</span> For employees that received a promotion, this is: <span class="math display">
\mathbb{E}[Y_i|promotion_i=1]=\beta_0+\beta_1
</span> Therefore we just need to add the estimate of the intercept and the slope together:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">coef</span>(m1)[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6560188</code></pre>
</div>
</div>
<p>We can check this by calculating the average manually:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>y[df<span class="sc">$</span>promotion <span class="sc">==</span> <span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6560188</code></pre>
</div>
</div>
<p>Which gives us the same answer!</p>
</section>
<section id="question-5" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-5">Question 5</h4>
<p>Test the following claim at the 5% level:</p>
<p>“Employees that received a promotion in the last 5 years on average have a higher satisfaction level of <em>more than</em> 0.02 compared to employees that did not receive a promotion in the last 5 years.”</p>
<p>Perform this test by answering the questions below.</p>
<ul>
<li><p>What is the null hypothesis? <span class="math inline">\beta_1</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in a value in the blank).</p></li>
<li><p>What is the alternative hypothesis? <span class="math inline">\beta_1</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in a value in the blank).</p></li>
<li><p>Under the null hypothesis, the test statistic <span class="math inline">T=(B_1-b)/S_{B_1}</span>, where <span class="math inline">b</span> is the hinge, follows a <span class="math inline">t</span> distribution with how many degrees of freedom? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is the associated <span class="math inline">p</span>-value? <span class="math inline">\underline{\hspace{20mm}}</span></p></li>
<li><p>What is your conclusion? Choose an option below:</p>
<ul>
<li>Reject H0: There is sufficient evidence for the claim.</li>
<li>Reject H0: There is not sufficient evidence for the claim.</li>
<li>Don’t reject H0: There is sufficient evidence for the claim.</li>
<li>Don’t reject H0: There is not sufficient evidence for the claim.</li>
</ul></li>
</ul>
<p><strong>Answer:</strong></p>
<p>According to our model estimates, a promotion leads to an increase in satisfaction of 0.0441 on average. The question is asking if this estimate is precise enough to say that a promotion leads to an average increase of more than 0.02 in the population. Therefore the claim is that <span class="math inline">\beta_1 &gt; 0.02</span>, which is our alternative hypothesis.</p>
<ul>
<li>Null hypothesis: <span class="math inline">\beta_1 \leq 0.02</span>.</li>
<li>Alternative hypothesis: <span class="math inline">\beta_1 &gt;0.02</span>.</li>
<li>Degrees of freedom: 14997 (can be read from model summary output). Can also be found by calculating <span class="math inline">n-k-1=14999-1-1=14997</span>.</li>
<li>Value of the test statistic:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m1))[<span class="dv">2</span>, <span class="dv">1</span>]</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>s_b_1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m1))[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>(t <span class="ot">&lt;-</span> (b_1 <span class="sc">-</span> <span class="fl">0.02</span>) <span class="sc">/</span> s_b_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.714923</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">p</span>-value: This is an upper-tail test so we calculate this with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(t, <span class="dv">14997</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04318999</code></pre>
</div>
</div>
<ul>
<li>Conclusion: The <span class="math inline">p</span>-value is less than the significance level (0.05) so we reject H0. Therefore the correct option is: “Reject H0: There is sufficient evidence for the claim.”</li>
</ul>
</section>
</section>
<section id="model-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-2">Model 2</h2>
<p>The HR department is interested in the relationship between employee satisfaction and work pressure. They have the following theory:</p>
<ul>
<li>Too much work increases stress and is bad for employee satisfaction.</li>
<li>Too little work makes work boring and is also bad for employee satisfaction.</li>
<li>There is an optimal amount of work in between these extremes that is best for employee satisfaction.</li>
</ul>
<p>To test this theory you estimate a regression model with <code>y</code> as the dependent variable and the following two independent variables:</p>
<ul>
<li><code>num_projects</code></li>
<li>The square of <code>num_projects</code>.</li>
</ul>
<p>Note: it is possible to add the number of projects squared to your model by adding <code>I(num_projects^2)</code> to your model formula in the <code>lm()</code> function.</p>
<p>If you estimated the model correctly, you should have an estimated intercept of -0.3376667.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> num_projects <span class="sc">+</span> <span class="fu">I</span>(num_projects<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> df)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ num_projects + I(num_projects^2), data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.61118 -0.12118 -0.00118  0.15459  0.67728 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -0.3376667  0.0148693  -22.71   &lt;2e-16 ***
num_projects       0.5566323  0.0077484   71.84   &lt;2e-16 ***
I(num_projects^2) -0.0729804  0.0009504  -76.79   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2085 on 14996 degrees of freedom
Multiple R-squared:  0.2969,    Adjusted R-squared:  0.2968 
F-statistic:  3166 on 2 and 14996 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="question-6" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-6">Question 6</h4>
<p>Use the estimated model to predict the employee satisfaction of an employee with 3 projects.</p>
<p>Also use the model to provide the lower and upper bound of a 95% confidence interval for the mean employee satisfaction for employees with 3 projects.</p>
<ul>
<li>Predicted employee satisfaction: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Confidence interval lower bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>Confidence interval upper bound: <span class="math inline">\underline{\hspace{20mm}}</span></li>
</ul>
<p><strong>Answer:</strong> The question is asking for a confidence interval for the mean employee satisfaction given a value of the independent variables. Therefore we use the <code>interval = "confidence"</code> option in the <code>predict()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">num_projects =</span> <span class="dv">3</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m2, df_p, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        fit       lwr       upr
1 0.6754064 0.6712987 0.6795142</code></pre>
</div>
</div>
<p>Note: because we are using <code>I(num_projects^2)</code> in our model formula, we can create a dataframe with only the <code>num_projects</code> variable. If instead you estimated the model using a <code>num_projects_sq</code> variable that you created, you will need to also add a value for that variable (i.e.&nbsp;<code>data.frame(num_projects = 3, num_projects_sq = 9)</code>.</p>
</section>
<section id="question-7" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-7">Question 7</h4>
<p>Employees in the data work on between 2 and 7 projects. According to the estimated model, what number of projects is on average best for employee satisfaction? The answer must be a whole number.</p>
<p><strong>Answer:</strong> There are several ways to do this question. One way is to predict the employee satisfaction for each of 2-7 projects. This could be done one-by-one in a similar way to the previous question. For example, we can try 2 projects:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">num_projects =</span> <span class="dv">2</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m2, df_p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.4836762 </code></pre>
</div>
</div>
<p>And 4 projects:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">num_projects =</span> <span class="dv">4</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m2, df_p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.7211757 </code></pre>
</div>
</div>
<p>We can continue this until we have the predicted satisfaction for all number of projects 2-7, and report the number of projects that gives the highest predicted satisfaction.</p>
<p>But a faster way would be to create a data frame with the sequence 2-7 and use that to predict the number of projects:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">num_projects =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df_p<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">predict</span>(m2, df_p)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>df_p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  num_projects           y
1            2  0.48367622
2            3  0.67540641
3            4  0.72117575
4            5  0.62098423
5            6  0.37483187
6            7 -0.01728134</code></pre>
</div>
</div>
<p>We can see that 4 projects gives the highest predicted satisfaction.</p>
<p>We can also plot these results to see it more clearly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_p, <span class="fu">aes</span>(num_projects, y)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-resit-solutions_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Another approach would use calculus. However, because the optimal number of projects needs to be a whole number, this approach is made a bit more complicated and is not what I recommend to do. Nevertheless, if you are interested, I provide the workings here.</p>
<p>The model is: <span class="math display">
\mathbb{E}[Y_i|num\_projects_i]=\beta_0+\beta_1num\_projects_i+\beta_2num\_projects_i^2
</span> Taking derivatives: <span class="math display">
\frac{\partial \mathbb{E}[Y_i|num\_projects_i]}{\partial num\_projects_i}=\beta_1 + 2\beta_2num\_projects_i
</span> The function <span class="math inline">\mathbb{E}[Y_i|num\_projects_i]</span> is at an extreme point when <span class="math inline">\frac{\partial \mathbb{E}[Y_i|num\_projects_i]}{\partial num\_projects_i}=0</span>. This happens at: <span class="math inline">\beta_1 + 2\beta_2num\_projects_i=0</span>. Solving for <span class="math inline">num\_projects_i</span> we get <span class="math inline">num\_projects_i=-\frac{\beta_1}{2\beta_2}</span>. Calculating this in our case gives:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span> <span class="fu">coef</span>(m2)[<span class="dv">2</span>] <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> <span class="fu">coef</span>(m2)[<span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>num_projects 
    3.813573 </code></pre>
</div>
</div>
<p>Therefore 3.81 projects is an extreme point. The second-order derivative is <span class="math inline">2\beta_2</span>. Because <span class="math inline">b_2&lt;0</span>, this means the second-order derivative is negative which means this extreme point is a maximum.</p>
<p>This means the ideal number of projects is 3.81. But because we can only work on a whole number of projects, we need to calculate which of 3 or 4 gives a higher satisfaction.</p>
<p>Our estimate of <span class="math inline">\mathbb{E}[Y_i|num\_projects_i=3]</span> is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(m2)[<span class="dv">2</span>] <span class="sc">*</span> <span class="dv">3</span> <span class="sc">+</span> <span class="fu">coef</span>(m2)[<span class="dv">3</span>] <span class="sc">*</span> <span class="dv">3</span><span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.6754064 </code></pre>
</div>
</div>
<p>Our estimate of <span class="math inline">\mathbb{E}[Y_i|num\_projects_i=4]</span> is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(m2)[<span class="dv">2</span>] <span class="sc">*</span> <span class="dv">4</span> <span class="sc">+</span> <span class="fu">coef</span>(m2)[<span class="dv">3</span>] <span class="sc">*</span> <span class="dv">4</span><span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.7211757 </code></pre>
</div>
</div>
<p>Because <span class="math inline">0.7211757&gt; 0.6754064</span>, this shows that 4 is the optimal number of projects.</p>
</section>
<section id="question-8" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-8">Question 8</h4>
<p>Perform a formal test for heteroskedasticity by regressing the square of the residuals from your model on <code>num_projects</code> and the square of <code>num_projects</code> (the same explanatory variables as in the model).</p>
<p>Use a 5% significance level.</p>
<p>In this test, the alternative hypothesis is that the model exhibits which of the following:</p>
<ul>
<li>Homoskedasticity</li>
<li>Heteroskedasticity</li>
<li>Serial correlation</li>
<li>Serial uncorrelation</li>
</ul>
<p>What is the <span class="math inline">p</span>-value from this test? <span class="math inline">\underline{\hspace{20mm}}</span></p>
<p>What is the conclusion? Choose one of the answers below:</p>
<ul>
<li>The model exhibits homoskedasticity. Therefore the coefficients are not reliable.</li>
<li>The model exhibits homoskedasticity. Therefore the standard errors are not reliable.</li>
<li>The model exhibits heteroskedasticity. Therefore the coefficients are not reliable.</li>
<li>The model exhibits heteroskedasticity. Therefore the standard errors are not reliable.</li>
</ul>
<p><strong>Answer:</strong> The alternative hypothesis is heteroskedasticity. The <span class="math inline">p</span>-value from the test is the <span class="math inline">p</span>-value of the <span class="math inline">F</span>-test from the auxiliary regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>e2 <span class="ot">&lt;-</span> m2<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>aux <span class="ot">&lt;-</span> <span class="fu">lm</span>(e2 <span class="sc">~</span> num_projects <span class="sc">+</span> <span class="fu">I</span>(num_projects<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> df)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aux)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e2 ~ num_projects + I(num_projects^2), data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.06150 -0.03527 -0.01841  0.00953  0.39284 

Coefficients:
                    Estimate Std. Error t value           Pr(&gt;|t|)    
(Intercept)       -0.0064134  0.0043117  -1.487             0.1369    
num_projects       0.0173018  0.0022468   7.701 0.0000000000000144 ***
I(num_projects^2) -0.0009965  0.0002756  -3.616             0.0003 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.06046 on 14996 degrees of freedom
Multiple R-squared:  0.03557,   Adjusted R-squared:  0.03545 
F-statistic: 276.6 on 2 and 14996 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The <span class="math inline">p</span>-value is 0.000.</p>
<p>Because the <span class="math inline">p</span>-value is less than the significance level of 0.05, the conclusion is “The model exhibits heteroskedasticity. Therefore the standard errors are not reliable.”</p>
</section>
</section>
<section id="model-3" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-3">Model 3</h2>
<p>The HR department is also interested in how salary affects satisfaction. Regress employee satisfaction on the following 2 independent variables:</p>
<ul>
<li>A dummy variable for salary being <code>"low"</code>.</li>
<li>A dummy variable for salary being <code>"medium"</code>.</li>
</ul>
<p>Note that by using the <code>salary</code> variable in your model formula <em>as is</em> the <code>"high"</code> salary value will automatically be chosen as the base category. Therefore you can use the <code>salary</code> variable in your formula and do not need to make any adjustments to the levels.</p>
<p>If you estimated the model correctly, your estimated regression intercept should equal 0.637470.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> salary, <span class="at">data =</span> df)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ salary, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.54747 -0.17182  0.02925  0.19925  0.39925 

Coefficients:
              Estimate Std. Error t value   Pr(&gt;|t|)    
(Intercept)   0.637470   0.007061  90.284    &lt; 2e-16 ***
salarylow    -0.036717   0.007634  -4.809 0.00000153 ***
salarymedium -0.015653   0.007709  -2.031     0.0423 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2483 on 14996 degrees of freedom
Multiple R-squared:  0.002522,  Adjusted R-squared:  0.002389 
F-statistic: 18.96 on 2 and 14996 DF,  p-value: 0.000000005967</code></pre>
</div>
</div>
<section id="question-9" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-9">Question 9</h4>
<p>Define the following:</p>
<ul>
<li><span class="math inline">\bar{y}_{low}</span>: The average employee satisfaction of low-salaried workers.</li>
<li><span class="math inline">\bar{y}_{medium}</span>: The average employee satisfaction of medium-salaried workers.</li>
<li><span class="math inline">\bar{y}_{high}</span>: The average employee satisfaction of high-salaried workers.</li>
</ul>
<p>The question below tests your ability to interpret the coefficients from the estimated model. Fill in the blanks below.</p>
<p>According to the estimated model, the average employee satisfaction of high-salaried workers is <span class="math inline">\underline{\hspace{20mm}}</span> (value of <span class="math inline">\bar{y}_{high}</span>).</p>
<p>According to the estimated model, the difference in average employee satisfaction between low- and high-salaried workers is <span class="math inline">\underline{\hspace{20mm}}</span> (value of <span class="math inline">\bar{y}_{low}-\bar{y}_{high}</span>).</p>
<p>According to the estimated model, the difference in average employee satisfaction between low- and medium-salaried workers is <span class="math inline">\underline{\hspace{20mm}}</span> (value of <span class="math inline">\bar{y}_{low}-\bar{y}_{medium}</span>).</p>
<p><strong>Answer:</strong> High-salaried workers are the base category. Therefore we just need to report the intercept:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m3)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.6374697 </code></pre>
</div>
</div>
<p>The difference between low- and high-salaried workers is measured by the coefficient on <code>"low"</code>. The reason for this is because: <span class="math display">
\mathbb{E}[Y_i|salary=low]-\mathbb{E}[Y_i|salary=high]=\left(\beta_0 + \beta_1\right)-\beta_0 =\beta_1
</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m3)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  salarylow 
-0.03671654 </code></pre>
</div>
</div>
<p>The difference between low- and medium-salaried workers is measured by the difference in coefficients between <code>"low"</code> and <code>"medium"</code>. The reason for this is because: <span class="math display">
\mathbb{E}[Y_i|salary=low]-\mathbb{E}[Y_i|salary=medium]=\left(\beta_0 + \beta_1\right)-\left(\beta_0 + \beta_2\right)=\beta_1-\beta_2
</span> This is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m3)[<span class="dv">2</span>]<span class="sc">-</span><span class="fu">coef</span>(m3)[<span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  salarylow 
-0.02106349 </code></pre>
</div>
</div>
</section>
<section id="question-10" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-10">Question 10</h4>
<p>Perform an appropriate hypothesis test to test the usefulness of the model. Use a 5% significance level.</p>
<ul>
<li>The null hypothesis is that <em>at least one/all/none</em> (choose one) of <span class="math inline">\beta_j</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for <span class="math inline">j=</span> <span class="math inline">\underline{\hspace{20mm}}</span> to <span class="math inline">\underline{\hspace{20mm}}</span> (choose one comparison operator and fill in values in the blank spaces).</li>
<li>The alternative hypothesis is that <em>at least one/all/none</em> (choose one) of <span class="math inline">\beta_j</span> <span class="math inline">&lt;/\leq/&gt;/\geq/=/\neq</span> <span class="math inline">\underline{\hspace{20mm}}</span> for the same <span class="math inline">j</span> (choose one comparison operator and fill in a value in in the blank space).</li>
<li>The formula for the test statistic is of the form: <span class="math display">
\frac{\frac{SST - SSE}{a}}{\frac{SSE}{n-k-1}}
</span> What is the value of <span class="math inline">a</span> in the estimated model? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the value of the test statistic? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is the critical value? <span class="math inline">\underline{\hspace{20mm}}</span></li>
<li>What is your conclusion? (choose one option below):
<ul>
<li><em>Reject</em> <span class="math inline">H_0</span>. The model is <em>useful</em>.</li>
<li><em>Reject</em> <span class="math inline">H_0</span>. The model is <em>useless</em>.</li>
<li><em>Don’t reject</em> <span class="math inline">H_0</span>. The model is <em>useful</em>.</li>
<li><em>Don’t reject</em> <span class="math inline">H_0</span>. The model is <em>useless</em>.</li>
</ul></li>
</ul>
<p><strong>Answer</strong>:</p>
<ul>
<li><span class="math inline">H_0</span>: All of <span class="math inline">\beta_j=0</span> for <span class="math inline">j=1</span> to <span class="math inline">2</span>.</li>
<li><span class="math inline">H_1</span>: At least one of <span class="math inline">\beta_j\neq 0</span> for the same <span class="math inline">j</span>.</li>
<li><span class="math inline">a</span> is replacing <span class="math inline">k</span> in the formula. This is 2 in this case.</li>
<li>The value of the test statistic can be read from the <code>summary()</code> output (18.96) or obtained directly with:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)<span class="sc">$</span>fstatistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     value      numdf      dendf 
   18.9609     2.0000 14996.0000 </code></pre>
</div>
</div>
<ul>
<li>The critical value is:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">2</span>, <span class="dv">14996</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.996331</code></pre>
</div>
</div>
<p>where the numerator and denominator degrees of freedom (2 and 14996) can be read from the last line of the <code>summary()</code> output.</p>
<ul>
<li>Conclusion: <em>Reject</em> <span class="math inline">H_0</span>. The model is <em>useful</em>.</li>
</ul>
</section>
</section>
<section id="model-4" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="model-4">Model 4</h2>
<p>Estimate a multiple linear regression model explaining employee satisfaction by:</p>
<ul>
<li>The <code>promotion</code> dummy.</li>
<li>The <code>"low"</code> salary dummy.</li>
<li>The <code>"medium"</code> salary dummy.</li>
</ul>
<p>As in Model 3, by using the <code>salary</code> variable as is the <code>"high"</code> salary will automatically be chosen as the base category.</p>
<p>If you estimated the model correctly, your estimated regression intercept should equal 0.635366.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> promotion <span class="sc">+</span> salary, <span class="at">data =</span> df)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ promotion + salary, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.54537 -0.17080  0.02957  0.19957  0.39957 

Coefficients:
              Estimate Std. Error t value   Pr(&gt;|t|)    
(Intercept)   0.635366   0.007107  89.398    &lt; 2e-16 ***
promotion     0.036145   0.014122   2.560     0.0105 *  
salarylow    -0.034939   0.007664  -4.559 0.00000519 ***
salarymedium -0.014564   0.007719  -1.887     0.0592 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2483 on 14995 degrees of freedom
Multiple R-squared:  0.002958,  Adjusted R-squared:  0.002759 
F-statistic: 14.83 on 3 and 14995 DF,  p-value: 0.000000001227</code></pre>
</div>
</div>
<section id="question-11" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-11">Question 11</h4>
<p>The estimated intercept 0.635366 is the average employee satisfaction among which subgroup?</p>
<ul>
<li>High-salary workers that received a promotion in the last 5 years.</li>
<li>High-salary workers that did not receive a promotion in the last 5 years.</li>
<li>Medium-salary workers that received a promotion in the last 5 years.</li>
<li>Medium-salary workers that did not receive a promotion in the last 5 years.</li>
<li>Low-salary workers that received a promotion in the last 5 years.</li>
<li>Low-salary workers that did not receive a promotion in the last 5 years.</li>
</ul>
<p><strong>Answer:</strong></p>
<p>The intercept gives an estimate of the mean value of the dependent variable when all independent variables are exactly equal to zero. When <code>promotion</code> is zero and <code>salary</code> is <code>"high"</code>, then the model is:</p>
<p><span class="math display">
\mathbb{E}[Y_i|promotion_i=0, salary_i=high]=\beta_0 + \beta_1 \times 0 + \beta_2\times 0 +\beta_3 \times 0=\beta_0
</span></p>
<p>Therefore the answer is: “High-salary workers that did not receive a promotion in the last 5 years.”</p>
</section>
<section id="question-12" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-12">Question 12</h4>
<p>Which variables are individually significant at the 1% level?</p>
<p><strong>Answer:</strong></p>
<p>All the variables with at least 2 <code>*</code>s in the summary output are significant at the 1% level. This means only <code>salarylow</code> is significant at the 1% level. The variable <code>promotion</code> has only 1 star and is only significant at the 5% level, not the 1% level. The variable <code>salarymedium</code> is only significant at the 10% level (which is indicated by the <code>.</code>).</p>
</section>
<section id="question-13" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-13">Question 13</h4>
<p>Test the joint usefulness of the salary variables, which are variables 2-3 in your the model. Use a 5% significance level.</p>
<p>Choose one of the options in <em>italics</em> and fill in the blanks.</p>
<ul>
<li>The null hypothesis is that <em>all/at least one/none</em> of <span class="math inline">\beta_j</span> <span class="math inline">\rule{1cm}{0.15mm}</span> <span class="math inline">\rule{1cm}{0.15mm}</span> for <span class="math inline">j</span> from <span class="math inline">\rule{1cm}{0.15mm}</span> to <span class="math inline">\rule{1cm}{0.15mm}</span>.</li>
<li>The alternative hypothesis is that <em>all/at least one/none</em> of <span class="math inline">\beta_j</span> <span class="math inline">\rule{1cm}{0.15mm}</span> <span class="math inline">\rule{1cm}{0.15mm}</span> for the same <span class="math inline">j</span>.</li>
</ul>
<p>The test statistic is of the form: <span class="math display">
\frac{\frac{SSE_r - SSE_c}{a}}{\frac{SSE_c}{n-k-1}}
</span></p>
<p>What is the value of <span class="math inline">a</span> in the test? <span class="math inline">\rule{1cm}{0.15mm}</span></p>
<p>What is the value of the test statistic? <span class="math inline">\rule{1cm}{0.15mm}</span></p>
<p>What is the critical value? <span class="math inline">\rule{1cm}{0.15mm}</span></p>
<p>Which of the 4 options below is the correct conclusion from the test?</p>
<ul>
<li>Reject H0. The variables are useful additions to the model.</li>
<li>Reject H0. The variables are not useful additions to the model.</li>
<li>Don’t reject H0. The variables are useful additions to the model.</li>
<li>Don’t reject H0. The variables are not useful additions to the model.</li>
</ul>
<p><strong>Answer:</strong></p>
<p>We can perform the partial <span class="math inline">F</span> test by using the <code>anova()</code> function with the reduced model (<code>promotion</code> only) and the complete model (<code>promotion</code> and <code>salary</code>). The reduced model is actually model 1 from earlier, so there is no need to estimate it again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1, m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ promotion
Model 2: y ~ promotion + salary
  Res.Df    RSS Df Sum of Sq      F        Pr(&gt;F)    
1  14997 926.53                                      
2  14995 924.39  2    2.1346 17.314 0.00000003087 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We now have everything to answer the questions:</p>
<ul>
<li><span class="math inline">H_0</span>: All <span class="math inline">\beta_j=0</span> for <span class="math inline">j</span> from 2 to 3.</li>
<li><span class="math inline">H_1</span>: At least one <span class="math inline">\beta_j\neq 0</span> for the same <span class="math inline">j</span>.</li>
<li><span class="math inline">a</span> is <span class="math inline">k-g</span>, the number of variables in the complete model minus the number of variables in the reduced model (or the number of variables we are testing). This is <span class="math inline">3-1=2</span>.</li>
<li>Value of the test statistic: 17.314</li>
<li>Critical value with <span class="math inline">k-g=2</span> numerator and <span class="math inline">n-k-1=14995</span> denominator degrees of freedom:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">2</span>, <span class="dv">14995</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.996331</code></pre>
</div>
</div>
<ul>
<li>Conclusion: Reject H0. The variables are useful additions to the model (<em>reason:</em> the test statistic 17.314 is larger than the critical value of 2.996).</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>