<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.52">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="tutorial4_files/libs/clipboard/clipboard.min.js"></script>
<script src="tutorial4_files/libs/quarto-html/quarto.js"></script>
<script src="tutorial4_files/libs/quarto-html/popper.min.js"></script>
<script src="tutorial4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="tutorial4_files/libs/quarto-html/anchor.min.js"></script>
<link href="tutorial4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="tutorial4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="tutorial4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="tutorial4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="tutorial4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a>
  <ul class="collapse">
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a></li>
  <li><a href="#exercise-5" id="toc-exercise-5" class="nav-link" data-scroll-target="#exercise-5">Exercise 5</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tutorial 4</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>In this tutorial we will study two datasets. The first dataset is the <a href="https://walshc.github.io/stats2/penguins.csv"><code>penguins.csv</code></a> dataset which featured on the resit exam from January 2022. This dataset is based on a dataset used in the Programming and Quantitative Skills course to learn about plotting. The data contain information from a random sample of 333 Antarctic penguins. The dataset contains 4 variables:</p>
<ul>
<li><code>flipper</code>: This is the penguin’s flipper length measured in mm (the penguin’s wing).</li>
<li><code>weight</code>: The penguin’s weight measured in grams</li>
<li><code>female</code>: A dummy variable that equals 1 if the penguin is female and 0 if it is male.</li>
<li><code>species</code>: A character variable indicating the penguin’s species. It is one of <code>"Adelie"</code>, <code>"Chinstrap"</code> or <code>"Gentoo"</code>.</li>
</ul>
<p>The second dataset is the <a href="https://walshc.github.io/stats2/ebill90.csv"><code>ebill90.csv</code></a> dataset from the resit exam in January 2019. It contains the monthly average household electricity bill in the USA from January 1991 to December 2000.</p>
<p>The variables are:</p>
<ul>
<li><code>year</code>: The year (as a numeric variable).</li>
<li><code>month</code>: The month (as an abbreviated character variable).</li>
<li><code>avg_bill</code>: The monthly average household electricity bill (in dollars).</li>
</ul>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<p>With the <a href="https://walshc.github.io/stats2/penguins.csv"><code>penguins.csv</code></a> dataset:</p>
<ol type="1">
<li>Estimate a regression explaining flipper length with weight, gender and their interaction. Is there evidence of any gender effect at the 5% level (that is, given a particular weight, does the flipper length differ by gender on average?). Use the critical value approach.</li>
<li>Estimate a regression explaining flipper length with weight, gender, the species dummies and the interactions of the species dummies with gender. Use adelie penguins as the base group. Test at the 5% level if the average flipper length of female adelie penguins is larger than the average flipper length of male adelie penguins of the same weight. Use the <span class="math inline">p</span>-value approach.</li>
</ol>
<p>With the <a href="https://walshc.github.io/stats2/ebill90.csv"><code>ebill90.csv</code></a> dataset, create a trend term (a variable that indicates the row number) and regress <code>avg_bill</code> on the trend and all month dummies except December (use December as your base category). If you estimated this model correctly your estimated intercept should be 137.21747. Use this model to answer the following questions:</p>
<ol start="3" type="1">
<li>In which month of the year is the average electricity bill largest? Does this make sense?</li>
<li>Use a suitable plot to visually check for independence of the residuals.</li>
<li>Perform a formal test for first-order autocorrelation of the residuals at the 5% level. Use the <span class="math inline">p</span>-value approach.</li>
</ol>
<p><em>Tip:</em> Use <code>df$month &lt;- factor(df$month, levels = unique(df$month))</code> to make the order of the levels be <code>"Jan"</code>, <code>"Feb"</code>, …, <code>"Nov"</code>, <code>"Dec"</code> instead of the month names alphabetically. Then use the <code>relevel()</code> function to change the base category to <code>"Dec"</code>.</p>
</section>
<section id="solutions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="solutions">Solutions</h2>
<section id="exercise-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-1">Exercise 1</h3>
<p>The model is: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}] = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i1} x_{i2}
</span> where <span class="math inline">Y_i</span> is flipper length, <span class="math inline">x_{i1}</span> is weight and <span class="math inline">x_{i2}</span> is the female dummy. For female penguins: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}=1] = \beta_0 + \beta_1 x_{i1} + \beta_2 + \beta_3 x_{i1}
</span> For male penguins: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}=0] = \beta_0 + \beta_1 x_{i1}
</span> For a fixed weight <span class="math inline">x_{i1}</span>, the difference is: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}=1]-
\mathbb{E}[Y_i|x_{i1},x_{i2}=0]= \beta_2 + \beta_3 x_{i1}
</span> If there is no gender effect whatsover, then both <span class="math inline">\beta_2=0</span> and <span class="math inline">\beta_3=0</span> and the expected flipper length given the penguin’s weight should be the same. That is to say, when <span class="math inline">\beta_2=\beta_3=0</span> we have <span class="math display">\mathbb{E}[Y_i|x_{i1},x_{i2}=1]=\mathbb{E}[Y_i|x_{i1},x_{i2}=0]</span> If there is a gender effect, then at least one of <span class="math inline">\beta_2\neq 0</span> or <span class="math inline">\beta_3\neq 0</span>.</p>
<p>So the null and alternative hypotheses are:</p>
<p><span class="math display">
\begin{split}
H_0:&amp;\beta_2=\beta_3=0 \\
H_1:&amp;\text{ at least one of }\beta_j\neq 0 \text{ for } j=2,3 \\
\end{split}
</span> We can test this using a partial <span class="math inline">F</span>-test because it involves testing whether a subset of our parameters are zero or not. Under <span class="math inline">H_0</span>: <span class="math display">F=\frac{\left(SSE_r-SSE_c\right)/\left( k-g \right)}{SSE_c/\left(n-k-1  \right)} \sim F_{k-g,n-k-1}</span> where <span class="math inline">k=3</span> and <span class="math inline">g=1</span>. We can estimate the complete and reduced models in R and use the <code>anova()</code> function to calculate the <span class="math inline">F</span> test statistic. The complete model again is: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}] = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i1} x_{i2}
</span> And the reduced model is: <span class="math display">
\mathbb{E}[Y_i|x_{i1}] = \beta_0 + \beta_1 x_{i1}
</span> We estimate these in R with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"penguins.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper <span class="sc">~</span> weight <span class="sc">*</span> female, <span class="at">data =</span> df)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>m_r <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper <span class="sc">~</span> weight, <span class="at">data =</span> df)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m_r, m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: flipper ~ weight
Model 2: flipper ~ weight * female
  Res.Df   RSS Df Sum of Sq      F      Pr(&gt;F)    
1    331 15516                                    
2    329 14432  2    1084.3 12.359 0.000006675 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The <span class="math inline">F</span> statistic is 12.359. To get the critical value we can use <span class="math inline">k-g=2</span> numerator degrees of freedom (which can be read under <code>Df</code> in the <code>anova()</code> table) and <span class="math inline">n-k-1=329</span> denominator degrees of freedom (which can be read under <code>Res.Df</code> for model 2 in the <code>anova()</code> table):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">2</span>, <span class="dv">329</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.023176</code></pre>
</div>
</div>
<p>Because the test statistic is larger than the critical value, we reject <span class="math inline">H_0</span>. There is evidence for a gender effect at the 5% level.</p>
</section>
<section id="exercise-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-2">Exercise 2</h3>
<p>The model we want to estimate is:</p>
<p><span class="math display">
\begin{split}
\mathbb{E}[Y_i|x_{i1},x_{i2},x_{i3},x_{i4}]
=&amp;\beta_0 +
\beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i3} + \\ &amp;\beta_4 x_{i4} +
\beta_5 x_{i2}x_{i3} + \beta_6 x_{i2}x_{i4}
\end{split}
</span> where <span class="math inline">x_{i1}</span> is weight, <span class="math inline">x_{i2}</span> is the gender dummy, <span class="math inline">x_{i3}</span> is a Chinstrap dummy and <span class="math inline">x_{i4}</span> is a Gentoo dummy.</p>
<p>Because Adelie is first alphabetically, it will automatically be chosen as the base category. We can therefore estimate the model with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper <span class="sc">~</span> weight <span class="sc">+</span> female <span class="sc">*</span> species, <span class="at">data =</span> df)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper ~ weight + female * species, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.2967  -3.0669   0.1011   3.2077  17.8867 

Coefficients:
                           Estimate  Std. Error t value          Pr(&gt;|t|)    
(Intercept)             164.7359574   3.8450416  42.844           &lt; 2e-16 ***
weight                    0.0068443   0.0009387   7.291 0.000000000002342 ***
female                    0.0011404   1.0755159   0.001          0.999155    
speciesChinstrap          8.2161927   1.0948508   7.504 0.000000000000593 ***
speciesGentoo            19.2649982   1.6311172  11.811           &lt; 2e-16 ***
female:speciesChinstrap  -5.3593575   1.5617432  -3.432          0.000677 ***
female:speciesGentoo     -3.3248938   1.3032191  -2.551          0.011189 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.252 on 326 degrees of freedom
Multiple R-squared:  0.8621,    Adjusted R-squared:  0.8596 
F-statistic: 339.8 on 6 and 326 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>For adelie penguins, the model simplifies to: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2},x_{i3}=0,x_{i4}=0]
=\beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2}
</span> For female adelie penguins, the model is: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}=1,x_{i3}=0,x_{i4}=0]
=\beta_0 + \beta_1 x_{i1} + \beta_2
</span> For male adelie penguins, the model is: <span class="math display">
\mathbb{E}[Y_i|x_{i1},x_{i2}=0,x_{i3}=0,x_{i4}=0]
=\beta_0 + \beta_1 x_{i1}
</span> Taking differences:</p>
<p><span class="math display">
\begin{split}
&amp;\mathbb{E}[Y_i|x_{i1},x_{i2}=1,x_{i3}=0,x_{i4}=0] - \\&amp;\mathbb{E}[Y_i|x_{i1},x_{i2}=0,x_{i3}=0,x_{i4}=0] =\beta_2
\end{split}
</span> So <span class="math inline">\beta_2</span> represents the average difference between female and male adelie penguins <em>of the same weight</em>.</p>
<p>Therefore the claim is asking if <span class="math inline">\beta_2&gt;0</span>. This is the alternative hypothesis. We are now ready to perform the test.</p>
<p>The null and alternative hypotheses are:</p>
<p><span class="math display">
\begin{split}
H_0:&amp;\beta_2 \leq 0\\
H_1:&amp;\beta_2 &gt; 0\\
\end{split}
</span> Under <span class="math inline">H_0</span>, <span class="math inline">T=\frac{B_2}{S_{B_2}}\sim t_{n-k-1}</span>. The value of the test statistic can be read from the table (0.001) or extracted directly with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m))[<span class="st">"female"</span>, <span class="st">"t value"</span>]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001060368</code></pre>
</div>
</div>
<p>The <span class="math inline">p</span>-value for this upper-tail test can be calculated with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(t, m<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4995773</code></pre>
</div>
</div>
<p>The <span class="math inline">p</span>-value is greater than the significance level of 1%. We therefore fail to reject the null hypothesis. There is not sufficient evidence for the claim.</p>
</section>
<section id="exercise-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-3">Exercise 3</h3>
<p>We first read in the data and get the variables ready to be used in the regression model before estimating it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"ebill90.csv"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create trend term (using the row number):</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>t <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert month to a factor variable specifying the order of the levels to be</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># "Jan", "Feb", ..., "Nov", "Dec":</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>month, <span class="at">levels =</span> <span class="fu">unique</span>(df<span class="sc">$</span>month))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify "Dec" to be the base level/category:</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">relevel</span>(<span class="fu">factor</span>(df<span class="sc">$</span>month), <span class="at">ref =</span> <span class="st">"Dec"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the model:</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(avg_bill <span class="sc">~</span> t <span class="sc">+</span> month, <span class="at">data =</span> df)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = avg_bill ~ t + month, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-79.223 -17.710  -4.021  15.585  93.801 

Coefficients:
             Estimate Std. Error t value   Pr(&gt;|t|)    
(Intercept) 137.21747   12.39744  11.068    &lt; 2e-16 ***
t            -0.44398    0.09087  -4.886 0.00000363 ***
monthJan     35.29325   15.37691   2.295    0.02367 *  
monthFeb     67.40223   15.37127   4.385 0.00002724 ***
monthMar     31.31921   15.36616   2.038    0.04400 *  
monthApr      9.32719   15.36159   0.607    0.54502    
monthMay    -25.65484   15.35756  -1.671    0.09774 .  
monthJun    -45.63786   15.35407  -2.972    0.00365 ** 
monthJul    -32.33988   15.35111  -2.107    0.03748 *  
monthAug    -30.87591   15.34869  -2.012    0.04677 *  
monthSep    -28.84693   15.34680  -1.880    0.06287 .  
monthOct    -41.33895   15.34546  -2.694    0.00820 ** 
monthNov    -43.06698   15.34465  -2.807    0.00595 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 34.31 on 107 degrees of freedom
Multiple R-squared:  0.5994,    Adjusted R-squared:  0.5545 
F-statistic: 13.34 on 12 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The month dummies show us how expensive each month is <em>on average</em> relative to December. We can see that January-April are more expensive than December and the other months cheaper. This makes sense because we use more electricty in the Winter. The most expensive month is February, which is usually the coldest month in the US.</p>
</section>
<section id="exercise-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-4">Exercise 4</h3>
<p>We extract the residuals from the model and create a scatter plot of them over time (using the trend term):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>e <span class="ot">&lt;-</span> m<span class="sc">$</span>residuals</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(t, e)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial4_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see clear patterns. For example, between periods 80-100 all the residuals are negative. If the residuals are independent, then this occurring should almost never happen. Therefore there is clear evidence that the residuals display serial correlation.</p>
</section>
<section id="exercise-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-5">Exercise 5</h3>
<p>To formally test for first-order serial correlation, we estimate a model with the model’s residuals <span class="math inline">e_t</span>: <span class="math display">
            e_t = \gamma_0 + \gamma_1e_{t-1}+ \nu_t
</span> We then apply a <span class="math inline">t</span>-test (significance test) on <span class="math inline">\gamma_1</span>. Under <span class="math inline">H_0</span> there is <em>no</em> first-order autocorrelation and under <span class="math inline">H_1</span> is there is first-order autocorrelation.</p>
<p>We now get the lagged residuals and estimate the auxiliary model in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>lag_e <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, df<span class="sc">$</span>e[<span class="dv">1</span><span class="sc">:</span>(<span class="fu">nrow</span>(df)<span class="sc">-</span><span class="dv">1</span>)])</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>aux <span class="ot">&lt;-</span> <span class="fu">lm</span>(e <span class="sc">~</span> lag_e, <span class="at">data =</span> df)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aux)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e ~ lag_e, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-51.217 -14.599  -0.544   8.931 100.792 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.11450    2.26048   0.051     0.96    
lag_e        0.65919    0.06949   9.487 3.54e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 24.66 on 117 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.4348,    Adjusted R-squared:  0.4299 
F-statistic: 89.99 on 1 and 117 DF,  p-value: 3.535e-16</code></pre>
</div>
</div>
<p>We can see that the test statistic is large (9.487) and the <span class="math inline">p</span>-value is very small (<code>3.54e-16</code> is close to zero). This is smaller than the significance level of 5% so we reject the null hypothesis. There is evidence of serial correlation at the 5% level. This confirms our conclusion in the previous question using the scatter plot.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>