<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="tutorial3_files/libs/clipboard/clipboard.min.js"></script>
<script src="tutorial3_files/libs/quarto-html/quarto.js"></script>
<script src="tutorial3_files/libs/quarto-html/popper.min.js"></script>
<script src="tutorial3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="tutorial3_files/libs/quarto-html/anchor.min.js"></script>
<link href="tutorial3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="tutorial3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="tutorial3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="tutorial3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="tutorial3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<link rel="stylesheet" href="style.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a>
  <ul class="collapse">
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tutorial 3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""> <link href="https://fonts.googleapis.com/css2?family=Fira+Mono&amp;family=Fira+Sans&amp;display=swap" rel="stylesheet"></p>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>In this tutorial we will study two datasets. The first is the <a href="https://walshc.github.io/stats2/rottentomatoes.csv">rottentomatoes.csv</a> dataset. This featured in the exam in October 2021. The dataset contains the Rotten Tomatoes rating of a random sample of movies with their length, year of release, and dummy variables for their genres. Here is a screenshot of the description from the exam:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="rt-exam-description.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Rotten Tomatoes Data Description</figcaption>
</figure>
</div>
<p>The second is the <a href="https://walshc.github.io/stats2/cv.csv">cv.csv</a> dataset. This featured in the resit exam in January 2020. This dataset contains employers’ ratings of different CVs, where we observe the applicant’s GPA and dummy variables for ethnicity, gender, skills and experience.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="cv-exam-description.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">CV Data Description</figcaption>
</figure>
</div>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li>Using the <a href="https://walshc.github.io/stats2/rottentomatoes.csv">rottentomatoes.csv</a> dataset, regress <code>rating</code> on <code>length</code> and <code>year</code>. Interpret each of the estimated regression coefficients.</li>
<li>Using the <a href="https://walshc.github.io/stats2/rottentomatoes.csv">rottentomatoes.csv</a> dataset, regress <code>rating</code> on all of the other variables. Use this model to answer the following questions:
<ol type="a">
<li>Report a 95% confidence interval for the coefficient on <code>romance</code> and interpret it.</li>
<li>Which genres are individually statistically significant at the 5% level, and which are not?</li>
<li>Test if this model is useful at the 1% level using a critical value approach.</li>
<li>What proportion of the variation in <code>rating</code> is left unexplained by the model?</li>
<li>Test the claim that “older movies are better” for a given length and genre. Use a <span class="math inline">p</span>-value approach with a 5% level.</li>
<li>Obtain a 95% confidence interval for the average rating of 90-minute romantic comedy movies from 2010.</li>
</ol></li>
<li>With the <a href="https://walshc.github.io/stats2/cv.csv">cv.csv</a> dataset, regress <code>rating</code> on all 7 of the other variables and use it to test the following claims (each at the 5% level):
<ol type="a">
<li>“Displaying technical skills has an impact on your CV’s rating.”</li>
<li>“Doing an second internship makes your CV look better from an employer’s perspective.”</li>
<li>“Doing an unpaid internship on average raises your CV score by more than 0.2 points.”</li>
<li>“Employers on average rate female/male or white/nonwhite CVs differently, holding everything else fixed.”</li>
</ol></li>
</ol>
</section>
<section id="solutions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="solutions">Solutions</h2>
<section id="exercise-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-1">Exercise 1</h3>
<p>We read in the data and estimate the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>rt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"rottentomatoes.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> length <span class="sc">+</span> year, <span class="at">data =</span> rt)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ length + year, data = rt)

Residuals:
    Min      1Q  Median      3Q     Max 
-44.407  -9.103  -1.018   8.578  39.451 

Coefficients:
             Estimate Std. Error t value        Pr(&gt;|t|)    
(Intercept) 357.06709  148.82283   2.399          0.0166 *  
length        0.13084    0.01922   6.808 0.0000000000171 ***
year         -0.15707    0.07380  -2.128          0.0336 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.77 on 997 degrees of freedom
Multiple R-squared:  0.05059,   Adjusted R-squared:  0.04869 
F-statistic: 26.56 on 2 and 997 DF,  p-value: 0.000000000005758</code></pre>
</div>
</div>
<p>We interpret the estimates:</p>
<ul>
<li><p>The intercept gives the model’s estimate of average rating of movies that are zero minutes long and from year 0. Of course no movies have these characteristics and this is far outside the range of our data, so we should not pay attention to it. In fact, there is no year zero in the anno Domini calendar system: the years before and after the birth of Christ go 3 BC, 2 BC, 1 BC, 1 AD, 2 AD, 3 AD.</p></li>
<li><p>The estimated coefficient on <code>length</code> says that on average a one-minute longer movie has a 0.1308 higher rating on average, holding the release year fixed.</p></li>
<li><p>The estimated coefficient on <code>year</code> says that on average a one-year <em>younger</em> movie has a 0.1571 <em>lower</em> rating on average, holding the length fixed. Alternatively, we can say that on average a one-year <em>older</em> movie has a 0.1571 <em>higher</em> rating on average, holding the length fixed.</p></li>
</ul>
</section>
<section id="exercise-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-2">Exercise 2</h3>
<p>One way to do this is to write out the entire formula as we normally do:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> length <span class="sc">+</span> year <span class="sc">+</span> comedy <span class="sc">+</span> action <span class="sc">+</span> drama <span class="sc">+</span> documentary <span class="sc">+</span> romance <span class="sc">+</span> horror <span class="sc">+</span> thriller, <span class="at">data =</span> rt)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ length + year + comedy + action + drama + 
    documentary + romance + horror + thriller, data = rt)

Residuals:
    Min      1Q  Median      3Q     Max 
-42.626  -8.462  -0.780   8.116  39.638 

Coefficients:
             Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept) 336.36156  148.03220   2.272      0.023287 *  
length        0.11581    0.01994   5.809 0.00000000848 ***
year         -0.14856    0.07342  -2.023      0.043294 *  
comedy        3.19065    0.98482   3.240      0.001236 ** 
action        4.17174    1.13514   3.675      0.000251 ***
drama         3.48755    0.92936   3.753      0.000185 ***
documentary   4.76121    1.51256   3.148      0.001694 ** 
romance       1.24938    1.10940   1.126      0.260363    
horror        3.71544    1.50504   2.469      0.013730 *  
thriller      1.97002    1.10667   1.780      0.075362 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.6 on 990 degrees of freedom
Multiple R-squared:  0.08259,   Adjusted R-squared:  0.07425 
F-statistic: 9.903 on 9 and 990 DF,  p-value: 0.00000000000001214</code></pre>
</div>
</div>
<p>But a trick to estimate a model using <em>all other</em> variables in a dataframe is to use a <code>.</code> in place of all the other variables. Like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> ., <span class="at">data =</span> rt) </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ ., data = rt)

Residuals:
    Min      1Q  Median      3Q     Max 
-42.626  -8.462  -0.780   8.116  39.638 

Coefficients:
             Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept) 336.36156  148.03220   2.272      0.023287 *  
length        0.11581    0.01994   5.809 0.00000000848 ***
year         -0.14856    0.07342  -2.023      0.043294 *  
comedy        3.19065    0.98482   3.240      0.001236 ** 
action        4.17174    1.13514   3.675      0.000251 ***
drama         3.48755    0.92936   3.753      0.000185 ***
documentary   4.76121    1.51256   3.148      0.001694 ** 
romance       1.24938    1.10940   1.126      0.260363    
horror        3.71544    1.50504   2.469      0.013730 *  
thriller      1.97002    1.10667   1.780      0.075362 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.6 on 990 degrees of freedom
Multiple R-squared:  0.08259,   Adjusted R-squared:  0.07425 
F-statistic: 9.903 on 9 and 990 DF,  p-value: 0.00000000000001214</code></pre>
</div>
</div>
<p>We can see that it gives the same output.</p>
<section id="exercise-2a" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-2a">Exercise 2a</h4>
<p>We get a 95% confidence interval for <code>romance</code> with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m2, <span class="at">parm =</span> <span class="st">"romance"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            2.5 %  97.5 %
romance -0.927663 3.42643</code></pre>
</div>
</div>
<p>We are 95% confidence that the true <span class="math inline">\beta_7</span> on <code>romance</code> is between -0.9277 and 3.4264. Because this confidence interval contains zero we cannot say that <span class="math inline">\beta_7\neq 0</span> at the 5% level.</p>
</section>
<section id="exercise-2b" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-2b">Exercise 2b</h4>
<p>We can look at the <span class="math inline">p</span>-values in the coefficients table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(m2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate   Std. Error   t value          Pr(&gt;|t|)
(Intercept) 336.3615618 148.03220098  2.272219 0.023287061616251
length        0.1158077   0.01993698  5.808689 0.000000008479459
year         -0.1485607   0.07341919 -2.023458 0.043294183705080
comedy        3.1906481   0.98482208  3.239822 0.001235876710249
action        4.1717357   1.13514273  3.675076 0.000250537812391
drama         3.4875486   0.92935872  3.752640 0.000185155544793
documentary   4.7612096   1.51255622  3.147790 0.001694305181887
romance       1.2493835   1.10940043  1.126179 0.260362668976212
horror        3.7154420   1.50504381  2.468660 0.013729962646249
thriller      1.9700183   1.10667300  1.780127 0.075361848971758</code></pre>
</div>
</div>
<p>Of the genre coefficients, all are significant at the 5% level except <code>romance</code> and <code>thriller</code>.</p>
</section>
<section id="exercise-2c" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-2c">Exercise 2c</h4>
<p>The null and alternative hypotheses are:</p>
<p><span class="math display">
\begin{split}
H_0 :&amp; \beta_1=...=\beta_9=0 \\
H_1 :&amp; \text{ at least one of } \beta_j\neq 0 \text{ for } j=1,\dots,9
\end{split}
</span> Under <span class="math inline">H_0</span>, <span class="math inline">F=\frac{SSR/k}{SSE/(n-k-1}\sim F_{k,n-k-1}</span>. The value of the test statistic in our sample is 9.90333:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)<span class="sc">$</span>fstatistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    value     numdf     dendf 
  9.90333   9.00000 990.00000 </code></pre>
</div>
</div>
<p>This can also be seen directly in the <code>summary(m2)</code> output. The critical value is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.99</span>, <span class="dv">9</span>, <span class="dv">990</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.425224</code></pre>
</div>
</div>
<p>Because the test statistic is greater than the critical value, we reject <span class="math inline">H_0</span> and conclude that the model is useful at the 1% level.</p>
</section>
<section id="exercise-2d" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-2d">Exercise 2d</h4>
<p>The <span class="math inline">R^2</span> measures the proportion of the variation in <code>rating</code> that is explained by the model. The proportion left unexplained is <span class="math inline">1-R^2</span>. We can calculate this with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">summary</span>(m2)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9174057</code></pre>
</div>
</div>
<p>So the proprtion left unexplained is 0.9174. This corresponds to 91.7406% left unexplained.</p>
</section>
<section id="exercise-2e" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-2e">Exercise 2e</h4>
<p>The claim is equivalent to <span class="math inline">\beta_2 &lt; 0</span>, as older movies have a smaller year. With <span class="math inline">\beta_2&lt;0</span>, movies with a larger year (younger) are worse and so movies with a smaller year (older) are better.</p>
<p>The null and alternative hypotheses are:</p>
<p><span class="math display">
\begin{split}
H_0 :&amp; \beta_2\geq 0 \\
H_1 :&amp; \beta_2 &lt; 0
\end{split}
</span> Under <span class="math inline">H_0</span>, <span class="math inline">t=\frac{B_2}{S_{B_1}}\sim t_{n-k-1}</span>. The value of the test statistic in our sample is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>b_2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m2))[<span class="st">"year"</span>, <span class="st">"Estimate"</span>]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>s_b_2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m2))[<span class="st">"year"</span>, <span class="st">"Std. Error"</span>]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>(t <span class="ot">&lt;-</span> b_2 <span class="sc">/</span> s_b_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.023458</code></pre>
</div>
</div>
<p>It turns out this is also the value under the “t value” column in the main coefficients table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(m2))[<span class="st">"year"</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Estimate  Std. Error     t value    Pr(&gt;|t|) 
-0.14856068  0.07341919 -2.02345839  0.04329418 </code></pre>
</div>
</div>
<p>This is because this column always gives the value of the test statistic when the hinge is zero, so we could have just used that value.</p>
<p>The <span class="math inline">p</span>-value for this lower-tailed test is then:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(t, m2<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02164709</code></pre>
</div>
</div>
<p>Because this <span class="math inline">p</span>-value is smaller than the significance level of 0.05, we reject the null hypothesis. Older movies are rated higher, given their length and genre.</p>
</section>
<section id="exercise-2f" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-2f">Exercise 2f</h4>
<p>We create a dataframe with one observation with the desired values, and use it in the <code>predict()</code> function with the <code>"confidence"</code> option for <code>interval</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df_p <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">length =</span> <span class="dv">90</span>, <span class="at">year =</span> <span class="dv">2010</span>, <span class="at">romance =</span> <span class="dv">1</span>,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">comedy =</span> <span class="dv">1</span>,  <span class="at">action =</span> <span class="dv">0</span>, <span class="at">drama =</span> <span class="dv">0</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">documentary =</span> <span class="dv">0</span>, <span class="at">horror =</span> <span class="dv">0</span>, <span class="at">thriller =</span> <span class="dv">0</span>) </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m2, df_p, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 52.61733 50.23863 54.99603</code></pre>
</div>
</div>
<p>We are 95% confident that the average rating of 90-minute romantic comedies from 2010 is between 50.2386 and 54.9960.</p>
</section>
</section>
<section id="exercise-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-3">Exercise 3</h3>
<p>We use the same trick as above to estimate a model using all variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"cv.csv"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> ., <span class="at">data =</span> cv)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ ., data = cv)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.4256 -2.0923  0.0327  1.9098  6.8236 

Coefficients:
              Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept)   -3.45532    0.58832  -5.873 0.00000000482 ***
gpa            2.12006    0.16073  13.190       &lt; 2e-16 ***
white          0.08135    0.10249   0.794       0.42739    
female        -0.03893    0.09755  -0.399       0.68990    
tech_skills    0.05433    0.11258   0.483       0.62941    
unpaid_intshp  0.25416    0.12075   2.105       0.03540 *  
top_intshp     0.99609    0.09933  10.028       &lt; 2e-16 ***
second_intshp  0.34441    0.11907   2.893       0.00385 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.476 on 2576 degrees of freedom
Multiple R-squared:  0.09667,   Adjusted R-squared:  0.09422 
F-statistic: 39.38 on 7 and 2576 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="exercise-3a" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-3a">Exercise 3a</h4>
<p>The claim is “Displaying technical skills has an impact on your CV’s rating.” This corresponds to <span class="math inline">\beta_4\neq0</span>. So the null and alternative hypotheses are <span class="math inline">H_0:\beta_4=0</span> and <span class="math inline">H_1:\beta_4\neq 0</span>. This is just a test for individual statistical significance so we can look directly at the <span class="math inline">p</span>-value for <code>tech_skills</code>. The <span class="math inline">p</span>-value is 0.62941 which is greater than 0.05. Therefore there is insufficient evidence for the claim.</p>
</section>
<section id="exercise-3b" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-3b">Exercise 3b</h4>
<p>The claim is “Doing an second internship makes your CV look better from an employer’s perspective.” This corresponds to <span class="math inline">\beta_7&gt;0</span>. So the null and alternative hypotheses are <span class="math inline">H_0:\beta_7\leq 0</span> and <span class="math inline">H_1:\beta_7&gt; 0</span>. Under <span class="math inline">H_0</span>, <span class="math inline">T=B_7/S_{B_7}\sim t_{n-k-1}</span>. The value of the test statistic can be read from the coefficients table because the test has a hinge of zero. We see it is 2.893:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(m3))[<span class="st">"second_intshp"</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Estimate  Std. Error     t value    Pr(&gt;|t|) 
0.344412728 0.119065429 2.892634164 0.003852309 </code></pre>
</div>
</div>
<p>The critical value for this upper-tail test is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>, m3<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.645445</code></pre>
</div>
</div>
<p>The test statistic is greater than the critical value so we reject <span class="math inline">H_0</span>. There is sufficient evidence for the claim at the 5% level.</p>
</section>
<section id="exercise-3c" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-3c">Exercise 3c</h4>
<p>The claim is “Doing an unpaid internship on average raises your CV score by more than 0.2 points.” This corresponds to <span class="math inline">\beta_5&gt;0.2</span>. We estimate <span class="math inline">b_2=0.25416</span> so the question is if this is enough evidence to say that <span class="math inline">\beta_5&gt;0.2</span> in the population. The null and alternative hypotheses are <span class="math inline">H_0:\beta_5\leq 0.2</span> and <span class="math inline">H_1:\beta_5&gt; 0.2</span>. Under <span class="math inline">H_0</span>, <span class="math inline">T=\left(B_5-0.2\right)/S_{B_5}\sim t_{n-k-1}</span>. The value of the test statistic must be calculated manually because the hinge is non-zero:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>b_5 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m3))[<span class="dv">6</span>, <span class="dv">1</span>]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>s_b_5 <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(m3))[<span class="dv">6</span>, <span class="dv">2</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>(t <span class="ot">&lt;-</span> (b_5 <span class="sc">-</span> <span class="fl">0.2</span>) <span class="sc">/</span> s_b_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4485035</code></pre>
</div>
</div>
<p>We compare this to the critical value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>, m3<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.645445</code></pre>
</div>
</div>
<p>The test statistic is smaller than the critical value so we fail to reject <span class="math inline">H_0</span>. There is insufficient evidence for the claim at the 5% level.</p>
</section>
<section id="exercise-3d" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-3d">Exercise 3d</h4>
<p>The claim is “Employers on average rate female/male or white/nonwhite CVs differently, holding everything else fixed.” This corresponds to <code>white</code> and <code>female</code> being jointly useful in the model. We test this with a partial <span class="math inline">F</span> test.</p>
<p>The null and alternative hypotheses are:</p>
<ul>
<li><span class="math inline">H_0: \beta_2=\beta_3=0</span>.</li>
<li><span class="math inline">H_1: \beta_2\neq 0</span> or <span class="math inline">\beta_3 \neq 0</span> or both.</li>
</ul>
<p>We form the test statistic: Under <span class="math inline">H_0</span>: <span class="math display">
        F=\frac{\left(SSE_r-SSE_c\right)/\left( k-g \right)}{SSE_c/\left(n-k-1  \right)}\sim F_{k-g,n-k-1}
</span> where the complete model includes all variables and the reduced model excludes <code>white</code> and <code>female</code>. The can compute the value of the test statistic by estimating both the reduced and complete models and using them in the <code>anova()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>m3_r <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> gpa <span class="sc">+</span> tech_skills <span class="sc">+</span> unpaid_intshp <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>           top_intshp <span class="sc">+</span> second_intshp, <span class="at">data =</span> cv)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m3_r, m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: rating ~ gpa + tech_skills + unpaid_intshp + top_intshp + second_intshp
Model 2: rating ~ gpa + white + female + tech_skills + unpaid_intshp + 
    top_intshp + second_intshp
  Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)
1   2578 15800                           
2   2576 15796  2    4.7272 0.3855 0.6802</code></pre>
</div>
</div>
<p>The value of the test statistic is 0.3855. The <span class="math inline">p</span>-value is 0.6802. Because the <span class="math inline">p</span>-value is greater than the significance level, we fail to reject the null hypothesis. There is no evidence that employers rate female and male or white and nonwhite CVs differently at the 5% level.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>